### ISSUE TITLE
Red Mountain Sky

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#100]
so In red mountain the sky cuts off perhaps it should be expanded?

![capture](https://cloud.githubusercontent.com/assets/15071652/24234338/2d6c97fe-0f6e-11e7-82e8-3c3b10cf5955.PNG)
![capturef](https://cloud.githubusercontent.com/assets/15071652/24234454/d19a6478-0f6e-11e7-822f-3d631a82298e.PNG)

Happens in DC to
![capture6](https://cloud.githubusercontent.com/assets/15071652/24234373/52ae4670-0f6e-11e7-8c6a-35c41e5294a4.PNG)

**Comment by PiKeyAr** [comment]
The reason it cuts off is because of the cloud object's size, it gets repositioned based on the camera's X and Z values. I tried making the object bigger, but it causes the transparency artifacts to become even more noticeable, so expanding it isn't feasible at the moment.
