### ISSUE TITLE
Egg Carrier Inaccuracies 2

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#101]
Well the Latest Update to the PL mod fixes the lighting but some objects ignore the lighting as you can see

DC
![capture](https://cloud.githubusercontent.com/assets/15071652/24271896/54d9642e-0ff1-11e7-89ce-f7840074f2b1.PNG)
PC
![capturef](https://cloud.githubusercontent.com/assets/15071652/24271897/54dbb314-0ff1-11e7-8ea9-db6b8785109f.PNG)

**Comment by PiKeyAr** [comment]
That's a palette selection issue I can't fix on my end yet. https://github.com/SonicFreak94/sadx-dc-lighting/issues/43
