### ISSUE TITLE
Mystic Ruins Base problems

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#102]
So, one of the things I'm going to plan on doing for the layout fixes for Mystic Ruins is deleting an oddly-placed door in the base. It's a Final Egg door, the very same that you have to do that puzzle to open. It's placed in a wall, above the door on the lower floor. Thing is, it's not a mistake. At least, not on the Dreamcast version. On the DC version, there's a large hole in the landtable, which Sonic Team plugged with this door that looks horrible. However, on SADX, when they redesigned the room to make the spinning machinery below more visible, they actually went and patched that hole!
![sadx landtable fixed the hole in the wall](https://cloud.githubusercontent.com/assets/26051785/24275643/fc34c242-0ffe-11e7-8e5b-75d2d75fe887.png)
It's a bit darker than the other models, but it works for what it needs to do. Having the FE door sticking through the wall looks *sloppy*, so would it be possible to port that part of the landtable over?

The other problem are these lights. The red and green ones.
![dreamcast mr base lights](https://cloud.githubusercontent.com/assets/26051785/24275665/29a571c2-0fff-11e7-8685-02f4292d6a17.png)
Currently, in the DC mod, only some of them look like this. They're *all* meant to look this way.

Also, would it be all right to fix the collision on those platforms? It looks silly with Sonic's feet in the floor.

**Comment by PiKeyAr** [comment]
The lights were easy to fix since the issue was caused by material colors, as for the other things I'm not very interested. The landtable piece is set up differently in SADX, so I'd have to port the entire wall over for just that.

As for the collision thing, that looks like something for your SET layout fixes mod.

**Comment by supercoolsonic** [comment]
Hmmm....I see. Perhaps I can work with the door in a different way. Alright. Thanks for the quick reply. The new update system is pretty cool. Don't have to bother with MEGA's *too slow* download speed anymore.

**Comment by supercoolsonic** [comment]
Could I ask a quick question? So I got the updates to Windy Valley, DC General, and the Mystic Ruins, but how would I go about viewing a changelog so I know exactly what's different? Like in Windy Valley. I have no idea what's different.
