### ISSUE TITLE
DC_General removes Rhinotank smoke effect

### ISSUE THREAD

**Issue by LighteningXL** [PiKeyAr/sadx_dreamcast#103]
DC_General
![untitled](https://cloud.githubusercontent.com/assets/26220489/24276665/a7917a54-100e-11e7-8c3c-c425f6acef7c.png)

No DC_General
![untitled1](https://cloud.githubusercontent.com/assets/26220489/24276671/ad5bb878-100e-11e7-9994-6477302cff58.png)

**Comment by PiKeyAr** [comment]
Thanks for the report, should be good now.

**Comment by LighteningXL** [comment]
So I got the update and it gave Rhinotank a different texture.
![untitled](https://cloud.githubusercontent.com/assets/26220489/24277416/4b5ed95c-1013-11e7-97ae-cf0e4b69096a.png)

**Comment by PiKeyAr** [comment]
I'm not sure how you got the update but it certainly looks like E_SAI.PVM or E_SAI texture pack hasn't been updated properly. Try again.

**Comment by LighteningXL** [comment]
I removed my DC_General and took the one from ModDB update 4. Then I startup mod manager and the following notification for an update appears for DC_General.
![screenshot_20170323220943](https://cloud.githubusercontent.com/assets/26220489/24277838/3a3d1ae6-1016-11e7-88d3-f2c9cc2b13e5.png)
![screenshot_20170323221009](https://cloud.githubusercontent.com/assets/26220489/24277842/3bb0a0c8-1016-11e7-909c-34dbb0fa4fcb.png)

I clicked install now and save & play, but the model still has water texture w/o smoke effect.

**Comment by PiKeyAr** [comment]
Check if there's an E_SAI folder in DC_General/textures. If there is, it might be a bug in the Mod Loader's update system.

**Comment by LighteningXL** [comment]
I see the E_SAI folder and nothing inside.
![screen shot 03-23-17 at 10 22 pm](https://cloud.githubusercontent.com/assets/26220489/24278019/83c9bf74-1017-11e7-93e7-3e1f1de8fca4.PNG)

**Comment by PiKeyAr** [comment]
Yeah, you need to delete it. Apparently the Mod Loader's update system can't delete empty folders yet, which makes the Mod Loader think there's a texture pack for that PVM, but it breaks because the folder is empty.

**Comment by LighteningXL** [comment]
Well crap! Thanks, removed it. Now his texture is fixed with the smoke effect 🖒

**Comment by PiKeyAr** [comment]
Great! I've reported the folder problem to the authors of the Mod Loader, so it should be fixed soon. When it's fixed, I'll push another update for the DC_General mod to make sure everyone updates properly.
