### ISSUE TITLE
Casinopolis in the dark and untextured piece in the Mystic Ruins?

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#104]
Not sure if it's the DC Lighting mod, or the most recent update to Casinopolis, but...
![pitch-black](https://cloud.githubusercontent.com/assets/26051785/24306693/74d65b94-108f-11e7-9eb2-8bcd0202de24.png)
Everything is dark.

Also having trouble updating the palette mod through the mod updater. It's missing a manifest file. I downloaded the most recent version, but it still says there's an update available.

Edit: Confirmed. It's a problem with the most recent update to the DC Casinopolis mod.

Edit 2: Also, I just noticed this.
![ummm](https://cloud.githubusercontent.com/assets/26051785/24307673/0da8543c-1093-11e7-8d2f-c72a8ff5cb71.png)
Were you able to port that piece over? If you did, all you need to do (I think) is give it a texture and proper UVs!

Edit 3: You got the grass object to use that second texture! Hooray!

**Comment by Zetchzie** [comment]
you'll need to manually get the PL updates. Manifest are only in official releases. to remove the update nag go to the mod.ini and delete its update url

**Comment by supercoolsonic** [comment]
Okay, that made me laugh. Nice. Casinopolis crashes for you, huh? Interesting. I wonder what could've happened. (This is why a more detailed changelog would be nice.)

And thanks for informing me on how to get rid of that update thing.

**Comment by Zetchzie** [comment]
no prob ^^

**Comment by Thesch28** [comment]
OK.... So I decided to try the new update feature that modloader has and I downloaded the new update for casinopolis and this happened: http://i.imgur.com/s4KofgM.png everything has the wrong Texture!!  xD
why? By the way I haven't experienced the same texturing as u supercoolsonic, I think is may have something to do with the new update feature.

**Comment by Zetchzie** [comment]
I haven't seen a Casinopolis commit pushed here recently so idk

**Comment by PiKeyAr** [comment]
I can't reproduce any of the above. The folders for DC_Casinopolis and DC_MysticRuins are identical between my PC and the server, so it might be a bug with the Mod Loader's update system.

**Comment by Thesch28** [comment]
That's exactly what I thought I guess I won't touch that update feature until it's updated.

**Comment by SonicFreak94** [comment]
Looking into it now!

**Comment by PiKeyAr** [comment]
The Mystic Ruins issue isn't caused by the update. Might be a SET object missing in a modified layout.

**Comment by supercoolsonic** [comment]
Oh, yeah. That's my personal layout. The door is gone. But normally on Dreamcast, that white model isn't there. It's normally a hole.

**Comment by PiKeyAr** [comment]
![demul_2017_03_25_09_50_15_594](https://cloud.githubusercontent.com/assets/23312549/24317888/6f22893c-1140-11e7-9341-fd14a94c72f9.png)
It's still there, but there's 2 differences:
1) The O HIDDEN GATE model appears different in SA1
2) It looks like the material of that landtable piece isn't ignoring lighting, whereas the actual SA1 landtable has the the "ignore light" flag enabled for that material. I can disable the "ignore light" flag in the landtable if that helps.

**Comment by PiKeyAr** [comment]
Or like, I can make it use a black texture that the other doors seem to use.

**Comment by supercoolsonic** [comment]
Well, it definitely looks better in your screenshot (minus the door in the wall). If it must be a single color, and not use a texture, it'd be best to be black, as white is typically associated with being untextured.

**Comment by PiKeyAr** [comment]
I can change the texture IDs to anything, but its UVs will make it look like a single color anyway, even in the SADX landtable.

**Comment by PiKeyAr** [comment]
I guess I'll just change the texture to black then. This is what the SADX landtable seems to have anyway.

**Comment by supercoolsonic** [comment]
I thought it looked like this on SADX.
![sadx landtable fixed the hole in the wall](https://cloud.githubusercontent.com/assets/26051785/24318077/b5fc4c58-10cd-11e7-8e64-d8ebb7f1be25.png)

**Comment by PiKeyAr** [comment]
That's part of the wall mesh in SADX. The "hole" causing it to look white is a different mesh.

**Comment by supercoolsonic** [comment]
Oh. Well then yeah. Black would be best.

**Comment by PiKeyAr** [comment]
The ModLoader has been updated to address the file removal problem, if you still can't update the Casino mod properly just [download this one](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/DC_Casinopolis.zip) and it will work properly with future updates.
