### ISSUE TITLE
Ice Cap Act 2 Wall Error

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#105]
So this happens in all versions of the game but I dont think it was intended my Sonic Team to be there

This one part of the wall ignores lighting or is just toned differently and it really stands out like an eyesore seeing as its a Square and its litteraly right there in plain sight when crossing the ice bridge 
![capture](https://cloud.githubusercontent.com/assets/15071652/24440500/7fcdad90-1422-11e7-960e-aef3d629cd4a.PNG)

**Comment by cheatfreak47** [comment]
If you fix this, a standalone DLL mod that fixes this on the original DX level, and maybe that ice patch with the square around it on the ground would be appreciated.

**Comment by PiKeyAr** [comment]
This isn't fixable without remodeling the entire wall. It happens because that square is a separate landtable piece, and fixing it would require merging the meshes together, which isn't something I could do. Same for the area near the start of Ice Cap 3.

**Comment by Zetchzie** [comment]
oh ok ^^
