### ISSUE TITLE
Windy Valley 1 Crash with new DC_General update

### ISSUE THREAD

**Issue by LighteningXL** [PiKeyAr/sadx_dreamcast#106]
My game crashes when I get up to the trampoline.
![untitled](https://cloud.githubusercontent.com/assets/26220489/24461041/fee8d8fc-146d-11e7-967a-9d135fba9333.jpg)

Then found out it was the new DC_General causing it. I went to grab the one from ModDB and update it but the crash still occurs. Here's what updating looks like.
![screenshot_20170329105028](https://cloud.githubusercontent.com/assets/26220489/24461247/8be45fe2-146e-11e7-9813-88bcb6eadcc7.png)

There are no empty folders.

**Comment by supercoolsonic** [comment]
Same happens for me. It's not even the trampoline, it's right after you leave that wind path.

**Comment by Zetchzie** [comment]
same here

**Comment by PiKeyAr** [comment]
It was some leftover debug code. Should be fixed now. Feel free to reopen this if you run into it again.
