### ISSUE TITLE
Ice Cap Act 2 giant icicle transparency

### ISSUE THREAD

**Issue by RinMaru** [PiKeyAr/sadx_dreamcast#107]
when you look through the giant ice you get a weird looking thing go on inside

![capture](https://cloud.githubusercontent.com/assets/15071652/24492858/b7e7ccdc-14fa-11e7-8e93-ecda8ac08142.PNG)

**Comment by PiKeyAr** [comment]
This will be fixed when depth peeling (order-independent transparency) is implemented in the PL mod.
![ztsq7re 1](https://cloud.githubusercontent.com/assets/23312549/24503328/94a88300-158c-11e7-98c8-32b2f39cc943.jpg)
For now, since there's no other way to make it work in SADX, it's going to #42.
