### ISSUE TITLE
Title Screen, File Select Screen, and other menus broke

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#108]
I think the latest updates to DC Branding might've broke something...
![whoops](https://cloud.githubusercontent.com/assets/26051785/24521184/e4536780-1550-11e7-84f5-17969cb013ad.png)

![oops](https://cloud.githubusercontent.com/assets/26051785/24521189/e6d05888-1550-11e7-80af-4fe2b0f96542.png)
Just a theory.

This happens on Character Select menu as well.

**Comment by PiKeyAr** [comment]
Your resolution settings don't match the window size specified in the Mod Loader. For the game to scale correctly on different resolutions, you need to have "Custom resolution" set up to match window size.

**Comment by supercoolsonic** [comment]
Oh. Alright, I fixed it. This can be closed, I guess. Wonder why that started to happen only now...
