### ISSUE TITLE
Sky Deck Act 1 to Act 2 transition broken (Sonic)

### ISSUE THREAD

**Issue by Sonikko** [PiKeyAr/sadx_dreamcast#109]
I just played through Sky Deck, at the end of Act 1, when you have to use the rocket to break the main cannon, and then you automatically transition to Act 2, nothing happens after launching the rocket, and Sonic just falls to his death.
![mods](https://cloud.githubusercontent.com/assets/24740235/24552402/90a32a36-1626-11e7-8986-92ff331577af.PNG)
These are my active mods and respective versions. I keep everything updated daily, both the mods and the Mod Loader!

EDIT: Just thinking about it, I forgot to enable the Set Layout Fixes mod by Supercoolsonic, I'll try right now. Should I disable SADX FE's set fixes, or do I use those in conjunction? Is SADX Fixed Ed code mod compatible with the DC conversion?

**Comment by PiKeyAr** [comment]
That usually happens if you dash through the level and use the rocket before the cannon finishes turning in your direction.

**Comment by Sonikko** [comment]
I tried 3 times and I always wait for the cannon to point at Sonic.

**Comment by PiKeyAr** [comment]
Well I don't really know how to help you. I can't reproduce it with or without the "Fixed SET layouts" mod.

**Comment by PiKeyAr** [comment]
>Should I disable SADX FE's set fixes, or do I use those in conjunction? Is SADX Fixed Ed code mod compatible with the DC conversion?


SADXFE Code is compatible, but SADXFE SET fixes aren't compatible for most levels. I'm not sure if there's any difference with that particular rocket between the default and Supercoolsonic's SET files, it's most likely a game code issue rather than a layout problem.

**Comment by supercoolsonic** [comment]
There might be a solution. I could try to make the rocket send you not as far as it does, so if it misses, you land on the platform. I'll look at it now.

**Comment by PiKeyAr** [comment]
I'll include the SET file with the next update of the SET fixes mod. In the meantime I think this can be closed.
