### ISSUE TITLE
Casino 2 flickering lights

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#111]
![green lighting](https://cloud.githubusercontent.com/assets/26051785/24823117/d996382e-1bc0-11e7-94d3-c023e16326ed.png)
(Ignore the red arrows. This is my personal layout.)

So, with the latest update to the Mod Loader and the Sky Deck update that recently went out, this happens. (Not caused by Super Sonic; happens as Knuckles, too) Not sure if it's a problem with the Mod Loader, but I don't know. If the camera approaches the green areas, the lighting disappears, and it looks normal.

Was there any reason to revert certain levels back to DC PVMs? Also, what was the change made to a fan in Windy Valley? I can't find it.

Edit: Gotcha. Wasn't aware of that about PVMs.

**Comment by Zetchzie** [comment]
DC PVMs Load faster and they are texture packs that didn't need altering to work so its more efficient to keep textures as PVM if we never had to edit anything in them to begin with. as far as the lighting bug gos idk

**Comment by supercoolsonic** [comment]
I also just noticed this:
![light layering problem](https://cloud.githubusercontent.com/assets/26051785/24824255/8f4e8f7a-1bcd-11e7-862d-ba0ddea1f7db.png)
The little lights that the flickering was restored for have layering issues. Fixable? Or Order-independent layering?

**Comment by PiKeyAr** [comment]
The green light is a texture filtering problem that happens with untouched Dreamcast PVMs, but only if anisotropic filtering is disabled. The yellow lights are difficult to fix within SADX limits wihout a hacky workaround that would need remaking each of them, and it wouldn't be compatible with SET edits, so I think I'll leave them at #42 for now.

**Comment by supercoolsonic** [comment]
What's anisotropic filtering, and how would I activate it?

**Comment by Zetchzie** [comment]
Anisotropic Filtering is a filter used by your GPU to try and keep textures sharp whenever viewed from different angles. If you have AMD or Nvidia you can enable it through Profiles.

**Comment by supercoolsonic** [comment]
So I got the Nvidia Profile Inspector, but what exactly do I change to activate it? I've been going through the Anisotropic filter settings, but nothing changes in-game.

**Comment by supercoolsonic** [comment]
Never mind. I got it. Thanks.

**Comment by PiKeyAr** [comment]
The lights should be fixed in today's update.
