### ISSUE TITLE
SADX Style Water update error

### ISSUE THREAD

**Issue by LimitCrown** [PiKeyAr/sadx_dreamcast#112]
After installing the latest updates to the mods, the water textures in the Station Square Adventure Field aren't correct when this mod is enabled.

**Comment by Zetchzie** [comment]
Screenshot or better discription?

**Comment by LimitCrown** [comment]
Sure. These are three pictures that I took.
https://steamuserimages-a.akamaihd.net/ugc/97233214774669869/9C8A26A412508D6A07E4BA1D1C48CFE479D06FC7/
https://steamuserimages-a.akamaihd.net/ugc/97233214774670198/9893053515D4A747892A365AD7AA963E29D2D511/
https://steamuserimages-a.akamaihd.net/ugc/97233214774670316/88468A9A0F60B7E2883F133A0DCFC7DDEE92AE6F/

**Comment by Zetchzie** [comment]
Whoa 0.o let me see if i get this error brb

**Comment by Zetchzie** [comment]
Yea its happening here aswell idk whats happening

**Comment by supercoolsonic** [comment]
I don't know why I've been avoiding the Adventure Fields so far since the recent updates came out. Same happens to me. SADX Style Water was changed in a few of the updates.

**Comment by PiKeyAr** [comment]
It obviously looks like either SADXStyleWater or the Station Square mod haven't been updated properly. Make sure all mods are up to date. IF nothing helps, try right-clicking and selecting "verify integrity" and/or "force update".

**Comment by PiKeyAr** [comment]
I'm going to increase the version number on the Station Square mod to trigger another auto-update.

**Comment by LimitCrown** [comment]
That appears to have fixed the error!

**Comment by supercoolsonic** [comment]
Yup. It's good now.
