### ISSUE TITLE
Yet Another List of Problems With Screenshots

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#113]
4. Pausing the game during the Chaos 4 fight makes him appear invisible, minus the pink glowing effect on his brain.
![invisible chaos](https://cloud.githubusercontent.com/assets/26051785/25067384/8741c24e-2207-11e7-9b42-5818266d2000.png)

7. So, a thought just occurred to me. Metal Sonic has this "motion blur" effect where several transparent copies of him appear behind him as he does various actions. I was wondering if it was possible to examine the coding for this, and use it to restore the transparency to the extra tails that show up whenever Tails flies or moves fast, and maybe even bring back the blur effect on Sonic's shoes from the original Japanese release. It seems plausible, as the coding to make transparent copies of a character model mid-gameplay exists in the game.

9. I also noticed in Casinopolis that the rotating light effect that also happens on Sonic and Tails persists when they are in the Shower Room. However, going a certain distance into the Shower Room pauses the effect, which makes sense, given the effect does not happen in the Shower Room. However, would it be possible to just disable it no matter how far you go into the Shower Room? Seems quirky. Same thing also happens around the vault. (Not a fix. Improvement.)

10. Also, the lights on the fountain in Casinopolis, the ones that were pretty much transformed into level models, the little circular light texture that they're meant to come from is no longer visible.

13. There's a model problem with the Reala table.
![model problem](https://cloud.githubusercontent.com/assets/26051785/25300179/0ed27c1e-26cf-11e7-8a93-919c06e24a24.png)

**Comment by Zetchzie** [comment]
7 effects are being restored Via the DC Character Models I dont think anyone is interested in doing it for the other models since the morphing effect in sonic's shoes is not in the other models and would require new animations i think.

**Comment by supercoolsonic** [comment]
Well, Tails' effect is already there, just not transparent anymore. The blur on Sonic's shoes would have to be added back in, however. Sonic doesn't grow multiple feet. And I don't think the models would need t morph to accomplish it. I...don't see any reason why they would need to, but what do I know?

**Comment by Sonikko** [comment]
I was wondering about the Tails's tails effect too, it looks bad with him having 6-7 tails while flying. As @supercoolsonic  said, the transparency effect is still in the code and it is used for Metal Sonic, everytime he switches from slow walking to jogging, and before every jump.

**Comment by PiKeyAr** [comment]
The Reala table thing appears to be some kind of a code error. I tried editing the models involved, but I couldn't get any satisfactory results so I left it as-is. Things that were edited out should be fixed/restored now. The remaining problems I have no interest in.

**Comment by supercoolsonic** [comment]
Are you sure about the Reala table? I remember back when I was editing the SADX exe, I got this to appear just fine.
![board model](https://cloud.githubusercontent.com/assets/26051785/25816122/afb65cba-33e8-11e7-97b6-f9e1eef2070d.png)
It was just invisible, is all. I guess if it's giving you trouble, you can port it over, right?

**Comment by PiKeyAr** [comment]
It isn't invisible, the problem with it is incorrect positioning and/or rotation. The model is identical between SA1 and SADX (apart from the UVs). I was able to fix it using a different workaround, though, so it will be available in the next update.
