### ISSUE TITLE
Emerald Coast Wavy Water Effect Causes Distracting Seams And Texture Squeezing?

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#114]
So, it's really cool that the Emerald Coast wave effect was restored. Definitely one of the coolest things about Sonic Adventure, and one of its best moments.

But, uhhh....could it be subject to improvement, even if these things happened in the original? Because they're distracting. Very distracting.
![two oceans](https://cloud.githubusercontent.com/assets/26051785/25068652/77d7b5f6-2230-11e7-97fd-d85cda9c8115.png)
![split oceans](https://cloud.githubusercontent.com/assets/26051785/25068653/7a7e29fc-2230-11e7-9300-03288488ae02.png)
All throughout the sequence, when the models bend, you can see seams, and it's easy to tell where the model split off because of the texture patterns on the models.

In fact, on the island after the whale chase sequence, by walking into the water a little, you can see the ocean model change right in front of you. It's, as I said, _very_ distracting. Could there be a way to remedy this? Or at least minimalize it?

**Comment by Zetchzie** [comment]
Im unable to reproduce this its either a failed update or a GPU error

**Comment by supercoolsonic** [comment]
Which one can't you reproduce?

**Comment by Zetchzie** [comment]
The way the water looks from a distance i cant reproduce

**Comment by supercoolsonic** [comment]
Huh. I got it to happen just now.
![texture effect sonic version](https://cloud.githubusercontent.com/assets/26051785/25068703/d01de9be-2231-11e7-8a8d-928832df154c.png)
You don't see this at all?

**Comment by Zetchzie** [comment]
![capture](https://cloud.githubusercontent.com/assets/15071652/25068716/c25797e0-223a-11e7-9f5a-6d42b58d17c2.PNG)
Not happening here

**Comment by supercoolsonic** [comment]
Aheh, heh.....I just re-downloaded the mod, and now that's not happening anymore, either. Hold on. I'll need to test this about 20 or so more times before I can say it was a partial update failure.

**Comment by Zetchzie** [comment]
I dont think the seams can be fixed without a complete rewrite and redoing of animations plus it's not likely PkR will be interested since it's Accurate to the DC

**Comment by supercoolsonic** [comment]
AH HA!! I'm not crazy! Not crazy! Look!
![hi-poly ocean](https://cloud.githubusercontent.com/assets/26051785/25068823/d12faa56-2234-11e7-8cf5-908ba912488e.png)
This is the ocean stuck on hi-poly mode.

![low-poly ocean](https://cloud.githubusercontent.com/assets/26051785/25068827/e3fa45a6-2234-11e7-8841-4efefb260e26.png)
This is the low-poly ocean. I had to quit the level and enter it again for the hi-poly ocean to go away. There's something wrong with the coding. I'm sure of it.

I'm aware it may be accurate to the DC version, but I'd like to hear him say "there isn't anything I can do for it", or something like that before I give up on this.

**Comment by Rayray-Alcard** [comment]
![46f678be-2235-11e7-9c94-26c9ca4bef39](https://cloud.githubusercontent.com/assets/27602092/25068855/25f9bc6c-223e-11e7-97c2-84091c9a58ca.jpg)
![4888fcf6-2235-11e7-99c2-97fbc947e38a](https://cloud.githubusercontent.com/assets/27602092/25068856/26f2be0c-223e-11e7-9657-1b6d23d81497.jpg)
![49d622aa-2235-11e7-92ed-4e4dba4d891b](https://cloud.githubusercontent.com/assets/27602092/25068857/28393494-223e-11e7-8d85-217fa6960509.jpg)

**Comment by Zetchzie** [comment]
randomly triggered just like other bugs

**Comment by supercoolsonic** [comment]
Appears so.


(Chuckles) I'm sorry. I got ecstatic over this. I just....I got so hyped over this being restored in the game. This was one the coolest things that I always wished could make it back into the DX version somehow, and finally, after all this time, it's here. And it looks great, seams aside. I just want this to be smoother, and more worth the effort put into it. I really didn't want to stumble across texture problems and bugs on my _first day_ with the ocean back to its wavy self, you know?

Ah well. That's Sonic Adventure for ya. Plagued with bugs, charm, and timeless fun. I want to keep this open so that PkR can be aware of these issues.

**Comment by Zetchzie** [comment]
I JUST NOW got it to do that Its squeezing the textures it seems

**Comment by supercoolsonic** [comment]
Alright, so it's not a failed update problem. ...Well, as I said, I have no idea what cause it to happen, or if it's really getting stuck on hi-poly mode or something. Maybe something's just happening to the texture. I'll let the professionals take it from here.

**Comment by PiKeyAr** [comment]
The texture tiling thing could've been caused by the UVs going outside their boundaries if the level was played through multiple times over. I've added a check to reset the UVs when the level is loaded again after exist/restart.
As for the seams, Zetchzie's comment is pretty much on point.

**Comment by PiKeyAr** [comment]
The texture tiling thing could've been caused by the UVs going outside their boundaries if the level was played through multiple times over. I've added a check to reset the UVs when the level is loaded again after exit/restart.
As for the seams, Zetchzie's comment is pretty much on point.

**Comment by supercoolsonic** [comment]
Ah, thanks. Well, this can be closed. Thanks for the insight.
