### ISSUE TITLE
HD_DCStyle Mod does not display the HD version of Gamma's second counter

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#116]
I have all the DC mods updated to the most recent versions,
For some reason the game doesn't use the HD version of Gamma's second counter: http://i.imgur.com/BBtkk25.png

**Comment by PiKeyAr** [comment]
This is likely caused by another mod with E102TIME.PVM (DC_General or DC_Branding) being loaded after it. Make sure the HD GUI mod is the last mod on the list.
