### ISSUE TITLE
Casinopolis see through light

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#121]
![20170418111557_1](https://cloud.githubusercontent.com/assets/15071652/25138608/f861480a-2428-11e7-95f3-c604a6abc7b1.jpg)
when viewed from behind the object is solid but from this view you can see through the object and see the outlining of the model

**Comment by PiKeyAr** [comment]
This has been brought up several times. It isn't fixable without #42 because:
1) The light uses a different blending mode for the whole model
2) Disabling that blending mode will cause issues with this light and other transparent models.

**Comment by Zetchzie** [comment]
alright i felt this had been brought up somewhere but I wasn't sure if it was the same issue

**Comment by PiKeyAr** [comment]
I've reimplemented the blending mode fix in a different manner (there are now two separate animations - one for the base and one for the light part), so this should be fixed now.
