### ISSUE TITLE
Egg Carrier Pool Room Staircase issues

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#122]
The staircase ignores lighting and the textures are misaligned  aswell as Z-fighting
![3c1b71f6-2690-11e7-8331-ff574c30a4c8](https://cloud.githubusercontent.com/assets/15071652/25287754/9b33893a-2690-11e7-819a-8203bf47707e.jpg)

**Comment by Zetchzie** [comment]
Looks like that staircase is jacked up in both SADX and DC

**Comment by PiKeyAr** [comment]
I've checked the staircase, and it doesn't have the "ignore lighting" flag enabled. It might be a landtable specular thing, which I can't do anything about on my end.

In general, I have no interest in fixing design issues with original SA1 assets unless fixing them is trivial, or a fix is available elsewhere, which doesn't seem to be the case here.

As for Z fighting, I'll have a look at it when I update the Egg Carrier mod next time.

**Comment by Zetchzie** [comment]
Looks like the model itself is screwed up if I go on previous issues similar to this that I posted on SADXFE
