### ISSUE TITLE
Update Problem with The Past update

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#123]
Seems the new version of the mod loader doesn't agree with the update just recently put out.
![oops again again](https://cloud.githubusercontent.com/assets/26051785/25290417/9798b72a-2693-11e7-8281-6ebd77a53e0c.png)

**Comment by Zetchzie** [comment]
I had no issues with it

**Comment by supercoolsonic** [comment]
Well, actually, pressing cancel apparently skipped the mod, and when I check for updates again, it doesn't detect an update for The Past. I don't know if it got updated or not, just thought that this should be brought to someone's attention, because a message like this shouldn't be ignored.

**Comment by Zetchzie** [comment]
just force update if it fails

**Comment by supercoolsonic** [comment]
Well, I tried both, but the message just pops up again.

**Comment by PiKeyAr** [comment]
Try deleting everything in the DC_Past folder except mod and verifying integrity. If it doesn't work, it means there is some issue with being able to access the path your DC_Past mod is at. Maybe a read-only attribute or something.
I don't do the coding behind the Mod Loader so there's little else I can suggest.

**Comment by supercoolsonic** [comment]
Okay, that fixed it. I had to keep the manifest file and version file in, though, because it couldn't verify it with those gone. I guess this can be closed now.
