### ISSUE TITLE
Egg Carrier Platform Textures and Station Square Lights

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#125]
Well, you asked to be notified if you missed anything, and so here I am.
The platform that takes you back and forth between the interior and exterior is not using its Dreamcast model on the inside.
![egg carrier spin platform inside](https://cloud.githubusercontent.com/assets/26051785/25559535/27a3b346-2d02-11e7-9b05-e79cbf3299d1.png)
You can tell because the inside rim isn't untextured.

The one on the outside also isn't using its Dreamcast model, but...
![egg carrier spin platform outside](https://cloud.githubusercontent.com/assets/26051785/25559538/3d442c62-2d02-11e7-850f-dd3f254a2a73.png)
The textures are a little goofed around the sides. There's no Eggman logo being shown.

Aside from that platform, the little elevators that hook onto the sides of the Egg Carrier on the outside, their Dreamcast model appears to be largely untextured on the top. Would it be possible to remedy that? It looks completely different (and somewhat better) on SADX.
SADX:
![elevator sadx](https://cloud.githubusercontent.com/assets/26051785/25559575/182e26d4-2d03-11e7-94d8-b453b7832d53.png)

Dreamcast:
![elevator sadx dreamcast model](https://cloud.githubusercontent.com/assets/26051785/25559576/1d326906-2d03-11e7-8bb0-aa6a71a410c2.png)

And now completely unrelated to the Egg Carrier, I noticed that the street lights on Dreamcast are not lit up during the day, but are currently with the mod.
![station square lights](https://cloud.githubusercontent.com/assets/26051785/25559559/81cf0456-2d02-11e7-9292-4b5e25a550a9.png)

**Comment by Zetchzie** [comment]
some collision issue in the egg carrier pool room could you see if it happens on your end? its in the back where the unused transport pad is. sonic walks towards it as if there's invisible bumps

**Comment by supercoolsonic** [comment]
Whoa. Yeah, happens to me, too. I wonder what's wrong.

**Comment by Zetchzie** [comment]
idk im not using your set fixes for the egg carrier so its something with the update

**Comment by supercoolsonic** [comment]
Yeah, it was probably something with the update.

**Comment by supercoolsonic** [comment]
"Barrier"?

**Comment by Zetchzie** [comment]
Yea had a barrier fail on me

**Comment by supercoolsonic** [comment]
What do you mean by "barrier"?

**Comment by Zetchzie** [comment]
when the egg carrier is transformed and your on the lower deck you can spin dash into a wall constantly and eventually break through it but for one instance i didnt have to really do much i just spindashed and broke right through but it didnt happen again

**Comment by supercoolsonic** [comment]
Oh. ...That happens all the time in Sonic Adventure. If you post a screenshot, I can try to fix it with some collision.

**Comment by Zetchzie** [comment]
![capture](https://cloud.githubusercontent.com/assets/15071652/25559863/1e5638d0-2d12-11e7-81a0-dafa01a6808a.PNG)
made it happen again but yea right hear ON BOTH SIDES you can sometimes just spindash right through

**Comment by supercoolsonic** [comment]
Ah. That spot has a collision cube and a pushy wall working together, as well as invisible landtable collision, but there is a spot you could fall through if you manage to beat the pushy wall's strength. I'll see what I can do with it.

If you'd like, you can report things like this, preferably with a screenshot if you can't describe it,  over in the SET Fixes issue thread.

**Comment by Zetchzie** [comment]
I usually dont report this stuff since they cant be broken by normal means but in this case some barriers just fail making them easy to breakthrough which could kill your average player

**Comment by PiKeyAr** [comment]
>The platform that takes you back and forth between the interior and exterior is not using its Dreamcast model on the inside.

Since it doesn't look like it has mirrored textures, I wouldn't consider this an issue.

>The textures are a little goofed around the sides. There's no Eggman logo being shown.

Will be fixed soon.

>Aside from that platform, the little elevators that hook onto the sides of the Egg Carrier on the outside, their Dreamcast model appears to be largely untextured on the top. Would it be possible to remedy that? It looks completely different (and somewhat better) on SADX.

It isn't untextured, it's just using a different (brighter) texture. Since this model had to be restored for the proper UVs to work, I'll probably leave it like this. Maybe I'll look into porting just the UVs at some point.

>And now completely unrelated to the Egg Carrier, I noticed that the street lights on Dreamcast are not lit up during the day, but are currently with the mod.

Technically they aren't "lit up", they're using a different blending mode for the top piece in the PC version (the Dreamcast version always uses the standard blending mode for it, so it looks darker even at night time). Anyway I've added a custom check that forces the standard blending mode, but only during the day.

**Comment by PiKeyAr** [comment]
Actually I'm just gonna go ahead and port the inside EggLift model too, since the outside one had to be fixed anyway.

**Comment by Zetchzie** [comment]
the recent egglift update... the pad is floating

**Comment by PiKeyAr** [comment]
I've just compared it against the original game and it looks pretty much the same I think

**Comment by Zetchzie** [comment]
yea they look the same, the red ring around the outer part though shouldn't be there. I guess the floating is a thing for set fixes

**Comment by PiKeyAr** [comment]
The red ring is a SADX thing, I decided to leave it in and even reconverted the extra texture (which was added specifically for that object in SADX) from the Gamecube version.

**Comment by Zetchzie** [comment]
gamecube also have proper collision for the pads and the staircase in the pool room is fixed in the gamecube

**Comment by PiKeyAr** [comment]
I might be able to fix the staircase, but collision for objects is done in code, and there's no way to get that out of the Gamecube version right now.

**Comment by Zetchzie** [comment]
wow the PC version was absolutely shit on

**Comment by PiKeyAr** [comment]
hmm actually no, the stairs are likely the same mesh in all versions, but the Z fighting isn't visible on the Gamecube for some reason, possibly because of rendering differences.

**Comment by Zetchzie** [comment]
the staircase has bendy textures but GC doesn't have these I wonder why

**Comment by supercoolsonic** [comment]
Ummm...I've managed to extract all of the files out of the SADX Final ISO and even the Preview Proto as well. Would those files be of any help?

**Comment by PiKeyAr** [comment]
I just ran it on Dolphin and I can definitely see Z fighting there.

>I've managed to extract all of the files out of the SADX Final ISO and even the Preview Proto as well. Would those files be of any help?

Not really, most of the game's data other than textures and music is in .REL files, which are binary files specific to the Gamecube.

**Comment by Zetchzie** [comment]
the red line here shouldnt be there that is only in the pool room
also here is the PC starircase 
![20170429210425_1](https://cloud.githubusercontent.com/assets/15071652/25560368/d6305d16-2d1f-11e7-82bd-358337d008fa.jpg)

![20170429210542_1](https://cloud.githubusercontent.com/assets/15071652/25560365/b8d1f248-2d1f-11e7-89aa-fcaf813f855c.jpg)

**Comment by Zetchzie** [comment]
well we have this for REL files
https://forums.sonicretro.org/index.php?showtopic=29821

**Comment by PiKeyAr** [comment]
The red ring thing is apparently SET file-related, and collision seems to be involved as well. Could be that the object IDs are swapped for whatever reason.

**Comment by Zetchzie** [comment]
the red rind only happens with sonic on the Egg carrier

**Comment by PiKeyAr** [comment]
It seems that SADX has two versions of that platform, one is used in the pool room and the other is used outside. SA1 only had one version of the object, so what I'm guessing is that with the SA1 SET file it loads the pool version in both acts, but I'm not sure.

**Comment by Zetchzie** [comment]
could be. that would make allot of sense but why would it only happen with sonic?

**Comment by supercoolsonic** [comment]
Is it because there were SET files added for SADX, and thus the SET files included with the DC mods are only overwriting Sonic's layout?

**Comment by PiKeyAr** [comment]
yes

**Comment by supercoolsonic** [comment]
Yay, I was right about something!

**Comment by Zetchzie** [comment]
oh ok xP

**Comment by PiKeyAr** [comment]
Yes. Anyway what I think I'll do is find that object and make it look like the original, since it has some texturing differences anyway.

**Comment by Zetchzie** [comment]
@supercoolsonic  youll need to apply this to your layouts aswell then once this is fixed

**Comment by supercoolsonic** [comment]
Already have it done. ;D

By the way, that collision issue with the floor in the pool area happens on Dreamcast too. ...So, it's accurate, I guess.

**Comment by PiKeyAr** [comment]
Apparently the SA1 SET file needs some tweaking collision-wise to work properly with SADX, which I will do at some point, but other than that I consider this issue closed.

**Comment by supercoolsonic** [comment]
Making it part of the landtable also works. Cool. Problem solved.
