### ISSUE TITLE
Station Square Hotel's textures messed up

### ISSUE THREAD

**Issue by spookmeman** [PiKeyAr/sadx_dreamcast#126]
After the latest update, the textures in the hotel and water seem to be _very_ glitched. Other levels aren't affected. This has been tested on two computers with different graphics cards.
![sadx evidence](https://cloud.githubusercontent.com/assets/28208590/25560335/2637679c-2d1f-11e7-8656-3137b651e152.png)
![sadx evidence2](https://cloud.githubusercontent.com/assets/28208590/25560339/3533acce-2d1f-11e7-9351-0c01001485e8.png)

**Comment by PiKeyAr** [comment]
You're either using incompatible mods overriding ADVSS04.PVM, or your Station Square mod hasn't been updated properly.

**Comment by Zetchzie** [comment]
someone rolled out the red carpet or its christmas.

**Comment by spookmeman** [comment]
Whoa whoa, wait a second, why didn't it update properly on BOTH computers? Must be my network.

**Comment by Thesch28** [comment]
The textures on my game got messed up too :(.

**Comment by Zetchzie** [comment]
Have you verified integrity of the Station square mod?

**Comment by spookmeman** [comment]
Ok, so is the file updating properly? From my understanding, something must be corrupting those ADVSS04.PVMs during the process or we're not receiving them correctly.

**Comment by Thesch28** [comment]
This is the reason why I hope the updates on moddb don't stop, many people isn't lucky enough to update the mods without problems during the progress (and by the way i got many errors while updating) this updating feature is a cool addition but it's not perfect.

**Comment by Zetchzie** [comment]
ok you need to force update the station square mod and try again
