### ISSUE TITLE
EggCarrier Thruster inaccuracy

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#127]
well this is how it looks in DC though I do not think this was the intended look. Personally id keep the current texture since white looks really out of place

![capture](https://cloud.githubusercontent.com/assets/15071652/25561208/5599b1d8-2d34-11e7-9de6-7b0ec1814f40.PNG)

**Comment by Zetchzie** [comment]
do we have any vids running on real DC hardware to confirm this is the intended look?

**Comment by supercoolsonic** [comment]
....Uhhh....this is one of the first things I reported here. That part of the model is untextured on Dreamcast, so PkR decided to port the models over from SADX, because "why not?"

**Comment by Zetchzie** [comment]
oh then glad he decided to keep the textured model lol
