### ISSUE TITLE
Chaos 4 Texture Error

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#130]
![chaos 4 is made of code](https://cloud.githubusercontent.com/assets/26051785/25722136/a0e5c3d2-30d8-11e7-8cf0-3c8d1695a7e6.png)
One of his textures isn't correct. I've verified integrity and re-downloaded mod, and it still happens.

**Comment by PiKeyAr** [comment]
Should be fine now. There was a GBIX issue with SA1's CHAOS4_COMMON.PVM.

**Comment by supercoolsonic** [comment]
It's fixed now. Thanks.
