### ISSUE TITLE
Final Egg Layering Problems

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#131]
Going through Act 2, I found a few things that could probably be fixed.

1) The background appears.....odd, if you move far enough away from it.
![final egg 2 background draw distance thing](https://cloud.githubusercontent.com/assets/26051785/25754822/46c6e030-3186-11e7-8be6-c8e66821e70c.png)
It moves into the passage where you start the Act.

2) Might be order-independent transparency, but this one part of that light object isn't layered properly here.
![small light layering problem](https://cloud.githubusercontent.com/assets/26051785/25754875/7064f88c-3186-11e7-9036-2e04a29888eb.png)

3) Self-explanatory.
![another layering issue](https://cloud.githubusercontent.com/assets/26051785/25754890/7e565cce-3186-11e7-9042-a8812e4626bf.png)

4) Also self-explanatory.
![and another layering issue](https://cloud.githubusercontent.com/assets/26051785/25754905/87ff3f20-3186-11e7-8602-acf2a77edebe.png)

**Comment by Zetchzie** [comment]
Another Order dependent transparency I gather

**Comment by supercoolsonic** [comment]
...Maybe. The weird thing is, those light ones behind the wall only happen at certain angles. I think there's something else happening here, but I could be wrong.

**Comment by PiKeyAr** [comment]
(2) has already been reported before and isn't fixable, (1) is a draw distance artifact that can be fixed. I've sorted the models involved in (3) and (4), but it probably won't help in (4).

**Comment by PiKeyAr** [comment]
Most of the issues should be sorted out in today's update. There is a minor alpha punchthrough problem with the ring texture around the blue glass, but I gotta stop here before I go insane.
