### ISSUE TITLE
Spotted some Minor Inaccuracies.

### ISSUE THREAD

**Issue by Rayray-Alcard** [PiKeyAr/sadx_dreamcast#132]
1. Footprints and shadow underneath the character model are fully visible under beach water in both acts of Emerald Coast:
![untitled](https://cloud.githubusercontent.com/assets/27602092/25769699/96f293d4-31ee-11e7-9bed-39e2cec7b350.png)
![untitled2](https://cloud.githubusercontent.com/assets/27602092/25769700/98377a84-31ee-11e7-8f4c-772c2f58f775.png)

2. Ring shadows at the beginning of Emerald Coast Act 1:
![untitled1](https://cloud.githubusercontent.com/assets/27602092/25769720/0a3e00f8-31ef-11e7-9386-72859dfb6223.png)

3. Station Square‘s twinkle park window transparency
and green texture brightness differences:
![untitled3](https://cloud.githubusercontent.com/assets/27602092/25769959/c596bae2-31f5-11e7-90e1-7eb0d650200a.png)
![untitled4](https://cloud.githubusercontent.com/assets/27602092/25769960/c7b36564-31f5-11e7-9f8f-028faf83de6a.png)

**Comment by PiKeyAr** [comment]
Unfortunately none if the above except 4 (which is a material difference) are fixable due limitations of SADX engine's transparency sorting.

**Comment by Rayray-Alcard** [comment]
Transparency issues aren't present with the old Emerald Coast water.

1.
![untitled](https://cloud.githubusercontent.com/assets/27602092/25776529/b7d601d0-328e-11e7-9198-8a7ac1b8a7dd.png)
![untitled2](https://cloud.githubusercontent.com/assets/27602092/25776530/b99fb754-328e-11e7-8f21-df73102f6a8a.png)

2.
![untitled1](https://cloud.githubusercontent.com/assets/27602092/25776532/c8755cf2-328e-11e7-8e13-0dc1e66bd128.png)

So the high poly water has transparency issues with 1 and 2?

**Comment by PiKeyAr** [comment]
The "old" water is just a square with textures on it, while the water used currently is an actual model, so all transparency nuances apply to it. SADX uses a special function to draw its default water, which hasn't been completely reverse engineered yet, and it certainly wouldn't work with the wave effect.

**Comment by Rayray-Alcard** [comment]
Ok. I never mentioned in Act 1 before and after wave effect,
the water ripples are above the water.
![untitled1](https://user-images.githubusercontent.com/27602092/27512766-9bcc0ca2-591a-11e7-8e63-7a5efaeb7726.png)
![untitled2](https://user-images.githubusercontent.com/27602092/27512767-9e059e20-591a-11e7-9b16-5438a6fd40a3.png)
It's the white circles texture above the blue water.

**Comment by PiKeyAr** [comment]
3 is a self-blending issue, other than that everything reported here should be fixed.
