### ISSUE TITLE
Egg Carrier Interior Texture error

### ISSUE THREAD

**Issue by LimitCrown** [PiKeyAr/sadx_dreamcast#133]
The main room in the inside of the Egg Carrier isn't using the correct textures. The other rooms in the Egg Carrier appear to still be correct.

**Comment by PiKeyAr** [comment]
This might have been a failed update due to a bug in the Mod Loader's update system. Please refer to this: https://twitter.com/pkr_sadx/status/860947695069876224

**Comment by LimitCrown** [comment]
That resolved the issue. Thanks!
