### ISSUE TITLE
Random Issues

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#134]
One area in Red mountain is still showing unleveled ground (the Secret area)
![20170507150936_1](https://cloud.githubusercontent.com/assets/15071652/25785423/d75a22c4-334d-11e7-94a6-16765c8a2920.jpg)

If you skip tails cutscene "In Tails story" after being rescud your camera will get stuck behind the bulding
![20170507155137_1](https://cloud.githubusercontent.com/assets/15071652/25785432/0bbccf80-334e-11e7-8c65-7208427b1069.jpg)

this area should be dark as the rest of the ground around it but it ignores the lighting
![20170507162849_1](https://cloud.githubusercontent.com/assets/15071652/25785439/3a0d3e24-334e-11e7-8f36-63957f45e88e.jpg)

Should that area really look like that?
![20170507165752_1](https://cloud.githubusercontent.com/assets/15071652/25785442/5e5619b8-334e-11e7-94a3-2ebefad396c3.jpg)

Bigs Fishing line will dissapear when in widescreen
![20170507173429_1](https://cloud.githubusercontent.com/assets/15071652/25785443/73a34278-334e-11e7-8800-ee7ba3fef9c4.jpg)

Is it supposed to look like that?
![e48d1078-3370-11e7-9df5-d9482ee1ddb9](https://cloud.githubusercontent.com/assets/15071652/25788279/d598984e-3375-11e7-9c9b-04b21e09257b.jpg)

Fencing is fighting with the stairs
![20170507201640_1](https://cloud.githubusercontent.com/assets/15071652/25787144/dd72d2cc-336c-11e7-8854-6376430c908b.jpg)

Is this supposed to happen a visible seam here but only at a certain angle
![20170507224348_1](https://cloud.githubusercontent.com/assets/15071652/25788449/20b66bb6-3377-11e7-9248-c8ba4164bc4e.jpg)

**Comment by Zetchzie** [comment]
Is it supposed to look like that?
![20170507195837_1](https://cloud.githubusercontent.com/assets/15071652/25787129/b930afce-336c-11e7-89ed-4c0ed40c8509.jpg)

The Chamilion doesnt spawn 
![20170507200244_1](https://cloud.githubusercontent.com/assets/15071652/25787135/c538da8a-336c-11e7-8bc2-3d4d70b7a947.jpg)

Fencing is fighting with the stairs
![20170507201640_1](https://cloud.githubusercontent.com/assets/15071652/25787144/dd72d2cc-336c-11e7-8854-6376430c908b.jpg)

**Comment by supercoolsonic** [comment]
I'm sure the Leon spawns in Hot Shelter. I remember fixing it in the SET Fixes layouts, and I recall PkR maybe doing something about it, too. Besides that, I had it spawn for me during me recent run through the game with the SET Fixes layouts. Leon is a very finicky enemy, and even if you stand around for a few minutes, sometimes he just doesn't show up. But he _is_ there. He might've just fallen off the ledge. If there's ever a time the Sonic community looks into SADX/SA1 to try and fix it up as much as possible, Leon is probably going to be a hot topic. ....Or it could be just variables making him not appear sometimes. I don't know. You can use debug mode to see if he's even up on the platform, or if he fell off.

What's wrong in the first picture with the water draining in Hot Shelter? I can't tell.
And is something wrong with the Past Burning Shrine area? It's dark, yes, but.....that's how it is normally, I think.

**Comment by Zetchzie** [comment]
In hot shelter is looks like the draining water is not blending properly with the water as its filling up. the Shrine looks like it shouldn't be that bright in the back since no fire or light source is over there. if this is the intended look then I guess theres nothing to worry about

**Comment by supercoolsonic** [comment]
OH, the wall on the left. Completely overlooked that. ....Huh. Looks more like a DC lighting mod issue. The water might be another OIT (Order-Independent-Transparency) issue, but I'm not too sure. Does it look that way on Dreamcast?

**Comment by Zetchzie** [comment]
yea im about to do a double check on the water brb

**Comment by Zetchzie** [comment]
if you look closely you can see a line and that doesnt happen in DC 
![20170507215817_1](https://cloud.githubusercontent.com/assets/15071652/25787552/6c98a762-3370-11e7-9f4e-2a8da5a9a991.jpg)

**Comment by supercoolsonic** [comment]
![comparison](https://cloud.githubusercontent.com/assets/26051785/25787955/54564952-336b-11e7-9310-93c8581275dc.png)
I...don't see much of a difference.

**Comment by Zetchzie** [comment]
hold on lol

**Comment by Zetchzie** [comment]
look CLOSLY you can see seams
![e48d1078-3370-11e7-9df5-d9482ee1ddb9](https://cloud.githubusercontent.com/assets/15071652/25788137/e76c3702-3374-11e7-92f9-3181157f0c78.jpg)

**Comment by supercoolsonic** [comment]
Oh! Oh, I see it! It's very faint, but I can see a slight texture problem there. In SADX, it appears to be cut off there a little. It's like there's two waterfall textures overlapping each other! ....Is...this a transparency thing? Or is it something that's currently fixable? I dunno.

**Comment by Zetchzie** [comment]
idk but if you play it in sadx you'll see it and it looks weird since the bottom part is out of sync with the top

**Comment by PiKeyAr** [comment]
Most of these are design issues with the original assets, which I have no interest in fixing as mentioned in the FAQ/troubleshooting guide. I will take a look at the Hot Shelter water thing if I ever come across that object, but that is rather low priority and it may not be fixable if sprites are involved.

**Comment by Zetchzie** [comment]
what ones should be reported to SADXFE?
