### ISSUE TITLE
Menu background Disparity 

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#135]
The top right and bottom left are very artifacty did somthing happen in in the HD GUI update or DC Branding?
![20170507195132_1](https://cloud.githubusercontent.com/assets/15071652/25786194/c1a9cad6-335e-11e7-9889-acb442660462.jpg)

**Comment by PiKeyAr** [comment]
Uhh what is this? Neither HD GUI nor DC Branding have this kind of background. You seem to be using some other mod that overrides AVA_BACK.PVM

**Comment by Zetchzie** [comment]
oh i think I know lol I thought I deleted  it a long time ago
