### ISSUE TITLE
Cowgirl Placement

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#137]
Looking at a video of the original Japanese release, it seems the position of the cowgirl is different than the position of the giant billboard castle thing in future releases. Using the cowgirl mod, I noticed a large part of the model was clipping through the wall behind it. In the video of the Japanese version, I couldn't see any part of the model clipping through, and it seemed to be placed further from the wall. It also appears the metal neon lights and the barrel to the left of it were positioned differently as well. I would recommend looking at the SET files from the original Japanese release and implementing them into the cowgirl mod to keep it as authentic and nice-looking as possible.

Naturally, I am preparing a SET Fixes version of the Casinopolis Knuckles layout to get her, the lights, and barrel closer to their Japanese positioning, but so far it's been done by eye, since I don't have immediate access to the Japanese files. And, of course, when I get the SET Fixes + Extras version going, I'll release one with the extras, too.

Japanese:
![japanese dreamcast position](https://cloud.githubusercontent.com/assets/26051785/25875841/41b2dff2-34df-11e7-983a-7a270bdeb87f.png)

SADX:
![sadx positioning](https://cloud.githubusercontent.com/assets/26051785/25875844/46a6512e-34df-11e7-8b2d-b6d68be379a2.png)

**Comment by Zetchzie** [comment]
is it just me or is the lights and the wall textures different in the top photo

**Comment by supercoolsonic** [comment]
It's the rotating light effect going around the room. It's the same.

**Comment by Zetchzie** [comment]
I forgot all about that lol

**Comment by PiKeyAr** [comment]
I've just hardcoded the cowgirl to the same position/rotation as in the Japanese SET file and altered NeonK's collision structure to make it work a little better, but that's about all I'm willing to do for it.

**Comment by supercoolsonic** [comment]
Hmmm. Well, that's one way to do it. I got more of it out, with far less of it in the wall. Can't do that now because of the hardcoding, but I suppose that's good enough. The mountain that the steam cloud doesn't jump out of no longer clips into the wall. I'm happy with it. Thanks. And I guess never mind about the SET Fixed files. No need to make them anymore.
