### ISSUE TITLE
Final Egg OBJ File Update Problem

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#138]
Just a small problem with updating the mod. It says "size of file system\OBJ_FINALEGG.pvm (0.0 bytes) differs from manifest (1.44mb)"

So....yeah. Final Egg can't update. Tried forcing the update multiple times and verifying integrity.

**Comment by PiKeyAr** [comment]
https://twitter.com/pkr_sadx/status/862781607744163840
