### ISSUE TITLE
Light Speed Dash glow blending

### ISSUE THREAD

**Issue by RinMaru** [PiKeyAr/sadx_dreamcast#140]
Sonics Lightspeed Charge fades from Blue to a Purplish color in DC but not in SADX

**Comment by Thesch28** [comment]
The lightspeed charge effects Is something related to the character models and as far as I know PKr is not going to do that kind of stuff since there is already a DC character models mod in the works by other modders and hackers.

**Comment by Zetchzie** [comment]
where did you here this? this is about coloring not the models

**Comment by Zetchzie** [comment]
heh so it it is i figured it was a pallet issue

**Comment by Thesch28** [comment]
Well I already knew about this someone pointed that out a long time ago in the forums of sonicretro.

**Comment by Zetchzie** [comment]
Never knew this of only been keeping track of SADX mods and DC mods for SADX threads. I may have over looked it

**Comment by PiKeyAr** [comment]
Reopening for posterity. As of right now the Light Speed Dash glow itself is almost identical to the original colors-wise, but there's a blending issue that causes the glow on Sonic's model to be less vibrant. It has do do with the way the colors blend with different models. At the moment I don't know how to fix it, but a solution may show up someday.

Reopening to save for posterity.

**Comment by PiKeyAr** [comment]
So after all these years I realized that like with other effects that are brighter on the Dreamcast, it probably just draws stuff twice or more. I don't really understand Ghidra's decompiled output of the SA1 function so I'm going to simulate its look manually.

**Comment by PaintDude** [comment]
For some people it looks like the original Dreamcast version but for me it’s looks like the DX version. I think I’m losing my mind.

**Comment by PiKeyAr** [comment]
There are mods that override DC Conversion's Light Speed Dash replacement.

**Comment by PaintDude** [comment]
Alright I’ll try to remove some mods

**Comment by PaintDude** [comment]
Ok, so I ended up removing some mods and it was the super sonic mod that was causing it.

**Comment by PiKeyAr** [comment]
No, I tested the Super Sonic mod yesterday and it was working fine.

**Comment by PaintDude** [comment]
Huh interesting

**Comment by Skittleology** [comment]
There are 2 Super Sonic mods, the one included with PKR's Mod Installer is the original one made by Morph/SonicFreak94. It seems that the one made by kell is causing this issue.

**Comment by Skittleology** [comment]
I've tested it too and it seems that Kell's Super Sonic mod is the one that is causing the problem.

**Comment by PiKeyAr** [comment]
It appears that having the Super Sonic mod above DC Conversion will override the Light Speed Dash aura replacement.

**Comment by PiKeyAr** [comment]
I changed the script in the Mod Installer to enable the Super Sonic mod after DC Conversion, so this issue should no longer happen when the Mod Installer is used.

**Comment by PiKeyAr** [comment]
I think the aura looks close enough now.
