### ISSUE TITLE
Checkpoint Stars ☆ Borke [ HD GUI 2 ]

### ISSUE THREAD

**Issue by Rayray-Alcard** [PiKeyAr/sadx_dreamcast#142]
Shape of the ☆ with and w/o CHRMODELS.DLL replacement
![☆](https://user-images.githubusercontent.com/27602092/26836150-1420fba8-4aa8-11e7-8215-05d5cbb95309.png)

**Comment by RinMaru** [comment]
thats why he said **

> Experimental Warning

** lol

**Comment by Rayray-Alcard** [comment]
Ok? How was I supposed to know if he was referring to the CHRMODELS.DLL or the mod itself?

**Comment by RinMaru** [comment]
Idk. If he was I didn't catch on either xP. Dont worry Im sure he will fix it. He's possibly asleep by now though so gotta wait.

**Comment by PiKeyAr** [comment]
Should be fixed in 0.804. Feel free to reopen if you run into other issues.
