### ISSUE TITLE
Title screen ripples hardware survey

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#147]
Please report the performance of the ripples mod here to help me decide whether I should keep it.

You can enable title screen ripples with DC_Branding 0.9900 or higher by installing this mod: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/TitlescreenRipples.zip

Unfortunately I could only implement it in a very clumsy way so it may not work on all GPUs and it may also lag at high resolutions and/or on lower end systems. Depending on how many people are able to run it I'll decide if I should keep it enabled or not.

**Comment by spookmeman** [comment]
It works as intended at a nice 60fps on my computer. My OS is Windows 10 (Insider Previews), my CPU is an i3-4130 and my GPU is an NVIDIA Geforce GTX 750 TI. I'm also running the at a 1080p resolution.

**Comment by AModderIGuess** [comment]
Intel Core i5 (inside a sort of crappy school laptop) running in full screen, 1080p resolution, I guess, 1280 x 720 game size and man, does it look beautiful. I hope you don't mind me uploading a link to a screen shot of the title screen.

**Comment by cheatfreak47** [comment]
Intel Core i3 3120M CPU running under Intel HD Graphics 4000 and it works more or less fine for me.
Lantern Engine is actually more taxing than this title screen tweak, this should definitely be migrated into DC_Branding and have an optional disable mod like you do with the title screen in general.

**Comment by Sonikko** [comment]
It's working perfectly on my PC.
GTX 1060 6GB
i5 6600
8GB DDr4@2133

GPU usage is around 40% at the main menu, running the game at 1080p SSAAx4 so it's actually rendering at 4K and downscaling.

**Comment by Shaddytheguy** [comment]
Seems to work alright, though I don't like the way the black around the edges looks.

Actually my PC did overheat after playing for 15 minutes, but that's probably because it sucks, not because of the game.

**Comment by Darkspines147** [comment]
Works well for me!
AMD R7 200 series 6GB DDr3
Dual-core CPU @2.2Ghz
8GB DDr2 @5400

**Comment by LimitCrown** [comment]
The mod appear to work fine for me.
NVIDIA GeForce GT 650M
Intel Core i7-3740QM @ 2.70GHz
16 GB RAM

**Comment by supercoolsonic** [comment]
Works perfectly fine, 60fps, aside from the black stuff on the left and right sides of the screen.

CyberPowerPC
Intel Core i7-4810MQ CPU @2.80Ghz
16 GB RAM

**Comment by PiKeyAr** [comment]
I was able to optimize the animation so it should be working well even on low-end systems now. I've also broken up the background into square tiles, which should make it compatible with any GPU. There are some positioning issues I need to figure out before releasing it though.

**Comment by Rayray-Alcard** [comment]
NVIDIA GeForce GTX 980
Intel Core i7-4790K @ 4.0GHz
16 GB RAM
Windowsh 10

Nice!

**Comment by Darkspines147** [comment]
@supercoolsonic It did that in the original game too if you used a wide screen. I have my Dreamcast hooked up to my Monitor via VGA, and the ripple does that.

**Comment by spookmeman** [comment]
@AModderIGuess That's 720p... 1080p is 1920x1080.

**Comment by PiKeyAr** [comment]
I've just pushed an update for DC Branding and the ripples mod, should make it perform a lot faster and potentially improve GPU compatibility.

**Comment by supercoolsonic** [comment]
@Darkspines147 Ah. Well, I don't mind it that much. This is such a big improvement over a simple static title screen image.

**Comment by PiKeyAr** [comment]
Since I've sorted out the compatibility issues and performance seems good I'm closing this. If you're having issues with the new title screen feel free to post here again.
