### ISSUE TITLE
Mystic Ruins Glitched Textures?

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#149]
So I found some glitched Textures on the Mystic Ruins, i used a ''?'' because sometimes people get glitched textures after update that was not downloaded properly.
so here's what i saw: http://i.imgur.com/aF80Pnc.png
can anyone confirm i'm not the only one seeing this?

**Comment by RinMaru** [comment]
yea thats happening for me aswell
