### ISSUE TITLE
Two missing models and a compatibility request

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#156]
Hi! So, it seems like you're wrapping things up with the Dreamcast Conversion mods, huh? I said I'd wait until you finished everything else, so I guess now's the time. I was wondering if you could port two more models over from the Dreamcast.
Lost World: The Aoki Switch. Object number 78.
Casinopolis: A diggable platform, O KDANM. Object number 174. Their textures are messed up because the model isn't mirroring the texture on it. You know. And those are the only two objects left that would need their models changed. Pretty please?

Also, it'd be cool to have compatibility with the Beta Windy Valley. Currently, loading the beta after the DC Windy Valley mod still allows the level to function, and you can play the beta level, but Act 1's sky box will be pitch-black, likely due to the transparent sky box code in your mod. Also, the "darkening" effect will activate at some point in the level, which it's not meant to do in the beta. Otherwise, Act 2 and Act 3 play just fine. So, yeah. OH! Also, ItsEasyActually spoke with me earlier today to bring up the idea of disassembling the Autodemo and making an improved Beta Windy Valley mod with the actual SET objects ported over and stuff. So, you may want to talk to him too, if possible, before improving compatibility if you decide to go for it.

You can get the mod and source code here to work with, just to make it easier on yourself.
https://github.com/supercoolsonic/SADXDC-SET-Layout-Fixes/issues/7
It's near the bottom of the page.

**Comment by PiKeyAr** [comment]
I've replaced the models for those unused objects with their SA1 counterparts, though I can't test them because I don't have a layout that includes them.

As for the Windy Valley mod, I'm not sure what you want me to do. I could make the code part of the mod auto-disable itself if a certain change is detected (e.g. a certain DLL is loaded, or the start position is altered), but that would be the same as disabling the Windy Valley mod, so why not just do that instead? In general, running several mods that change the same level at the same time isn't a good idea.

**Comment by supercoolsonic** [comment]
Thanks for the models. They look fine now.
I only thought Windy Valley was possible because loading both still allows the level to work. The problems are only aesthetic. If you're not interested, then I guess this can be closed. It'd be cool to be able to play the beta WV with the updated lighting, draw distance, and Dreamcast object models. That's all.

**Comment by PiKeyAr** [comment]
You can add draw distance and fog tweaks to the mod, it's a very simple edit of an array. As for the objects, unless the Beta Windy Valley mod is designed as an addon to the DC_WindyValley mod (which probably wouldn't be a good idea), I think it's better to redo all objects/lighting either way.
Overall, there are too many nuances with making this stuff compatible and I just don't see much point in it.
