### ISSUE TITLE
Chaos Emerald Glow with Magnet Shield

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#160]
So, uhh....I was testing something out today, and I noticed this happen to the glow a few times.
![ummm](https://user-images.githubusercontent.com/26051785/33110367-fa66e2c4-cf0c-11e7-9175-104299b1ebbc.PNG)
It seems to happen if you collect a ring with the shield with the emerald just off screen like that. I'm not sure if it's something with the coding that restores the glow or if it's something with the Lantern Engine mod. Regardless, it's minor, but I thought it was worth reporting.

**Comment by PiKeyAr** [comment]
Looks like it switches to an incorrect blending mode under some circumstances. Try with DC_General 0.8046 that I just uploaded.

**Comment by supercoolsonic** [comment]
It seems to be working fine now. Thank you very much!
