### ISSUE TITLE
Crash in Emerald Coast

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#163]
![wonkyspring](https://user-images.githubusercontent.com/26051785/34014414-a6a556ee-e0e0-11e7-9c65-27fe9246ebc4.PNG)

So uh....in every level now, this happens to the spring texture. Dunno what broke, and I'm pretty sure nothing I'm loading after the DC mods changes the texture or spring models in any way.
Edit: Something in DC General causes it, it seems.

Edit2: Also unrelated to this, but about the new restored water ripple effect. When 2P Tails goes into shallow water, the effect looks very strange It's like he's constantly emitting water ripples.

Edit3: Okay, so I figured out that if I load the Updated HUD mod after DC General, the springs and stuff look fine. Still should look at the texture weirdness, but more importantly, I had a crash happen in Emerald Coast. It was near the start of the level, where that one lone swinging spike ball is. I was Sonic, and I had just stepped into the water. And the game crashed. I quickly saw, though, that I didn't leave a footprint in the sand under the water. Since that was a recent thing that was changed, I figured it might have something to do with that.
Edit4: However, in loading that mod after the DC General, that makes the pause box turn white. *Sigh*

**Comment by PiKeyAr** [comment]
The ripple and the star texture should work fine now, as for the crash and the white pause box that sounds like something is preventing the OBJ_REGULAR texlist from resizing properly or overwriting OBJ_REGULAR.PVM with a PVM that has less than 100 textures.

**Comment by supercoolsonic** [comment]
Okay, everything seems to work fine now. Thanks so much!

**Comment by PiKeyAr** [comment]
No problem. I think there's one more texture (ya.pvr) in OBJ_REGULAR that could be problematic, but I haven't run into objects that use it just yet. Maybe it's unused.

**Comment by KayaneRF** [comment]
𝘚𝘵𝘢𝘳 𝘵𝘦𝘹𝘵𝘶𝘢𝘭𝘪𝘻𝘢𝘵𝘪𝘰𝘯 𝘣𝘦𝘯𝘥𝘦𝘥 𝘪𝘯 𝘊𝘰𝘮𝘮𝘰𝘯 𝘚𝘸𝘪𝘵𝘤𝘩
![4796643](https://user-images.githubusercontent.com/34458147/34278816-2f6ac49c-e67b-11e7-85b8-977ddacdb877.png)

[𝘚𝘦𝘢𝘴𝘩𝘰𝘳𝘦 𝘈𝘯𝘨𝘭𝘦 𝘉𝘶𝘨 𝘈𝘤𝘵 2 𝘦𝘯𝘥](https://www.dropbox.com/s/tay5wvol7zau6nv/%E2%80%8C.mp4)

𝘔𝘦𝘳𝘤𝘪 ♥️
–𝘒𝘢𝘺𝘢𝘯𝘦
