### ISSUE TITLE
Failed to update mod Dreamcast Casinopolis

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#164]
So I tried to download the new update for the DC Casinopolis and i got this message i deleted all the files inside and tried to force the update and i still get it.
![image](https://user-images.githubusercontent.com/25397223/34323267-ab3c3d12-e806-11e7-8ef6-ae0092f3fe7e.png)
I don't know if i'm the only one with this problem.

**Comment by RinMaru** [comment]
Downloaded fine for me

**Comment by PiKeyAr** [comment]
Should be working now.

**Comment by Thesch28** [comment]
It's Working Now Thanks!
