### ISSUE TITLE
Objects and Title Screen fade-in

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#170]
Alright. So I forgot a few objects. ....Ummm....I was wondering if you could fix them? Pretty, pretty please?

![greendifuse](https://user-images.githubusercontent.com/26051785/35841142-1e41d2aa-0ac0-11e8-80b5-984159158af7.PNG)
O ARACADE2 in Speed Highway has a green diffuse going along there. ...Think you could remove it?

![splitegg](https://user-images.githubusercontent.com/26051785/35841174-4add8796-0ac0-11e8-86cb-30566042263e.PNG)
O DARUIMA in Hot Shelter has a texture that is split in half. The eggman logo.

This one is something a bit more.
![windyblock](https://user-images.githubusercontent.com/26051785/35841202-6abcf5d8-0ac0-11e8-8408-ea966288d8e5.PNG)
There's an object for the Chao Race Course called Small Screen, however, when I try to place one, nothing appears. This is what it was like before you added in the Chao Garden mod. None of the objects would load. I was wondering if the same case applied to this one, and if it was possible to allow it to be placed.

Finally, something that has nothing to do with objects. You know how you put in that fade effect for the "Sonic Adventure" text on the title screen when you press start? Looking at the Dreamcast version running on an emulator, and in various Youtube videos, it seems there was meant to be a _fade-in_ effect for the text as well when the title screen first loads up. Is there a way to implement something like that?

**Comment by PiKeyAr** [comment]
Although I made a few exceptions in the past, I'm not interested in restoring models that go unused in the final version of the game.
Re: title screen transitions, maybe someday, not anytime soon though because I don't know how those transitions work.

**Comment by supercoolsonic** [comment]
Alright then. I understand. I guess I'll close this, then.
