### ISSUE TITLE
[Suggestions] DLCs Settings

### ISSUE THREAD

**Issue by cheatfreak47** [PiKeyAr/sadx_dreamcast#172]
I would like a setting added to the Dreamcast DLCs mod that makes the DLC only show up if some conditions are met to prevent the DLC from showing up when it is impossible to complete.

My suggestion is that a new setting be added called "Post Game Mode" which, when enabled- causes the DLC to not load or show up unless the current character's story mode has been completed (As in, the story is at 100% on character select).

In addition, a check should be done to make sure the user isn't in Mission Mode. The DLC should not be loaded when the user picks mission mode because it's possible for the new objects for the DLC to interfere with the missions users are trying to find/pick up.

The goal of this setting is to make it so users don't need to flip the mod on and off to experience the DLC in a convenient way. Seasonal mode is a great step towards this since it allows you to experience the DLC at fixed points in the year, but this would make it so you could leave the mod in seasonal mode without potentially interfering with the typical story playthrough.

**Comment by PiKeyAr** [comment]
I need examples of how the DLCs interfere with the story mode or mission mode. Previously I had a suggestion about making the DLC content work in Mission Mode, and in this release I also added a few exceptions to prevent known problems with the DLCs interfering the story.


The setting to turn off DLC content if the story isn't 100% complete for current character is a possibility, but I'm not sure I would want it on by default, and even then flipping that setting takes more clicks than disabling the mod itself, so the convenience argument doesn't really work here.

**Comment by PiKeyAr** [comment]
I've added a toggle to disable DLC content for current character if his/her story isn't complete.
At the moment I'm not interested in disabling the DLCs in Mission Mode.

**Comment by cheatfreak47** [comment]
Hmm, well the DLC content makes the most sense only showing up in adventure mode because of how mission mode sometimes dumps structures and other things on the map- so if you ever had a conflict of that it'd be a problem. I suppose I could do a playthrough of Mission mode here in a bit and also report on the issues caused by DC Conversion if you'd like- but it'd be hard to check for every possible conflict of mission objects and DLC objects since the DLC can only be loaded one at a time.

Unless you want to build a version of the mod for testing where every mission object is spawned in the adventure fields at once. 🤔

**Comment by cheatfreak47** [comment]
Doing a proper mission mode playthrough in DC Conversion to document any issues the DC level design has is something I've been meaning to do anyway, so this would be a good excuse, I could try and kill two birds with one stone here.

**Comment by Clownacy** [comment]
Just FYI, I did that a while ago, and reported all my issues in the Retro thread. Stuff like the Burger Shop man falling through the Mystic Ruins pool thing, and Knuckles not being able to dig under the signs, also in Mystic Ruins. They were all fixed, I believe.
