### ISSUE TITLE
Red Mountain Clouds are Gone

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#186]
I'm not sure exactly when this started (Although it was probably fairly recently), but in Knuckles' Red Mountain, only while the Dreamcast Conversion mod is active, and 'Dreamcast Red Mountain' is configured to load, the clouds do not appear. I haven't the faintest idea as to what causes it. It's not an .exe problem, as I've tried it on multiple .exes.
![cloudsnothere](https://user-images.githubusercontent.com/26051785/39478147-2c1631f6-4d27-11e8-94b9-eaf9d829d241.PNG)

**Comment by PiKeyAr** [comment]
Are you trying to load the Dreamcast Conversion mod together with the old "Dreamcast Red Mountain" mod?

**Comment by supercoolsonic** [comment]
No. I got rid of those individual mods a while ago, when everything got merged into one mod.

**Comment by supercoolsonic** [comment]
They're fixed. Thanks a lot!

**Comment by supercoolsonic** [comment]
I don't exactly feel comfortable in making a completely separate issue for this, and I know this has absolutely nothing to do with Red Mountain's clouds, but could I request that you remove the Lost World aokiswitch thing? For the unused switch? It turns out that it's not functioning right, although the texture UV problem was fixed. I'd like to try and fix this on my own, as I'm noticing some other errors with the object that can't be resolved unless the object is back in its raw SADX state.
