### ISSUE TITLE
New build test

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#194]
I'm looking for people to help me refine the new update for DC Conversion. Specifically these two things:

1) Make sure usage of untouched SA1 PVMs didn't break anything.
This test build aims to use as many untouched PVM files from SA1 as possible. Switching to untouched SA1 PVMs brings a few benefits, namely better texture accuracy (I decided to get rid of custom textures altogether), smaller memory/space footprint (SA1 PVMs are smaller), faster loading and future compatibility with original SA1 PRS files (that will reduce the footprint even further), which may be possible to load with the Mod Loader in the future. In addition, this build introduces a lot of minor accuracy updates, some of which you may have seen on my Twitter.

2) Make a list of post-cutscene camera transitions that shouldn't happen, so that I can disable them.
I've restored the smooth camera transitions that take place after cutscenes finish, however there are cases when such transitions shouldn't happen and it would be better to have the camera cut directly to the character. There are at least two in Big's story that need fixing. To disable transitions for those specific cutscenes, I need to know their IDs, so the point of this test is to make a list of cutscene IDs that need their transitions disabled.

If you'd like to test this build, please [download it from here](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/PVMTest.7z) and report any problems in this issue. The build will be reverted to the latest public version if you update it through the Mod Loader, so don't update it until you're done testing.

**Please use the following settings**
- Run the game in a window/windowed fullscreen
- SADX Style Water: Disabled everywhere
- Fix cutscene camera transitions: Enabled
- Sonic Team Logo Mode: Animated
- Please disable the HD GUI 2 mod

**Places/aspects of the game that need testing**
- All character stories except Sonic
- Chao

**Things to look out for in particular**
- Texture errors, objects/levels using wrong textures, especially after reloading the stage several times or progressing from one act to another
- Level objects and other things disappearing, especially after reloading the stage
- Crashes
- Cutscene transition issues (see below)

**Things not to bother with**
- Stuff that happens without the mod (e.g. Chaos 4 disappearing when hitting the pause button). When in doubt, disable the mod and try again.

**How to test cutscene transitions**
Attach Cheat Engine to sonic.exe and add the 4-byte value at 3B2C570 to the list of values. When you find a post-cutscene camera transition that isn't supposed to happen (i.e. when it's better that the camera cut immediately to the character), write down the value 3B2C570 and report it here with a brief description of the cutscene (e.g. Big exiting the elevator after Twinkle Park). This is needed only for characters other than Sonic.

**How to report crashes**
Attach Cheat Engine to sonic.exe and add the 4-byte value at 3ABDBF4 to the list of values. When the game crashes, write down the value 3ABDBF4 and report it here with a brief description of where the game crashed.

**Additional notes (for myself mostly)**
SA1 PVMs with errors that had to be corrected in DC Conversion:
CHAOS4_COMMON - GBIX error
EFF_REGULAR - texture count error (repeated textures)
PVME101FACTORY - GBIX conflict
MOGURATATAKI - texture format error with Super Sonic's ear texture
OBJ_EC00 - transparency error with monorail sign
OBJ_EC30 - transparency error with monorail sign
OBJ_FINALEGG - alpha rejection issue with light texture that requires manual editing

Textures that don't have PVMs in SA1:
E101R - from .PB file
EROBO - from .PB file

PVMs that have extra textures in SADX/DC Conversion:
HIGHWAY03 - water animation enhancement
AL_ICON - SADX Chao
AVA_OPTION - new options
AVA_OPTION_E - new options
AVA_TITLE - new/different menu items
AVA_TITLE_E - new/different menu items
CON_REGULAR - new menu items
CON_REGULAR_E - new menu items
OBJ_REGULAR - extra textures for Metal Sonic
SCORE_BACK - ring count for Chao gardens

Textures replaced in SA1_Chars:
SHOOTING1
SHOOTING2
EV_EGGMOBLE0 (not in SA1_Chars yet)

SADX Chao textures:
AL_BODY
AL_OBJECT
AL_DX_CHAOS
AL_DX_ETC
AL_DX_PARTS_TEX
AL_DX_TEX_XYBUTTON
AL_ENT_CHAR all
AL_EYE
AL_JEWEL
AL_MOUTH
AL_OBJECT
AL_STG_KINDER_AD_TEX
AL_TEX_COMMON
AL_TEX_ENT_COMMON all
AL_TEX_ODEKAKE_MENU all
AL_TOY

**Comment by RinMaru** [comment]
Crash after emerald coast. Also the camera acts a bit diff in the pool area in SS after the cutscene
Crashed During Egg Hornet Cutscene

**Comment by PiKeyAr** [comment]
The above crashes happened because several PVR files were missing in the SADX system folder. I've uploaded a new build of the mod that adds back all PVR files from the DC version.

**Comment by PiKeyAr** [comment]
Use this DLL to get past the crash after the Egg Carrier transformation cutscene https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/DCMods_Main_4jun.7z

**Comment by RinMaru** [comment]
All is clear. Though Perfect Chaos seems to have an orange tint under him in the final round

**Comment by PiKeyAr** [comment]
I've updated the link with the latest build. Done a full playthrough of Sonic's story side by side with DC footage, added lots of minor fixes and adjustments. Now for the cutscene transition stuff only the other characters are left.

**Comment by PiKeyAr** [comment]
The new branch has been merged so the new build is now the main version of the mod.
