### ISSUE TITLE
Chaos 2 chandelier layering issues

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#207]
![layeringchandel](https://user-images.githubusercontent.com/26051785/57734452-85340a00-7667-11e9-85fb-ddd29f6dd1c7.PNG)

It's got a lot of them. Any way this can be fixed?

**Comment by PiKeyAr** [comment]
There's only so much that can be done to improve the look of meshes like this. Alpha rejection is probably unavoidable with this model, but writing 0x01 at 0054DFCA does seem to improve it a bit.

**Comment by PiKeyAr** [comment]
This object will be fixed in an upcoming update, not very soon though.
