### ISSUE TITLE
Window reflection textures not chaning for time of day

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#208]
I noticed that some of the window reflections in the Station area (Main area) of Station Square aren't changing based on the time of day. For example, the windows right next to the entrance to the hotel, at night, still reflect the daytime ones. The window on the side of the station building, to the left of the news stand, also shows daytime textures at night, and one of the windows close to the grass on the left side of the Speed Highway building also shows daytime textures at nighttime. All of these also happen in the evening.

![onearea](https://user-images.githubusercontent.com/26051785/57743439-b3771100-768a-11e9-8931-1121c695b72a.PNG)
![another area](https://user-images.githubusercontent.com/26051785/57743443-b5d96b00-768a-11e9-91f9-0f8cab9cf884.PNG)
![hotelarea](https://user-images.githubusercontent.com/26051785/57743446-b7a32e80-768a-11e9-8db6-1bf7e2bbfc1c.PNG)

**Comment by PiKeyAr** [comment]
Do night versions of these textures exist in the Dreamcast version?

**Comment by supercoolsonic** [comment]
Well, never mind. I assumed Sonic Team was competent enough to make textures for them, considering they did for other textures, but I guess I overestimated them. Sorry.

**Comment by supercoolsonic** [comment]
However, if you're in the mood to make an enhancement for this, I have some edited versions of the reflections textures in question. Versions for evening, and versions for night.




![kio_mado12_e](https://user-images.githubusercontent.com/26051785/57747449-40c26180-769b-11e9-8f7b-e8cedb95496c.png)
![kio_mado13_e](https://user-images.githubusercontent.com/26051785/57747452-428c2500-769b-11e9-8c5f-92b2b8a2ec2a.png)
![kio_mado14_e](https://user-images.githubusercontent.com/26051785/57747455-4455e880-769b-11e9-8dc6-a41fb55007fd.png)
![kio_mado12_n](https://user-images.githubusercontent.com/26051785/57747458-45871580-769b-11e9-8b06-c5a9924e47e4.png)
![kio_mado13_n](https://user-images.githubusercontent.com/26051785/57747460-461fac00-769b-11e9-8abf-16a3152d06ed.png)
![kio_mado14_n](https://user-images.githubusercontent.com/26051785/57747461-4750d900-769b-11e9-94ac-4349eeb63b54.png)

**Comment by PiKeyAr** [comment]
For Dreamcast Conversion I generally try hard to avoid editing original PVMs. But there's always a possibility to use this in a "general enhancements" mod, which I do want to make someday.

**Comment by supercoolsonic** [comment]
Okay, that's fine. I'd love to see that someday too.
