### ISSUE TITLE
Idle Chatter mod is active during cutscenes

### ISSUE THREAD

**Issue by TheWonderFromDownUnder** [PiKeyAr/sadx_dreamcast#215]
Pressing the idle chatter button will make the characters do their idle poses even during cutscenes.

![Screenshot (27)](https://user-images.githubusercontent.com/52037295/64194725-c69b3000-ce77-11e9-9814-5746dc3d34d1.png)

Note: It only works when they're standing still, and only the animation plays, not the voices.

**Comment by PiKeyAr** [comment]
Wrong repo?

**Comment by TheWonderFromDownUnder** [comment]
Actually, yeah. Thought this issue only appeared in the current version of DC Conversion, but no, it's definitely just an idle chatter thing. My mistake.
