### ISSUE TITLE
Game softlocks on Twinkle Circuit

### ISSUE THREAD

**Issue by TheWonderFromDownUnder** [PiKeyAr/sadx_dreamcast#216]
With the "Remove market ring count display" option enabled, the game will be unable to load the continue and quit options after beating a Twinkle Circuit race and softlock.

**Comment by PiKeyAr** [comment]
I think this is fixed in 0.5260?

**Comment by PiKeyAr** [comment]
Haven't been able to reproduce this on the latest version, I think this is fixed. Please reopen if you manage to reproduce it.
