### ISSUE TITLE
Crash after re entering Sky deck

### ISSUE THREAD

**Issue by Sora-yx** [PiKeyAr/sadx_dreamcast#219]
Hello, 
Not sure if this is known, but basically, in Adventure Mode, entering to Sky Deck, finishing it, and then re entering, makes the game crash. It happens with every character, although not everytime, but still pretty often. It also happens if you enter, leave and re enter. VS gave me this error:

![1](https://user-images.githubusercontent.com/50106301/70843371-7138cc80-1e31-11ea-8d16-add021d039c9.PNG)

![image](https://user-images.githubusercontent.com/50106301/70843441-8104e080-1e32-11ea-9bd9-cd27d46b0d5f.png)

**Comment by PiKeyAr** [comment]
Thanks for the report. I've added a check in today's update that will hopefully fix this.

**Comment by Sora-yx** [comment]
It did, thank you for the quick fix, nice work!
