### ISSUE TITLE
Dreamcast Conversion crashing during the demo loop

### ISSUE THREAD

**Issue by cheatfreak47** [PiKeyAr/sadx_dreamcast#221]
Was having some people do some testing and found a crash caused by Dreamcast conversion.

If you let the demo loop on the title screen run it's cutscenes, it crashes when it gets to the cutscene where Sonic and Amy talk in the casino area.

**Comment by cheatfreak47** [comment]
In case this information is helpful
```
Faulting application name: sonic.exe, version: 1.0.0.9, time stamp: 0x3f9aec4c
Faulting module name: sonic.exe, version: 1.0.0.9, time stamp: 0x3f9aec4c
Exception code: 0xc0000005
Fault offset: 0x003d7bee
Faulting process id: 0x3a5c
Faulting application start time: 0x01d5c1cb185e977d
```

**Comment by PiKeyAr** [comment]
I've just run the entire demo loop for all characters and it didn't crash.
What's your current mod list? Also make sure none of the mods have missing files (check integrity in the Mod Manager).

**Comment by PiKeyAr** [comment]
Tested again with DC Characters just to make sure
![image](https://user-images.githubusercontent.com/23312549/71898843-a79e0900-319d-11ea-888a-c8d44433d2fb.png)

**Comment by PiKeyAr** [comment]
Hopefully fixed in [this](https://github.com/PiKeyAr/sadx_dreamcast/commit/15cde9fe809b46fa70b7884c3c8324f5082f805f)
