### ISSUE TITLE
Dreamcast Sonic Team and Intro Won't Play

### ISSUE THREAD

**Issue by Dynaroo10** [PiKeyAr/sadx_dreamcast#222]
Upon loading the game, after the Sega logo it goes straight to the title screen skipping the Dreamcast Sonic Team and Intro Movies. 
If the config is to the SADX Sonic Team logo, that works fine.

![Untitled](https://user-images.githubusercontent.com/71418884/93413182-982b9f80-f896-11ea-914e-d489ac2992c6.png)

**Comment by Dynaroo10** [comment]
Forget to mention this happens even if Dreamcast Conversion is the only mod loaded.

**Comment by PiKeyAr** [comment]
Just to confirm, if all mods are disabled does it play the original SADX intro?

**Comment by Dynaroo10** [comment]
I just tried it with no mods enabled and the mod loader uninstalled and neither times did the SADX intro play.
I've have also tried verifying the files on Steam and reinstalling using your mod installer but it still won't play.
I did notice that before using your mod installer (when SADX was using the Steam exe and not the 2004 PC exe) the SADX intro did play then.

**Comment by PiKeyAr** [comment]
From [SADX Mod Installer FAQ](https://sadxmodinstaller.unreliable.network/index.php/frequently-asked-questions/)
>The game works but the videos won’t play. What’s wrong?


SADX relies on Windows Media Player to play videos and it doesn’t like certain video codecs.
1. If you use a version of Windows that doesn’t include Windows Media Player, install it separately.
2. If you use Smooth Video Project (SVP) or LAV, disable or uninstall them before playing. Some other codecs like ffdshow may also cause issues.

**Comment by Dynaroo10** [comment]
I See. I'll have a look into Windows Media Player to see if I can get the videos working.
They used to work so that was why I thought it might have been the mod.

Thanks for the help!

**Comment by Dynaroo10** [comment]
Managed to fix it. Apparently when I updated Windows it installed LAV without me knowing. 
Uninstalling it fixed the problem.
Sorry for bothering you and thanks again!
