### ISSUE TITLE
Chaos 0 Bugged out. Help?

### ISSUE THREAD

**Issue by Polk120** [PiKeyAr/sadx_dreamcast#226]
I don't know why this is happening. I installed the default mods with the guide setup option, i set up my controller, i started a new game, i watched the cutscene before sonic's fight with chaos 0 in the prolouge and.....Nothing is happening! the clock is stuck at 0, Chaos zero isn't moving and the game won't respond to ANY inputs. How do i fix this?

**Comment by PiKeyAr** [comment]
I have no idea, I've never seen this happen or heard about it before. Does the game freeze entirely, or do you still hear the sound/music? Does it work if you disable any of the mods and/or the Mod Loader?

**Comment by Polk120** [comment]
Never mind, i found out that it was just my ps4 controller not wantting to work for some reason. i plugged in a xbox one controller and it worked now. Sorry about that!

**Comment by PiKeyAr** [comment]
That's still weird though, unless the controller is malfunctioning it should work fine in SADX with the input mod provided that it's configured correctly.
