### ISSUE TITLE
Disable movies option?

### ISSUE THREAD

**Issue by metafarion** [PiKeyAr/sadx_dreamcast#228]
There is a config option in the Codes tab to skip the game's intro, and there's another one to skip cutscenes, but can it be possible for us to skip just the pre-rendered cinematics?

Full background: SADX and the Mod Loader and most of the mods I've tested work well in WINE, however there's a significant issue with Windows Media Player and its associated libraries which are needed to play the game's pre-rendered movie files.  The game crashes every time it tries to load one of these, and I've done a lot of research and fiddling with Winetricks et al without much success, but it occurs to me it would be a very simple, if not ideal, workaround to just turn playback of these movies off.  I believe the "Disable Cutscenes" option does this, but it also causes the game to skip most of the non-cinematic cutscenes, which is unnecessary overcorrection.

**Comment by PiKeyAr** [comment]
This issue tracker is for Dreamcast Conversion. The codes you mentioned are included with the Mod Loader. Unless the problem happens only with the files added by DC Conversion, I don't see why a feature like this should be implemented in this mod.

**Comment by metafarion** [comment]
Oh, you're right.  This would definitely be for the mod loader.  I guess I was up too late and I didn't notice whose repo I'd wandered into.
