### ISSUE TITLE
Mystic Ruins Object texture garbage

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#230]
I was watching my friend play through the game earlier and this happened:
![20210308165240_1](https://user-images.githubusercontent.com/26051785/110390785-7edd0200-8034-11eb-9202-3f28d1272705.jpg)
Specifically when the cutscene started with Eggman. This is Tails's story.

These are the mods he was using:
![modsSAL](https://user-images.githubusercontent.com/26051785/110390839-94eac280-8034-11eb-976b-2b867a937cc1.png)

**Comment by PiKeyAr** [comment]
I'd look into Better Tails AI since it loads custom textures. I don't have it installed at the moment, but I started Tails' story without it and it worked fine.

**Comment by PiKeyAr** [comment]
I haven't been able to reproduce this with and without the Better Tails AI mod, please reopen if still applicable.
