### ISSUE TITLE
 Issue with HD FMV-compatibility

### ISSUE THREAD

**Issue by LPFan12** [PiKeyAr/sadx_dreamcast#231]
The animated Dreamcast-Sonicteam Logo does not seem to display correctly when enabled while the HD FMV-mod is active. It displays small in the topleft corner of the screen and I have not found a way to get around this issue. It has to be an issue with the compatibility between the mods, because it worked well when I did not have the HD FMV-mod active.

**Comment by PiKeyAr** [comment]
This happens because the HD FMV mod hasn't been updated with the HD Sonic Team logo yet. For the current version of the mod, follow its developer's instructions to make it compatible with Dreamcast Conversion.

**Comment by PiKeyAr** [comment]
I think this is resolved with the latest version of the AI HD FMV mod.
