### ISSUE TITLE
Consistent crashing

### ISSUE THREAD

**Issue by superiorgamedude** [PiKeyAr/sadx_dreamcast#237]
I don't know if the creator will see this, considering how old this mod is, but I've been playing a lot more Sonic Adventure with mods lately, and have experienced consistent crashes. It happens at almost random, yet very specific places, such as Windy Valley, Red Mountain, and most consistently in Twinkle Circuit, but not Twinkle Park for some reason. However, this only occurs when I have the dreamcast conversion mod turned on. If I turn it off, but keep all my other mods on, the problem does not occur. And this only started with my new computer. It did not occur on my old one, and if it did, it wasn't nearly as often. Here is a screenshot to show what mods I am using:

![2021-11-12](https://user-images.githubusercontent.com/70874193/141525739-c33fc02f-e883-413b-b197-8cbd838c9eff.png)

**Comment by PiKeyAr** [comment]
Do the crashes keep happening if you only enable Lantern Engine and DC Conversion?

**Comment by superiorgamedude** [comment]
It doesn't seem like it. I tried multiple stages with both the Lantern Engine and the DC Conversion on, and nothing went wrong.

**Comment by superiorgamedude** [comment]
> Do the crashes keep happening if you only enable Lantern Engine and DC Conversion?

It doesn't seem like it. I tried multiple stages with both the Lantern Engine and the DC Conversion on, and nothing went wrong.

**Comment by PiKeyAr** [comment]
This suggests that there is a mod conflict. Try enabling your mods one by one and getting the game to crash to isolate which mod combination causes it. I've tried most of the other mods you have enabled, but I've never used the Light Speed Dash mod, so I'd suggest starting there. After you figure out which mod is conflicting, try putting it after Dreamcast Conversion on the mod list.

**Comment by superiorgamedude** [comment]
> This suggests that there is a mod conflict. Try enabling your mods one by one and getting the game to crash to isolate which mod combination causes it. I've tried most of the other mods you have enabled, but I've never used the Light Speed Dash mod, so I'd suggest starting there. After you figure out which mod is conflicting, try putting it after Dreamcast Conversion on the mod list.

Ok, so upon closer inspection, I am 95% sure it's the frame limiter mod (which I'm not even sure how that got there, I never downloaded it), but I'm still not too sure. As of right now, turning off the frame limiter seems to have solved the problem, but the crashes were so inconsistent that I still can't be 100% certain. I'll keep you notified if anything comes up.

**Comment by PiKeyAr** [comment]
I don't think Frame Limiter is likely to cause crashes. Furthermore, if the game seems to be crashing randomly, it could be something like a faulty graphics driver.
Anyway, this doesn't seem to be a problem with DC Conversion specifically so I'm closing this. If you need further help getting your modded setup to work, please ask on x-hax discord.
