### ISSUE TITLE
Flying textures at Twinkle Park mirror section.

### ISSUE THREAD

**Issue by HardDan** [PiKeyAr/sadx_dreamcast#238]
I know this was in the original dreamcast version, but I think, that this is a mistake, that is better to be fixed.
In Twinkle Park at Amy's mirrors section there is a room with floor traps, you can see there strange flying textures on the right. I think there was supposed to be a wall (like in reflection) but it was removed due to player's convinience, and developers accidently forgot textures there. It was fixed in DX version (which is wow, something good). So I think, that it would be better, if Dreamcast Conversion had this fix, as an option if you like, just delete those.

**Comment by PiKeyAr** [comment]
Those additional trap doors in the background may indeed look like an odd design choice, but their placement seems too elaborate to have been unintentional. Although there have been some exceptions, in principle this mod does not fix design flaws with original Dreamcast assets, unless they were clearly unintentional and there are hints on how the affected assets were supposed to look.


The placement of these trap doors is controlled by the SET file, and making an option just to remove them would be rather difficult. The "optimized" SET layouts used in the mod by default fix Z fighting and remove duplicate or redundant SET items, but it doesn't cover cases like this.
