### ISSUE TITLE
Rapidly flashing blue light during the Egg Viper boss fight

### ISSUE THREAD

**Issue by ezodagrom** [PiKeyAr/sadx_dreamcast#240]
Continuation from this issue that was closed on the lantern engine mod, since it was clarified that it is an issue with the dreamcast conversion:
https://github.com/michael-fadely/sadx-dc-lighting/issues/81

Even though it was mentioned that there are no plans to tone down the effect, I think it's very important to tone it down because it can potentially lead to epileptic attacks.

I wanted to avoid recording a video showing the issue since it could be dangerous for people with sensitivity to flashing lights, but it's the only way I can effectively show the issue. The only visual mods active are the dreamcast conversion and lantern engine.
I really recommend slowing down the video's playback speed if you have sensitivity to flashing lights.
https://www.youtube.com/watch?v=JdbGd9lP2sc

**Comment by PiKeyAr** [comment]
Here's a comparison of this effect between the original game and the mod at the highest intensity:
![image](https://user-images.githubusercontent.com/23312549/153873051-98a93a5e-3a6f-4470-9284-97631c47a83f.png)
Original effect video: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/eggviper.mp4
I think the color itself is fine, but it flashes a bit longer in the recreated version, and the flash frequency may be different. It's also a bit glitchy in the original game (the palette flashes white and sometimes red for a moment at certain frames) and I opted not to recreate the glitches.
I'm not sure how to deal with it to be honest. Is the original version of the effect also dangerous? If this effect can cause seizures, does the flashing fire effect in the Mystic Ruins Past also need to be toned down?

**Comment by ezodagrom** [comment]
I tried to see if I could change the effect to be more like the Dreamcast version, to flash between lightblue and white instead of flashing between lightblue and black, but I really don't understand much about this, I couldn't figure out how to change the black part of the effect, I could only change the lightblue part. :x

**Comment by ezodagrom** [comment]
I think I managed to make it closer to the dreamcast version.
Video:
https://www.youtube.com/watch?v=jLj-n0MjV2k

Image of the code changes:
https://i.imgur.com/enSKJsM.jpg

**Comment by ezodagrom** [comment]
> It's also a bit glitchy in the original game (the palette flashes white and sometimes red for a moment at certain frames) and I opted not to recreate the glitches. 

Sorry to be so annoying about this issue (I won't comment anymore after this unless there'll be replies to respond), I just wanted to note that I don't believe the original behaviour of flashing between light blue and white is a glitch (though the red in certain frames sounds like glitchy behaviour), I believe the flashes between light blue and white were intentional, since flashing between 2 bright colors feels alot less straining on the eyes than flashing between a bright color and a dark color like it currently does in the dreamcast conversion mod, at least to me.

**Comment by PiKeyAr** [comment]
I was able to capture original Egg Viper palette blending from the emulator:
https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SA1%20research/eggviper/red.mp4
https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SA1%20research/eggviper/blue.mp4
I will try to recreate it when I get to rewriting Egg Viper for the next update.

**Comment by ezodagrom** [comment]
> I was able to capture original Egg Viper palette blending from the emulator: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SA1%20research/eggviper/red.mp4 https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SA1%20research/eggviper/blue.mp4 I will try to recreate it when I get to rewriting Egg Viper for the next update.

Nice, thank you for the status update about the issue.

**Comment by PiKeyAr** [comment]
Progress on a more faithful version of the effect:
https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SA1%20research/eggviper/eggviper_pc_2.mp4
https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SA1%20research/eggviper/eggviper_pc_3.mp4

I also added a fadeout at the end so it doesn't cut back to regular lighting right after releasing the energy ball, making it a bit smoother looking.

**Comment by ezodagrom** [comment]
> Progress on a more faithful version of the effect: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SA1%20research/eggviper/eggviper_pc_2.mp4 https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/SA1%20research/eggviper/eggviper_pc_3.mp4
> 
> I also added a fadeout at the end so it doesn't cut back to regular lighting right after releasing the energy ball, making it a bit smoother looking.

That looks good, and the fadeout at the end is pretty nice .

**Comment by PiKeyAr** [comment]
The new version of the effect is now included in the latest release.
