### ISSUE TITLE
Egg Carrier in Skychase only becomes visible after a few seconds

### ISSUE THREAD

**Issue by Samuel555v** [PiKeyAr/sadx_dreamcast#245]
The Egg Carrier in skychase only becomes visible after a few seconds, I have did numerous amount of testing With other mods, And none of the mods causing it, Dreamcast Conversion is causing it, I also tried turning off and on some things in Dreamcast Conversion "Configure", And Didn't work. 

I have also tried reaching out to you about it in the x-hax Server, but you were offline, so I am putting this here so that you hopefully see this.

**Comment by Samuel555v** [comment]
@PiKeyAr doin ping so it gives notification (idk how notification system works in github)

**Comment by PiKeyAr** [comment]
Thanks for the report. This should now be fixed in the latest update.
