### ISSUE TITLE
Game crashes when Super Sonic jumps while holding a Light Speed Dash

### ISSUE THREAD

**Issue by TheRamosOnline** [PiKeyAr/sadx_dreamcast#247]
As the title says.
Only mods active are Super Sonic and Dreamcast Conversion.
The issue itself seems to be caused by the glow of the Light Speed Dash. When Dreamcast Conversion is turned off, there is no blue glow and the crash doesn't occur. See videos for reference;
![image](https://user-images.githubusercontent.com/45015774/162998813-2a98cfc0-4324-4f1c-9dec-eb942d35b1e6.png)

https://user-images.githubusercontent.com/45015774/162999353-c5030ece-e01c-419e-9c3d-4836c6ee2500.mp4

https://user-images.githubusercontent.com/45015774/162999370-cef43781-76c9-40a0-8c52-81fd384d590f.mp4

**Comment by PiKeyAr** [comment]
See [this issue](https://github.com/kellsnc/sadx-super-sonic/issues/2)

**Comment by Skittleology** [comment]
same thing actually happens to me when Super Sonic is listed below Dreamcast Conversion

**Comment by Skittleology** [comment]
it's a conflict. it's not this mod

**Comment by PiKeyAr** [comment]
I have confirmed that the crash goes away and the aura works correctly if the Super Sonic mod is placed under Dreamcast Conversion on the mod list.
