### ISSUE TITLE
Light Speed Dash shortcut in Red Mountain can't be taken.

### ISSUE THREAD

**Issue by LimitCrown** [PiKeyAr/sadx_dreamcast#25]
In the first half of Sonic's Red Mountain stage, if you try to use the trail of rings to reach the area with a few extra lives, then you won't be launched high enough to reach it.

**Comment by PiKeyAr** [comment]
Fixed this and a couple other thing. [Here's a fixed SET file](https://www.dropbox.com/s/n6qcbo03uxgbzbx/SET0500S.BIN?dl=0).
Thanks for the report!

**Comment by LimitCrown** [comment]
Thanks! The error was resolved.
