### ISSUE TITLE
Crash in last area of Sky Deck and Super Sonic's story

### ISSUE THREAD

**Issue by Snoogleflorp** [PiKeyAr/sadx_dreamcast#253]
- Playing Sky Deck by any means (Adventure mode, trial, new save) causes the game to crash here. I disabled all other mods (except Input Mod), including Lantern engine, to test this, although it seems to happen no matter what mods I have on. Disabling Dreamcast Conversion fixes this.
![sadxcrash](https://user-images.githubusercontent.com/77871568/200140356-a0ac181b-6209-4d25-9efb-cd8a5fc9675b.png)
- Playing the Super Sonic story, after the FMV the game will immediately crash. Same deal, fixed when Dreamcast Conversion is disabled. Skipping the cutscene also prevents the crash.
![fmvcrash](https://user-images.githubusercontent.com/77871568/200141202-f780d150-3da8-4ff6-92d4-b3d3b18f106c.png)
![sadxloader](https://user-images.githubusercontent.com/77871568/200140507-d42cb953-4975-4514-8a49-b328ce34ea72.png)

**Comment by PiKeyAr** [comment]
Are these reproducible on the latest version of the mod? The screenshot shows 0.6031 while the latest version is 0.6034.

**Comment by Snoogleflorp** [comment]
Yup, it's fixed now. Weird that the mod loader didn't have a popup about the update when I definitely had it set to check for updates on start up. Still, my bad for not making sure.
