### ISSUE TITLE
Dreamcast Sonic Team Logo is Locked

### ISSUE THREAD

**Issue by ElectroNuke** [PiKeyAr/sadx_dreamcast#254]
I'm glad to see the "disable chao replacement" option added! Only problem is, it doesn't seem like the Dreamcast Sonic Team logo can be disabled. Might just be a simple coding error.

**Comment by PiKeyAr** [comment]
It works for me, have you checked that "Sonic Team logo mode" is set to "SADX" or "Off" in the configuration window?

**Comment by ElectroNuke** [comment]
Yes. Reordering it above and below my other mods doesn't work, either.

**Comment by ElectroNuke** [comment]
Yes. Reordering it above and below my other mods didn't work, either. Disabling all video enhancements did it for me, but that renders the other options in that section completely useless.

**Comment by PiKeyAr** [comment]
Still unable to reproduce this
