### ISSUE TITLE
Crashes at this scene with Tikal

### ISSUE THREAD

**Issue by TheDragonary** [PiKeyAr/sadx_dreamcast#257]
I don't know if the same problem would occur for the other characters when they get this sort of scene but happened for Sonic

![71250_20230119120118_1](https://user-images.githubusercontent.com/112120245/213441649-0642c77f-9a24-4c67-89f5-98f6c16727cb.png)
[crashdumpandconfig.zip](https://github.com/PiKeyAr/sadx_dreamcast/files/10456702/crashdumpandconfig.zip)

**Comment by TheDragonary** [comment]
Could I also add that egg carrier chao garden seems to crash a lot. Well it says the game stopped working instead of giving an error and crash dump. Don't know if this is a problem with DC conversion or my computer although last time I played SADX with DC conversion too, there were no crashes ever.

**Comment by PiKeyAr** [comment]
Are you sure this is DC Conversion crashing?

**Comment by TheDragonary** [comment]
Oh sorry I just disabled it and checked right now, yeah its not DC conversion
