### ISSUE TITLE
Windy Valley Beta Framerate

### ISSUE THREAD

**Issue by shadowstardx** [PiKeyAr/sadx_dreamcast#258]
The framerate for the auto-demo version of Windy Valley  is dropping for some reason

**Comment by cheatfreak47** [comment]
the Windy Valley autodemo stage has higher requirements to run well than most of the rest of the game, this is normal and has nothing to do with the dreamcast conversion

in fact, one of the reasons the stage was cut originally was *likely* because it was too much for the dreamcast to handle

**Comment by shadowstardx** [comment]
Thanks for getting back to me quick. I will check again.

**Comment by PiKeyAr** [comment]
This issue tracker is for Dreamcast Conversion. Please report problems with other mods to their respective developers.

**Comment by shadowstardx** [comment]
It is only happening with the auto demo windy valley. Every other level runs perfect.
