### ISSUE TITLE
Broken framerate only happening with the auto demo windy valley. Wasn't an issue before

### ISSUE THREAD

**Issue by shadowstardx** [PiKeyAr/sadx_dreamcast#259]
The problem probably has something to do with the mod loader. My gaming computer isn't a potato and was running this level fine before.

**Comment by PiKeyAr** [comment]
This issue tracker is for Dreamcast Conversion, not the Mod Loader or the Autodemo Windy Valley mod. The Autodemo Windy Valley mod has known performance issues that aren't exclusive to low-end PCs. The "Resizable Window" option in the Mod Manager is also known to affect performance. If you have it enabled, you can turn it off for better performance.

**Comment by shadowstardx** [comment]
Thank you! Resizable window breaks the frame rate for some some reason
