### ISSUE TITLE
An issue with Big The Cat's Hot Shelter stage.

### ISSUE THREAD

**Issue by LimitCrown** [PiKeyAr/sadx_dreamcast#26]
After one of the updates, the glass covering the top of the fish tank in the upper floor of Hot Shelter looks like it has been raised a little bit. It's no longer possible to break the glass covering the fish tank with the Kiki's bombs. The hint monitor that talks about the fish tank is directly in the middle of one of the walkways, so it prevents Big from easily reaching the fish tank from there. The glass also seems to be a brighter green color than usual.

**Comment by PiKeyAr** [comment]
I had no idea it was possible to break that glass...
The reason for everything you described above is that I remade the water and the glass as landtable objects (they were SET objects originally) to avoid transparency sorting issues. I didn't know there was interactivity attached to the glass object. That complicates things.
I can undo the change partially but that may cause glitches in Amy's part of the stage. Well, I'll just have to see how it goes I guess.

**Comment by PiKeyAr** [comment]
Updated the mod and the SET files: https://www.dropbox.com/sh/aawtmh4zsyntr1q/AADvwtT4Ts1N8fi3XXatvZb9a?dl=0

**Comment by LimitCrown** [comment]
Alright. The glass above the fish tank can be broken again. I don't notice any issues with her portion of the stage, so it may be fine.
