### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by throwaway1908** [PiKeyAr/sadx_dreamcast#260]
Hi, I want to ask a question and I am not sure where else to ask this, so I hope here is fine. 
Basically, I am trying to edit the Dreamcast version of Sonic Adventure and I am having trouble finding the texture file for the text "Now saving". I noticed there was an option to disable it in the Dreamcast conversion mod, so I am wondering if any of you could tell me where the location of this file/texture is in the game files?

**Comment by PiKeyAr** [comment]
"Now saving" is a string that is drawn using the game's debug font, same as DLC strings. The font texture is a headerless PVR embedded in 1ST_READ.bin.

For SA1/SADX modding, please ask on the x-hax Discord server, #sa1-modding channel.
