### ISSUE TITLE
Cutscene stuttering issue

### ISSUE THREAD

**Issue by Bigmac9922** [PiKeyAr/sadx_dreamcast#262]
When you play dreamcast conversion mod the game stutters constantly however I found 2 mods that fixed the game the 63 fps mod and also the camera code error fix mod both are needed for buttery smooth gameplay links are here (https://www.speedrun.com/sadx/resources). However even with the mods all pre rendered and ingame cutscenes constantly stutter even on my gsync monitor the cutscenes are not 63 fps when using the mods they are 30 but that is not a problem however it seems that the frame pacing is off horribly and because it is at 30 fps instead of 63 i cant limit the framerate to make it stable. My gsync monitor has a framerate range of 1-240 so this shouldn't be a issue even if it was not capped but it seems because it fluctuates so much it still stutters however it is not as bad as a standard monitor without gsync. Is there any way to possibly make a cutscene specific fps limiter mod to make it buttery smooth 30fps instead of it jumping around constantly or even make the cutscene's speed not be tied to fps and allow it to be what ever fps the game is running at preferably 63 fps because 60 causes stuttering due to a engine issue. @PiKeyAr @michael-fadely

**Comment by Bigmac9922** [comment]
If a better cutscene specific fps limiter was made it might help stabilize the stuttering. I would fps cap the cutscenes using rtss to make them smooth like the game is but because they are running at 30fps instead of 63 this is not possible.

**Comment by PiKeyAr** [comment]
Are you sure any of this is caused by the Dreamcast Conversion mod? Does it stop happening if you untick Dreamcast Conversion in the Mod Manager?

**Comment by Bigmac9922** [comment]
I uncheck all the mods and it still stutters on cutscenes. I think its the base game sonic adventure 2004 that causes the issue as the steam version doesn't have the cutscene stutter.

**Comment by Bigmac9922** [comment]
Any idea on how to possibly fix the cutscene frame pacing?

**Comment by PiKeyAr** [comment]
The 2004 PC port has weird framepacing in general, I don't know if there's a proper solution for it. I've heard reports of the d3d8to9 wrapper causing framepacing issues, with some systems achieving better results after replacing d3d8.dll with an older version. But otherwise I don't know.

**Comment by Bigmac9922** [comment]
I tried swapping the d3d8to9 wrapper to a older version and it does help but doesn't completely fix it. The actual gameplay would stutter horribly until I added the 2 mods above now it runs buttery smooth the only thing is the pre rendered and ingame cutscenes stutter but gsync helps alot.

**Comment by michael-fadely** [comment]
This is indeed an engine problem and not a Dreamcast Conversion problem. Unless my frame limiter has been integrated into the mod loader, disabling the frame limit mod should restore the original 62-63 FPS frame rate. I haven't been able to figure out why it stutters, but it also most certainly happens during 60 FPS gameplay, for what that's worth.

**Comment by Bigmac9922** [comment]
I did get the fps buttery smooth no stutter while in gameplay with your [63fps mod] and [Camera Code Error Fix (1.0)] without using both of these I had stuttering. These should definitely be bundled with the mod loader as a optional toggle for easy access. However the only thing I have found to help alleviate the cutscene stutter is to use DXVK and use d3d8 to 9 v1.10.1 this helps cutscenes that have a cap with 30fps become more stable. Gsync also helps with cutscene stutter greatly but it still happens. The way the game loads model animations may be what creates stuttering during cutscenes.

**Comment by Bigmac9922** [comment]
Is there a way to possibly make the cutscenes animations not be tied to the framerate so you could make them 63fps. As there seem to be mods to edit the cutscenes to have different text, character's and animations. There even seems to be fps mods to make the cutscenes have higher fps but this makes the animations way to fast.
