### ISSUE TITLE
Can't update Dreamcast Conversion any longer

### ISSUE THREAD

**Issue by Ceejus** [PiKeyAr/sadx_dreamcast#265]
"Failed to update mod Dreamcast Conversion:
Size of downloaded file "DCMods_Main.dll" (192.00 bytes) differs from manifest (605.50 KB).
Press retry to try again, or Cancel to skip this mod."

**Comment by PiKeyAr** [comment]
I tested the update on another computer. The file on the server has the correct size that matches the manifest. Check your Internet connection and try again.
