### ISSUE TITLE
chao garden bug

### ISSUE THREAD

**Issue by Lucianoiscool2848** [PiKeyAr/sadx_dreamcast#266]
![Captura de pantalla (270)](https://github.com/PiKeyAr/sadx_dreamcast/assets/90996640/9b7e6c0c-2f44-417d-b057-298e55d072b9)
when the exit door and the VMU transporter are both loaded in a certain radius, the door's textures mess up and when i spindash, the game crashes

**Comment by PiKeyAr** [comment]
This was fixed a while ago. Are you using the latest version of the mod?

**Comment by Lucianoiscool2848** [comment]
Updated. seems fixed now. but... it caused another bug? the chao eggs dissapear when hatching and when they crack they take the textures of the dark egg
![Captura de pantalla (271)](https://github.com/PiKeyAr/sadx_dreamcast/assets/90996640/86214c90-8efc-439f-89f4-b8f31d93bc5e)
![Captura de pantalla (272)](https://github.com/PiKeyAr/sadx_dreamcast/assets/90996640/405315c0-95bd-4b61-9392-4598f18e5eb3)

**Comment by PiKeyAr** [comment]
This was also fixed around the same time... Please share your mod version number.

**Comment by Lucianoiscool2848** [comment]
Thanks PKR! I updated it and both bugs seem fixed now
