### ISSUE TITLE
Sound Overhaul feedback

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#29]
Please report all issues with Sound Overhaul here. Things like:

- Sounds clicking/clipping
- Sounds that play with a delay that shouldn't be there
- Sounds that play on the Dreamcast but are missing in SADX even with Sound Overhaul installed
- Sounds that are too loud
- Sounds that are too quiet
- Sounds that have an effect (echo etc.) on the Dreamcast, but are lacking it in SADX
- Sounds that play for too long or loop endlessly when it isn't needed (some of these I can't fix)
- Sounds that don't loop when they should
- Sounds that are looped wrong or get cut off too early (sadly I can't fix it in most cases)
- Wrong sound effects used by characters, badniks etc.
- Any other differences in the way the effects sound in comparison with the Dreamcast version

When reporting an issue with Sound Overhaul, please include the following information:

1. Where and when it happens (if you can locate the problematic sound in the mod's soundbanks, that's even better)
2. Whether the problem happens in the Dreamcast version
3. Whether the problem happens in unmodded SADX

Known issues:

- The sound that plays when you go through rings in NiGHTS pinball stage is missing
- The Egg Hornet engine sound loops incorrectly at 60 FPS
- Eggman's announcements in Sky Deck 2 are cut off at 60 FPS
- Tornado's crashing sound in several cutscenes are played too early due to a bug in game's code

**Comment by PiKeyAr** [comment]
When the bullets drop down in the cutscene before Chaos 0, it sounds like one bullet, while on the Dreamcast it had a reverb effect to imitate the sound of multiple bullets.
Egg Hornet's engine sound is looped incorrectly (requires a code-based fix)
Zero's chest-thumping sound is a single sound, but on the Dreamcast it repeated several times.
Amy's hammer punch uses a wrong sound.

**Comment by KNNSpeed** [comment]
- Twinkle Circuit's initial countdown timer makes only 1 beep instead of three (the sound just needs to be looped 2 more times--the zero chest-bumping noise might require the same fix)

I've also come across your mentioning on SonicRetro that your Dreamcast sounds have some kind of echo--I have my own rip and also extracted all the SFX (I modified the MLT python scripts to extract every bank from every audio file to minidsf), and I'm not really hearing any echo, using WinAmp with in_aodsf to directly play the files and to mass convert the many thousands of sound files.

**Comment by PiKeyAr** [comment]
Hi there,

Would you mind sharing your rips of the following?

SANDHILL bank 01 sounds 00 and 01
V_AMY_E bank 06 sound 01
ICECAP bank 01 sound 10
Any level bank 00 sound 01
Do sounds from, say, ALIFE_AMY play fine?

Thanks in advance!

**Comment by KNNSpeed** [comment]
ALIFE_AMY seems fine, yeah.

[WAVs.zip](https://github.com/PiKeyAr/sadx_dreamcast/files/765487/WAVs.zip)

I think I see what you mean by echo in the character voices, actually. Incidentally, issues like that are not unique to this game--I've definitely come across it with rips from other games before. For example, I've ripped my copy of StarFox Adventures and it has inaccuracies due to incomplete/improper decoding of the sequencing library. That is to say, I think the "echo" has something to do with the dsf plugin's interpretation of the dsflib library, since the library stores all the "notes" or "instrumentation" and each minidsf is probably like, say, sheet music. 

If it's not that, then I'd wager that that's just how it had to be encoded to deal with any hardware distortion in the Dreamcast's DSP. I tried the same rip in Demul just now and Amy's hammer swing noise sounds exactly the same through that as it does on vanilla SADX PC.

**Comment by KNNSpeed** [comment]
Here's what Demul sounded like (it has a built-in record sound button! Who knew??):
[spuDemul - Copy.zip](https://github.com/PiKeyAr/sadx_dreamcast/files/765505/spuDemul.-.Copy.zip)

**Comment by PiKeyAr** [comment]
Thanks for sharing. I've checked the sounds, and the reverb effect is indeed present in Amy's voice clip, while it doesn't in SA1 (you can check in sound test). Sand Hill sounds are inaccurate, same difference I ran into with my rips. The "select" sound has audible clipping caused by DC offset (not sure that's the correct term, but still), you can look at its spectrogram to see what I mean.

I know there is a way to disable reverb in another plugin for foobar2000, but with it disabled some sounds get broken in other ways because it also disables DSP emulation completely. I think the only way to rip sounds properly at the moment is via the sound test, and then still some editing would be necessary.

**Comment by KNNSpeed** [comment]
Out of curiosity, were you using aoDSF or this: https://hydrogenaud.io/index.php/topic,73786.0.html ?

**Comment by PiKeyAr** [comment]
The HighlyTheoretical one is the plugin where you can disable DSP emulation. With this plugin, some sounds come out distorted or just broken. I think I've tried another foobar2000 plugin as well, which was a bit better but still inaccurate.

As for the Sound Overhaul, I used DSF Decoder 0.10 Winamp plugin. There's also "2SF Decorder 0.22" but it doesn't seem to fare much better.

**Comment by KNNSpeed** [comment]
Darn. So I guess the format's not been fully figured out by non-emulator devs. Might it be worth asking the DEmul team about it? Maybe there's a way to have DEmul autodump the SFX as the game gets played, which would give me a pretty good reason to play through the whole story again one of these days. ;p

**Comment by PiKeyAr** [comment]
I don't think Demul has means to tell different sound effects apart.

The Audio Overload SDK is open source, so theoretically it's possible to build a plugin with reverb disabled and DSP emulation enabled, but I have almost no experience with this kind of thing.

**Comment by PiKeyAr** [comment]
I have finally figured out what was wrong with some sounds being slowed down with Sound Overhaul. Turns out my earlier hypothesis was correct - the game forces some sounds to play at 22050hz no matter what sampling rate the actual sounds are. If the sound is of better quality, it is slowed down. There are only a few cases where this applies, and it's not universal - e.g. the same sound may be distorted in one level or cutscene, but play fine elsewhere.

There are like <10 sounds that need to be adjusted for this, but some of them are common sounds, like the jump sound, or the sound of a badnik being destroyed.

A compromise solution would be to resample just the problematic sounds. I have found a way to convert the sounds to 22050hz with pretty much no audible loss of quality - just tried it on the jump sound. Perhaps even the Dreamcast originally played them at 22050hz, who knows.

Now that we've figured it out, wel need to find a way to rip the sounds from the Dreamcast version without reverb. I should give all those DSF plugins another go.

**Comment by PiKeyAr** [comment]
I just found out that the DSF plugin was updated as recently as this month: http://www.foobar2000.org/components/view/foo_input_ht

I have tried it on some minidsf files, and it appears to work fine without reverb for some sounds, while other sounds are broken, like the sounds in P_AMY bank 3.

**Comment by PiKeyAr** [comment]
OH YES!

I've been able to disable reverb. Turns out you have to change the mixer parameter in the dsfmake script to something other than 0x00. This didn't fix the inaccuracies for Ice Cap and Sand Hill sounds, but the effects and the voice clips are now coming out without echo. This is super cool!

**Comment by PiKeyAr** [comment]
Okay, I think we're stuck with those plugins, since they still produce files that sound different from the Dreamcast version. While comparing their spectrograms, I noticed other defects, so I think we should drop the idea of ripping from MLTs entirely.

I have found an effective way to rip sound effects from the sound test that produces single sounds. The only thing we'll have to do is put each sound into the respective soundbank.

**Comment by KNNSpeed** [comment]
Wow, nice find!
Does the dsfmake trick work for most of the sounds?
Also any idea if changing "effect" can do anything useful?

**Comment by KNNSpeed** [comment]
I just checked my iTunes library (I rip my own game soundtracks), and there are a LOT of Dreamcast files thatdo actually play at 22.050 kHz. Notable ones include all of Phantasy Star Online v2's SFX (whatever was stored as ADX with the music files), and all of SA2's Chao audio. Interestingly, SA2 and PSO's BGM is all 32.000 kHz, as well as a variety of GameCube titles.

**Comment by PiKeyAr** [comment]
Thank you! Yeah, I'm inclined to believe SA1 effects were also played at 22050hz.

So OK, I've figured out a way to rip SA1 sounds from the soundtest. Here's how:
1. Run SA1 in Demul, go to the sound test.
2. Go to the soundbank you want to rip.
3. Enable sound recording in Demul's sound options.
4. Play each sound in the soundbank. Wait ~0.5 seconds between pressing any keys/buttons to switch/play sounds.
5. When done, copy spuDemul.wav from the Demul folder to desktop. At this point you may want to resample it to 22050hz. But make sure the quality loss isn't audible. I've been able to do this in Audacity with the following parameters:
![aud](https://cloud.githubusercontent.com/assets/23312549/23003645/9454b306-f435-11e6-92f2-4b3831c01db4.png)
After opening the file, you need to select "Project Rate" at the bottom of the window and set it to 22050hz. Then set the preferences as the screenshot above (you need to do this only once) and then proceed to saving the file (File->Export Audio->choose WAV).

6. Run [Wavepad Audio Splitter](http://www.nch.com.au/splitter/) (freeware)
7. Open spuDemul.wav and select Edit->Split at silences.
8. Select level threshhold -36dB (move the slider all the way to the left), silence duration ~400-500ms, everything else should be self explanatory. Press Split. Now you get separate sounds in a folder you chose in the splitter.
9. If you recorded the sounds in a consistent order, every second file will be a "select" sound, which you need to delete.
10. Now you have the "raw" sounds, which need to be looped (if necessary), converted to mono (if necessary, which it is in most cases).
11. The sounds need to be renamed and put into the respective soundbank. You can check the soundbanks in the Sound Overhaul mod, which has them as folders with WAV files. Beware of sound order and "empty" sounds, they're skipped by the soundtest, but they still need to be in the folder! The soundtest's soundbanks also aren't exactly the same (e.g. two soundbanks in the soundtest can be one bank in SADX), but the sound order is the same.

The above procedure isn't very hard to do, but it's tedious and it would be a lot faster with more people. So I'd appreciate your help if you're interested. So far I've done the COMMON bank, P_BIG and V_BIG as a test. I'm going to do the CHECK_SHEET bank, the ENEMY_SET bank, and English character voices (P_xxx and V_xxx_E).

If you would like to help, it would be great if you could do the level soundbanks. But don't touch the Chao-related soundbanks yet, as we haven't figured out the differences, which are huge.

The cutscenes (E_xxx) need some extra precautions because you have to compare them against the Dreamcast soundbanks because the SADX soundbanks have missing sounds. This is how I found the missing sounds for the Sound Overhaul mod.

Anyway, please let me know if you're interested in helping me with these rips, and which soundbanks you would like to process. You'll be credited in the Sound Overhaul credits, of course.

**Comment by KNNSpeed** [comment]
Try this for resampling (IIRC the only thing it touches is the sampling rate, and nothing else, but it does have command-line options):
[wavrsmp.exe.zip](https://github.com/PiKeyAr/sadx_dreamcast/files/778878/wavrsmp.exe.zip)

**Comment by KNNSpeed** [comment]
Converting stereo to mono en masse can also be easily accomplished with a program called "sox"

http://sox.10957.n7.nabble.com/Stereo-to-mono-td711.html

I have a script I can modify really quickly to do this batch conversion.

**Comment by PiKeyAr** [comment]
Converting/resampling things in not an issue. The issue is actually ripping the sounds and sorting them, which is like 60% of the work needed. The remaining 40% are looping the looped sounds and checking which sounds actually need the mono conversion. The only way to tell is to look at the sound and see if the left and right tracks are different. If they are the same, it can be safely converted to mono.

**Comment by KNNSpeed** [comment]
Perhaps instead of doing it by hand, it might be easier to modify the sadx-input-mod mod slightly to take one button press and cause it to output the sequence of commands needed (should be a simple For or While loop)? So you just go into sound test, hit like "Y" or something, and it just will auto-play each sound and record them overnight. All you'd need to tell this program manually is how many sounds are in each bank, and when to hit left/right instead of up/down. you'd just need to specify a 0.5 sec delay between each action. The only real issue then would be to know when an effect stopped, which you could maybe take advantage of the Windows "stereo mix" playback device and wait until it's been quiet for a while, or something like that.

**Comment by PiKeyAr** [comment]
Uhh how does SADX input mod fit into this if I'm recording sounds in Demul?

I think I'm comfortable with the method I suggested earlier, just finished check_sheet_bank02 and I'm really happy with the quality, too. Seems like this will resolve a lot of volume-related problems as well.

**Comment by KNNSpeed** [comment]
I was thinking something that emulates controller buttons, and sadx-input-mod interfaces with XInput. Xpadder would also potentially work. Just tryin' to think of a way that wouldn't be quite so tedious. ;)

**Comment by PiKeyAr** [comment]
Turns out some sounds are missing in the soundtest, so a combination of several approaches should be used. Nothing is easy with this game...

Notes for myself:
1. Amplify by 5.6db or normalize to -3.0db
2. Convert to mono if tracks are the same
3. Resample to 22050hz

**Comment by Zetchzie** [comment]
you using the GDI game or the CDI file laying around allot was trimmed from the CDI including sound files

**Comment by PiKeyAr** [comment]
Care to elaborate on that? I don't see how that is possible given that the sounds are in MLT soundbanks. If you delete them, the sound will disappear entirely for a stage/character.

**Comment by Zetchzie** [comment]
I may be wrong but I just know CDI files are modified and compressed to fit on discs and sound may suffer as a result. I know SA2 had its sounds washed out due to compression. plus sadx cdi file wont loop its music ingame. the original GDI does not present this issue. Im no coder but Id recomend you find a gdi dump for quality reasons and to be sure nothing was tampered with.

**Comment by PiKeyAr** [comment]
I did a comparison of a CDI rip I've been using and the GDI rip of version 1.005. The ADX files are indeed different, the binary files are also different, the MLT soundbanks are the same except the Casinopolis voice bank for Sonic and Tails. So I guess I'll switch to the GDI rip just in case.

**Comment by Zetchzie** [comment]
I just dont trust cdi rips anymore after numerous issues and then them being resolved in gdi rips. I spent so long looking for untouched dumps since my copies got messed up in storage along with my dreamcast when I was young.

**Comment by PiKeyAr** [comment]
I'd like to ask everyone following this issue to test a new preview of Sound Overhaul 2. Here's [a Retro post](http://forums.sonicretro.org/index.php?showtopic=35774&view=findpost&p=883778) with instructions and download.

**Comment by Thesch28** [comment]
It sounds amazing a lot better than the first version of Sound Overhaul!
Emerald coast sounds amazing with all those seagulls and water sound effects, This sure is a Big improvement over the last version Some things sound even better compared to the DC the volume of everything sounds just right!
except one thing and that is the Ring loss and Ring sound effect they sound good but I think they should be a bit louder not too much just a bit other than that everything seems right!

**Comment by Zetchzie** [comment]
sounds great on my end

**Comment by Thesch28** [comment]
MMM now that I played for a while with headphones I noticed some stuff and now I think the volume of the rings and ring loss is fine but I found some things that should be changed
1. Tikal's fade sound should fade away because after she gives you a tip the sound effect of the light getting away gets cut so adding a fading effect should be good so it would sound like it gets cut.
2. Gamma's Aim sound is way too loud if I keep aiming the sound gets too loud to the point it gets annoying so I think it would be a good idea to lower the volume of the effect just enough to still be heard without Earraping Headphones users xD.
3. the sound effect of the wheel badnik from emerald coast should lowered but just a bit not as low as DX.
4.Also the Kikis'(That orange Robot Monkey) bomb throwing sound effect becuase it kindda feels aout of place so I think it should be lowered as well not as low as DX but close.

Those are the only things I think should be changed by the most part everything sound great!
I didn't even know Tikal actually tried to point to a direction when saying ''This Way!'' like without that sound effect this mod has I still wouldn't even noticed!

**Comment by PiKeyAr** [comment]
Thanks for the feedback.

I gotta say I'm not looking into things like sounds being cut off - this is something SADX and even SA1 do by default, and it requires code-based fixes rather than sound editing. It also happens less often at 30FPS. I suspect there's a bug in SADX code that does the timing incorrectly.

I'm only interested in sound volume for now. And it looks like normalization isn't the way to go, because some sounds are actually supposed to be quiet, while normalizing them brings them all to the same level. This is why I wanted to amplify them first, but that caused clipping in some sounds. I honestly don't know how the Dreamcast version handles this, or why the SADX implementation is so awful.

Maybe I could amplify all sounds that won't clip, and normalize the sounds that would clip with amplification. Uh... I don't know.

**Comment by PiKeyAr** [comment]
Yeah, nope. It's very specific to each sound. I guess I could get away with normalizing the loud sounds and amplifying the quiet sounds, but honestly that sounds like way too much work.

**Comment by PiKeyAr** [comment]
OK, so it appears that SADX has sound volume settings for individual sounds, and those settings haven't been reverse engineered yet.
This means that rips and universal normalization/amplification aren't gonna be of much help. The game requires a complete remastering of sounds, which would have to be done by comparing the volume difference between SA1 and SADX sounds, and compensating that difference manually.

Obviously I'm not gonna do the above, but I think I'll do the following:
1. Rip all SA1 sounds from the sound test/soundbanks and convert them to a format usable with SADX
2. Apply selective normalization (while preserving the unmodified files just in case):
Character sounds: -2db?
Enemy/object sounds: -3db?
Cutscene sounds: -2db?
Background sounds: -4db or -5db or -6db?
3. Release Sound Overhaul 2 and wait for feedback on sound volume
4. Make individual adjustments to sounds based on players' feedback.

**Comment by PiKeyAr** [comment]
OK, how about this one? https://www.dropbox.com/s/u2pf5hkwridv5se/NewSoundOverhaulAmplified_preview.zip?dl=0

To me this sounds a lot closer to the Dreamcast version, and it seems to fix a few issues with stuff sounding too loud. Maybe I should stick with amplification?

**Comment by Thesch28** [comment]
That sounds like a good Idea for now.
I already heard that you said that the game uses the sound like if it ran at 30fps while running at 60fps because of some coding error making all these errors.
I was simply thinking that editing The fading sound after Tikal's tips would a good fix for now since is one of those sound effects that someone will hear a lot.

**Comment by Thesch28** [comment]
Also sorry for the grammar errors it's hard to type fast on a phone 'xD.

**Comment by PiKeyAr** [comment]
I probably won't be doing the sound remastering for the entire game, but let me know how the new previous I just uploaded sounds like. If it works out, I think I'll be able to get away with simple amplification and some fixes.

**Comment by PiKeyAr** [comment]
OK, disregard the previous test. Try this one: https://www.dropbox.com/s/g5j3ydj5m8cp5sn/NewSoundOverhaulMix_preview.zip?dl=0

**Comment by PiKeyAr** [comment]
OK, it was kinda stupid but I forgot to update index.txt in the COMMON bank, which means half the sounds weren't even getting replaced properly.

Here are 3 previews of the same mod: 
1. Normalized https://www.dropbox.com/s/p2t39mgb4oskbv4/NewSoundOverhaul_preview.zip?dl=0
2. Amplified https://www.dropbox.com/s/u2pf5hkwridv5se/NewSoundOverhaulAmplified_preview.zip?dl=0
3. Mix https://www.dropbox.com/s/g5j3ydj5m8cp5sn/NewSoundOverhaulMix_preview.zip?dl=0

Please redownload and let me know which you think sounds better. After updating the index in the normalized one, I feel like it's pretty good now.

**Comment by Thesch28** [comment]
Ok I played with these for a while and I noticed some differences and overall I liked Normalized by the most part but it has some things that I don't like but first here is a list of things that I think are worth to mention for each different preview.
Normalized: 1.Gamma's aim sound effect is too loud
2.Boots pad sound is good in normalized.
3.Bladed Spinner (That purple robot that flies) It's electricity sound effect is too loud)
4.Ring sound effect sounds good ring loss sound effect sounds good as well.
5.Background noises in Emerald coast sound good.

Mix: 1.Gamma's aim sound effect isn't as loud ad normalized but I sounds better to be honest.
2.Boost pad sound it too quiet and feels out of place
3.Bladed Spinner (That purple robot that flies) It's electricity sound effect isn't as loud as Normalized and sounds better to be honest it isn't so quiet but it isn't too loud.
4.Ring sound effect is too quiet ring loss as well.
5.Background noises are decent but I still prefer the ones from the Normalized preview.

Amplified: 1.Rings sound effect is too quiet ring loss as well.
2.Gamma's aim sounds a bit quieter than the mix one or at least that What I hear I still prefer the Mix one.
3.Boots pad sounds is too quiet.
4.charging spin dash sound effect is too quiet some other abilities like amy's upgraded hammer sound effect is too quiet, is like if these sounds where being heard from far away.
5.voices for abilities sound too quiet.
6.Bladed Spinner (That purple robot that flies) It's electricity sound effect feels a bit quieter than mix not too much but I still prefer how it sounds in mix.

Normalized is in general my favorite one specially for the background sound effects,Voices,Rings,etc.
I think Normalized should be used as the base for the public release but this is just my opinion but if that Happens I recommend replacing these 2 things.
1.Gamma's aim sound effect from Mix should be put in normalized.
2.Bladed Spinner electricity sound effect from Mix should be put in normalized.

**Comment by PiKeyAr** [comment]
I decided to do the whole sound thing in a different way.

I will rip the sounds from the MLT soundbanks using both HighlyTheoretical and aoDSF. Then I will pick the sounds without noise from HighlyTheoretical, and replace the glitchy sounds with aoDSF sounds. If a sound has audible defects in both versions, I will try to rip it from the sound test and amplify it to match the volume of the ripped sound.

**Comment by PiKeyAr** [comment]
Looks that won't work.

1) There are differences in how HighlyTheoretical and aoDSF handle the volume setting in the minidsf files, so they can't be ripped at the same volume.
2) With the HighlyTheoretical plugin, some sounds have clipping, but trying to prevent it makes other sounds too quiet. Even at the volume where some sounds clip, other sounds are still too quiet.
3) None of the above matches the volume of SADX sounds, although aoDSF comes pretty close.

The author of the HighlyTheoretical plugin said he doesn't know how to fix the noise issue with some sounds.

Looks like I'm stuck again...

**Comment by PiKeyAr** [comment]
I guess I really have no other choice. I'm going to mix and match the sounds from both rips, and then normalize them and deal with loudness complaints individually.

**Comment by PiKeyAr** [comment]
I have converted and categorized all soundbanks in the game (including all cutscenes and Japanese voices) except the Chao-related stuff, which is very different between SA1 and SADX so no direct conversion is possible. I have also found a better way to normalize sounds so that very few sounds are too loud. From what I've tested so far, it sounds pretty good, I really like the results.

The remaining things to do for Sound Overhaul 2 release:
1. Remove garbage and empty sounds
2. Convert to 22050hz
3. Loop the looping sounds
4. Add known missing effects: Zero's chest thump, Chaos 0 bullets
5. Normalize/amplify
6. Look for sounds that need to be in stereo (all bank 05 sounds, emerald coast bank_01 17 etc.) and fix them
7. Final playthrough and feedback

**Comment by PiKeyAr** [comment]
I am happy to announce that Sound Overhaul 2 has been released! Download it [here](http://www.moddb.com/mods/sadx-dreamcast-conversion/news/sound-overhaul-2-a-dreamcast-sound-mod#articlesform).

**Comment by Sonikko** [comment]
Some sounds are too loud, I don't know if it's like that in the Dreamcast version, but for example the bricks wall you break at the start of Windy Valley act 3 is very very loud and sounds low quality.
On the other hand I feel like the dash pads and springs sounds are too quiet.
The sounds volume is pretty inconsistent, some voice banks are very quiet, like Tails's "Yah!" when he starts flying, most are fine. But I think that all the sound effects should be on the same volume level, more or less.
Also if you ripped some of the sounds using an emulator, it's possible that they sound louder (and some times distorted since I think the audio is amplified beyond clipping levels) than they did on console since (afaik) it's a known issue with SA audio in DC emulators, and that would explain the volume level differencies, between the extracted audio files and the ripped ones.
I really appreciate the louder ambient sounds and the ones that were missing before.
Great job nonetheless, I'll make a proper list with all the sounds that sound wrong to me in some way, I only did a quick playthrough to see what's different, so I don't have a detailed list.

**Comment by PiKeyAr** [comment]
Thanks for the feedback. A few comments:

1) The brick sound - I feel like it's the same as in SA1 in terms of both loudness and quality, but I'll see if I can do something about it. The problem is that it becomes a lot louder when you break them one after another, and making it less loud would also make it almost silent when you break only one.
2) Dash pads and springs definitely feel right to me. You have to keep in mind that the levels in SA1 have very different music, and something that sounds about right for Emerald Coast, for example, will sound way too loud in Twinkle Park 1 or Casinopolis, so some compromise had to be made. Dash pads and springs are sounds in the common/checks sheet soundbanks, which means they have to be the same across the entire game. Although technically it's possible to make unique common soundbanks for the different levels (which was the case with SA1 Dreamcast), it will take way too much effort and consume a lot of disk space, and I'm not particularly interested in doing it.
3) Same for the voice clips - they have to be the same for the whole game, although I considered normalizing all of them at some point. We'll see. It was a problem in the Dreamcast version as well, so maybe normalization will help make them a bit better.
4) The ripped sounds from the emulator were actually too quiet, and I had to manually adjust the volume to match the rest of the sounds. As for the distortion, Demul sound emulation is pretty accurate as far as I know. I only ripped the P_... soundbanks, some character voices and the Emerald Coast soundbanks for this release.

If you do make a list, please consider the points I made above. Ideally I would also like to know if it sounds different in unmodded SADX and SA1. I am by no means a sound professional, and neither am I looking to do a complete audio remaster of the game again (maybe someday, when there's a better way to extract SA1 files), so some things I may or may not be able/willing to fix. But either way, I am collecting feedback and suggestions to see what I can do to improve it. I will also likely accept patches/fixes made by others, provided that they don't ruin the quality of a given sound.

Again, thanks for the feedback, and looking forward to more!

**Comment by PiKeyAr** [comment]
I decided to normalize English character voices because they sound better pretty much anywhere.

**Comment by Thesch28** [comment]
I have played with Sound overhaul 2 for a while and I have to say it's pretty good, I was actually going to suggest you to normalize the voices banks because they sounded better on the normalized preview.
This new version is a very huge improvement over the original release of sound overhaul there are many restored effects that I didn't even knew about but one little thing that feels off is the diving sound effect that the giant whale has in Emerald coast it's a bit too loud or at least that's what I think but It's not that much of a problem.

**Comment by Zetchzie** [comment]
my opinion is pretty much the same its just the whale effects that need tweaking everything else sounds great

**Comment by PiKeyAr** [comment]
I appreciate your feedback! In the meantime, I have updated the original post with a link to a folder that contains up-to-date fixes since the original 0.7 release of Sound Overhaul 2. To update the sounds, you just need to copy them over the originals in the same soundbank (I have preserved the folder structure for your convenience).

**Comment by Thesch28** [comment]
Thanks for the Info!, Quick question I haven't seen the small egg carrier door implementation uploaded to dropbox just like any other update, change, or fix before. are you going to put all the stuff into the official release only from now on?

**Comment by PiKeyAr** [comment]
I uploaded it as a separate test in #55, I will also update the Dropbox and MEGA mirrors once I make sure it's actually working. The reason the mirrors get updated less frequently now is that I'm waiting for the Mod Loader's update feature, which should be available soon.

**Comment by Shaddytheguy** [comment]
I feel like I've heard it talked about somewhere before, but the Egg Hornet's thruster noises don't loop right and just replay all janky-like.

**Comment by PiKeyAr** [comment]
Yep, it happens without mods too. It's an issue with how the game handles sounds at higher framerates - it should play fine at 30 FPS. Unfortunately there's currently no way for me to fix it.

**Comment by Thesch28** [comment]
So In Sky deck act 2 Eggman talks like giving orders I thik this was missing in dx.
But his voice sounds too quiet and it's kindda hard to hear even on DC i was wondering if those voice effects could be just a bit louder.

**Comment by Thesch28** [comment]
The sound effects of eggman talking in sky deck are in SKY_DECK_BANK01.
and the sound clips are SKYDECK_E_01_29-Decending into the clouds.
SKYDECK_E_01_30-go up, full speed ahead!

**Comment by PiKeyAr** [comment]
I noticed the Tornado crash sound too, but it gets cut off if I add a delay. It's just the way that cutscene is designed. It sucks, but someday we'll figure out how cutscenes work (getting pretty close actually) and hopefully fix this.

**Comment by Thesch28** [comment]
Eggman's announcements in Sky Deck 2 get cut both of them I'll assume this is because of coding issues with the game running at 60 fps.
I also think the ''go up, full speed ahead!'' gets cut on the DC version.
The ''Decending into the clouds, slow the ship down'' doesn't get cut.

**Comment by Thesch28** [comment]
The Sound effect of Chaos 6 using this attack > http://i.imgur.com/SARGMmq.png is a bit loud, I would recommend to lower it just like the splashing sound of the whale from Emerald coast.

**Comment by PiKeyAr** [comment]
I corrected the Chaos 6 sound and a few cutscene sounds, but at some point I lost track of my changes, so  I think I'll do another full test playthrough and release a new version of Sound Overhaul

**Comment by PiKeyAr** [comment]
I'd like to ask everyone to test version 0.8, which I uploaded to the pCloud mirror together with the other DC mods. The MEGA mirror will also be updates in a few hours.

If everything goes well, I will be releasing 0.8 in the coming 1-2 days.

**Comment by Zetchzie** [comment]
will do ^^ I love playing this game

**Comment by PiKeyAr** [comment]
That's most likely caused by the game playing the same sound several times at once, making it louder. I could make the climbing sound less loud overall, but then it would make it less audible in general. We'll see.

**Comment by Zetchzie** [comment]
no no no the sounds are fine lol it just happened in that one instance it sounds fine now

**Comment by Thesch28** [comment]
I think that happened to me before but knuckle's wall climbing sound it's ok.
I don't think it needs changes.

**Comment by Zetchzie** [comment]
Only thing thats different that i've noticed is tails voice when flying is louder then in DC and  spindash is slightly louder in DC

**Comment by Thesch28** [comment]
are your using the new version? by the way all character voices are louder they PiKeyAr normalized them because they sound better like that and well I agree with that.
or is the voice only a bit louder compared to the other version?

**Comment by Zetchzie** [comment]
only those two sounds i've really noticed aswell as the spindash being a bit different but im not going to nitpick it sounds great regardless

**Comment by Thesch28** [comment]
I already mention that eggman's lines on sky deck act 2 and some many others sound effects get cut too early because of an error on SADX sound coding which is related to the game running at a speed of 60 fps the original game was made for 30 fps but now that the game runs at 60fps there are some issues with how the game handles the sound.
basically some developer was too lazy to try to fix this and left many parts of the coding untouched when they needed some fixes.

**Comment by Zetchzie** [comment]
does setting the Framerate to 30fps fix it?

**Comment by Thesch28** [comment]
I Heard PiKeyAr saying that setting the framerate to 30fps fixes some of them.
By the way some sounds get cut on DC too but not as many as SADX.
for Example Eggman's ''go up, full speed ahead'' gets cut on DC too.
The people that made DX had the opportunity to fix errors that the original game had!
but they where too lazy and made everything lower quality, low res, and buggy.
and made sonic's skin orange like Donald Trump :V

**Comment by Zetchzie** [comment]
setting the fps to 30 on a 60fps screen makes the game play very erratic lol
