### ISSUE TITLE
Egg Viper explosion effect

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#30]
It just occurred to me that the effect described [here](https://github.com/SonicFreak94/sadx-dc-lighting/issues/26) could be achieved by simply altering fog color/distance. Should be easy enough to implement on my end.

**Comment by PiKeyAr** [comment]
Float at 0x3C58158 is the hit counter. I can trigger a color fade when it decreases, and force it to loop when the counter reaches 0. Now I need to find the explosion trigger.

**Comment by PiKeyAr** [comment]
Looks like SADX still has some code for this effect. There is a 4-byte value at 3C6E1EC that becomes 1 for the duration of the effect. sub_57E590 changes stage light's diffuse color and light direction. And of course it's not working in SADX for whatever reason.
I'll close this, since a fog-based implementation of this effect would be inaccurate. I'll leave this for SonicFreak94 to figure out in the PL mod.

**Comment by PiKeyAr** [comment]
As this is now possible to implement in the mod via the API I'm reopening this.

**Comment by PiKeyAr** [comment]
I've recreated the effect to the best of my ability, it's not 100% accurate to the original but I'm satisfied with the way it works currently.

**Comment by Rayray-Alcard** [comment]
Surely, functions beautifully. There is one issue: character select and stages stay red after beating egg viper via boss mode.
![untitled1](https://user-images.githubusercontent.com/27602092/28583246-82b11cce-7136-11e7-99a8-590c06e23e52.png)
![untitled2](https://user-images.githubusercontent.com/27602092/28583248-84ccdda4-7136-11e7-9a24-313c40a994ec.png)

The workaround is to enter Sky Deck.

**Comment by PiKeyAr** [comment]
I want to add another color when the Egg Viper is preparing to shoot a ball of plasma. It looks like it's supposed to flicker in blue, not red.

**Comment by PiKeyAr** [comment]
The "blue" effect should be enabled in today's update.
