### ISSUE TITLE
Mystic Ruins Major Missing Textures

### ISSUE THREAD

**Issue by KNNSpeed** [PiKeyAr/sadx_dreamcast#37]
See images (Warning: Large, 2880x1800). This only happens when going to the forest part from the minecart; they display correctly when exiting the Final Egg area.

![capture](https://cloud.githubusercontent.com/assets/9886112/22808238/f5dcb296-eef8-11e6-842e-c90a161c9ca6.PNG)
![capture2](https://cloud.githubusercontent.com/assets/9886112/22808246/f957799c-eef8-11e6-956c-5da991ff5dbe.PNG)

Similar issue; the rocks and bush have the wrong textures when returning via the minecart, but when you, say, start in the main Mystic Ruins area in Super Sonic's story, they're fine.

![capture3](https://cloud.githubusercontent.com/assets/9886112/22808259/fe8ccebc-eef8-11e6-8a5f-d4881bbb3184.PNG)
![capture4](https://cloud.githubusercontent.com/assets/9886112/22808263/0081b2fa-eef9-11e6-9836-396ebff8321a.PNG)

**Comment by PiKeyAr** [comment]
I've never seen this before. It looks like either a GBIX conflict or a PVM/texture pack overriding MROBJ. Could you post a screenshot of your SADX Mod Manager with a list of mods you have enabled?

**Comment by KNNSpeed** [comment]
![capture](https://cloud.githubusercontent.com/assets/9886112/22850309/4ed97ee2-efd5-11e6-9990-072c0c140c9b.PNG)

I have tried it without SADX:FE, and it still happens. I have noticed that the little yellow hexagons in Final Egg's hub at one point exhibited similar behavior when entering from Mystic Ruins, though I haven't seen that happen again in a while and this happens consistently. Nonetheless, maybe it's related?

**Comment by PiKeyAr** [comment]
So I just set up the following mods:
![untitled](https://cloud.githubusercontent.com/assets/23312549/22851377/8c726ffa-f063-11e6-8b39-f2c34c8d3b3c.png)
And I still can't reproduce it. Yesterday I played through the entire Sonic's story and I haven't seen it. A couple ideas. Try without the limit break mod? It's highly experimental anyway and known to break some things.
Are there any specific steps to reproduce the issues? What do I have to do step by step (starting with running the EXE)?

**Comment by PiKeyAr** [comment]
Also #38 may have something to do with this. Try with the updated DC_Branding mod to see if it still happens.

**Comment by PiKeyAr** [comment]
Just tried with the limit break mod, still can't reproduce it.

**Comment by PiKeyAr** [comment]
Is [this](https://github.com/SonicFreak94/sadx-dc-lighting/issues/18) related by any chance?

**Comment by KNNSpeed** [comment]
Looks like the new modloader fixed it. I didn't even know there was a newer version out. Thanks!
