### ISSUE TITLE
Water/Ocean textures

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#39]
![untitled](https://cloud.githubusercontent.com/assets/23312549/22842128/7a464faa-f017-11e6-835f-fd55c02e99d8.png)

So I found a way to hide the awful SADX water layers, and it allowed me to restore the Dreamcast look of the water in many levels.

Advantages of this approach:
- Looks exactly like on the Dreamcast
- Allows to restore more Dreamcast stuff that depends on the water looking the way it does
- Supports palettization
- No stupid color blending modes (e.g. the darker the texture, the more transparent it is - this is now gone)

Disadvantages:
- Not everyone likes SA1 water textures
- No multi-layered water objects
- Moving waves effect is lost (although it can be imitated relatively easily with UV manipulation)

So far I've been able to restore the following:
- Station Square (all acts + sewers)
- Mystic Ruins
- Mystic Ruins Past

I may be able to restore the Egg Carrier water too, though it's gonna be tricky. Emerald Coast is impossible to restore at the moment.

I'm pretty sure people will complain and say that the previous water textures looked better. So I think I'll make a separate mod with SADX style textures for those who prefer them to SA1 textures. SA1 textures will be enabled by default, however.

**Comment by PiKeyAr** [comment]
I was able to implement the ocean in Egg Carrier.

There is some minor stuff left, like Egg Hornet, Zero and E101 mk2. I can probably just copy the same water object over from the main landtables.

The water in Emerald Coast is a lot more tricky though...

**Comment by RenjinTenRyugaku** [comment]
Oh gosh YES! <3

**Comment by PiKeyAr** [comment]
SA1 water textures in all levels except Emerald Coast have been restored, including all Adventure Fields and boss arenas.
To revert to SADX style water textures from the previous version, use the "SADX Style Water" mod. The mod must be loaded BEFORE all of the DC mods.
The Emerald Coast water needs to be investigated separately, so I'll open a new issue for it.
