### ISSUE TITLE
Wave effect in Emerald Coast

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#40]
I don't know how doable this is, but it's a really cool effect that added a lot to the atmosphere in the original game. 
https://youtu.be/DjUgfunJu84?t=268
The lighting on the water changes to simulate a wave. Shame it got cut like everything else in SADX, really.

Reimplementing this effect will require:
1) Understanding how the Emerald Coast ocean object works in SADX
2) Ripping the higher poly model/transformation data from SA1
3) Applying lighting to simulate a wave

[Relevant issue](https://github.com/SonicFreak94/sadx-dc-lighting/issues/29)

**Comment by KNNSpeed** [comment]
It might help to know that the water in Emerald Cost SADX does already bob up and down with the whale. It just doesn't look like a wave--which might only be a matter of lighting (?)

**Comment by Zetchzie** [comment]
Idk but after playing it almost feels as if instead of actual waves the entire body of water shifts. it definitely dont look like there's any bending in geometry

**Comment by Flash2k17** [comment]
On Demul, this happens. Obvious bug, but heh.
You can see what the wave looks like a little better.
[img]http://upload.vstanced.com/images/2017/02/17/wEb.jpg[/img]

<details>
  <summary>Click to expand</summary>
  Demul has a "cold" blue RGB color tone, making everything look whiter-blue and nothing like the mod. It'd be a pretty bad idea if I compare you some texture with a whole different color tone and I don't want to ruin the mod that way. Am using the latest version of Demul. Changing between video modes do nothing. Worse is that I'd have to fully reboot my pc because a prompt will sometimes show up saying "not supported" with a black screen whenever I enter fullscreen. Which version of Demul are you using? What are your settings? I'd like to use what you recommend me to use but not with everything looking a little whiter/bluer...
</details>

**Comment by PiKeyAr** [comment]
You probably have custom color settings for your display that affects some 3D programs but not others. I see nothing wrong with colors in that screenshot.

**Comment by PiKeyAr** [comment]
STG01.BIN 001A132C - high poly water mesh in SA1. Possibly with animation at 0xA188

**Comment by Zetchzie** [comment]
Thats a nice screenshot you can definitely see whats happening.

**Comment by PiKeyAr** [comment]
Emerald Coast High Poly Ocean
Model: 0x1A132C
 
Function_1 Pointers
1A1330 //Points to NJS_MODEL Pointer for Model_1A132C
1B1AFC //Null Data
1A1838 //Points to NJS_MODEL Pointer for Model_1A1834
1B1AF4 //Null Data
1B1AF8 //Null Data
1A132C //High Poly Ocean Model
1B1B00 //Null Data
1B1B04 //Null Data
 
 
Function_2 Pointers
1A15B8 //Points to NJS_MODEL Pointer for Model_1A15B4
1A14DC //Points to Pointer to PVR Name Array
1A132C //High Poly Ocean Model
1A15B4 //Points to NJS_OBJECT at 0x1A15B4
1B1B04 //Null Data

**Comment by PiKeyAr** [comment]
SADX sea model that is most likely the one that needs to be changed: sonic.exe 00CC03FC

**Comment by KNNSpeed** [comment]
I wonder how feasible it would be to use the high poly ocean in other places in SADX. Modern PCs should be able to handle it, I'd think. Might be worth looking into when I have more time...

**Comment by Flash2k17** [comment]
Does this mean the sea model includes static for that old water texture to finally work?

**Comment by Zetchzie** [comment]
@Flash2k17 I imagine if they did this bad with the port, those assets are still there i'm betting

**Comment by PiKeyAr** [comment]
Here's a [video](https://www.dropbox.com/s/w4i3g6trjpk0bnj/Emerald%20Coast%20water.avi?dl=0) that lets you see the wave effect a bit closer.

You can clearly see the seams between the meshes, and what I think happens there is the following:
1. There are 2 high-poly water models - one used around the bridge when you first see the whale, and another, bigger one is used during the whale chase scene and for the effect when Sonic lands at the shore near the end of Act 1.
2. The effect consists of an animation, which is done by moving the vertices around in a sine wave-like motion. Also note how the direction of the wave is determined by the whale's position.
3. I'm not sure whether lighting on the models actually changes, or if it's merely clever use of palette lighting. I suspect the latter, i.e. it happens automatically because of the way palette lighting works.

The intriguing part is that both meshes (or at least one of them) are still there in SADX, but obviously they don't have that animation going on. There's even some code that is supposed to move the vertices around in the first model, and it uses stuff like sine and square roots. So... perhaps all the stuff is there, just broken?

**Comment by Flash2k17** [comment]
What if you're able to completely remove whale model and see if waves still occur? It's just so you can make sure that wave animation have to do with the whale itself.

**Comment by PiKeyAr** [comment]
Yes, the waves are triggered by the whale. That doesn't really help, though.

**Comment by Flash2k17** [comment]
Weird because the whale disappears half a second earlier before the water + bridge animation stops.

**Comment by Flash2k17** [comment]
Weird. All 3 whales disappear half a second earlier before the water + bridge animation stops.

I was also looking into it moments ago without water texture being visible, but was in DX when noticing the timing on whale disappearances before end of water animation.

I'm only saying it might be worth looking into without the whales' existence. Wave effect could just be a separate trigger with its own timing. Who knows?

**Comment by PiKeyAr** [comment]
I know that if you run the level with an empty SET file, the waves don't show up. I'm also pretty sure that they trigger when the whale makes a water splash.
Either way, why does this matter? If you want to look into the effect itself, you should be looking at the disassembly. The sub at 501300 seems to have something to do with the effect (vertices etc.), and sub_5015C0 is responsible for calming the water down after the waves show up. I've also posted the model's address in the EXE, which you can look up to see what happens to it.

**Comment by Flash2k17** [comment]
Wouldn't empty SET disable everything entirely other than land? I thought doing a little old fashion "connect the dots" on wave effect investigation would narrow down the path of the situation a little more, that way we wouldn't have to be focusing on something surrounded by another thing that's not sure if it may or may not have connection to the effect. I wasn't sure that video post paragraph already gave the answer before my question. Think that settles it. My bad—I'll back off now since I'm rookie at coding/hex stuff.

**Comment by PiKeyAr** [comment]
4F7800 - Act 2 water
4F78D0 - Act 3 water

**Comment by PiKeyAr** [comment]
[WIP video of the effect working in SADX](https://www.dropbox.com/s/e85lxwryaka0vxx/2017-04-12%2020-45-56.mp4?dl=0)
