### ISSUE TITLE
SADX-style water texture - transparency error

### ISSUE THREAD

**Issue by LimitCrown** [PiKeyAr/sadx_dreamcast#43]
After one of the recent updates, when the SADX-Style Water mod is enabled, the texture used for the water behind the Twinkle Park entrance isn't transparent. The problem doesn't occur with the Dreamcast-style water textures.

**Comment by PiKeyAr** [comment]
It occurs in both cases actually. It's also like that in unmodded SADX. Previously I used a pretty nasty workaround to restore the transparency, but it wasn't very accurate, and it can't be used with SA1 style textures, so I got rid of it. A universal solution may show up sometime soon.

For a list of other issues that require proper transparency sorting, see #42.

**Comment by PiKeyAr** [comment]
Oops, I guess you meant the pool water. How could I even miss that! Let's see...

**Comment by PiKeyAr** [comment]
I fixed the water in the sewers. This one, however, can't be fixed at the moment:
![tr](https://cloud.githubusercontent.com/assets/23312549/22870993/41a996d6-f1f0-11e6-8386-6e3766eb73cf.png)
Let me know if you find anything else odd with the water.

**Comment by LimitCrown** [comment]
I quickly went through the different areas with the changed water textures. There don't seem to be any other issues that I can notice currently.

**Comment by PiKeyAr** [comment]
Great! Thanks for testing. Feel free to reopen this if you run into any other water-related issues.

**Comment by PiKeyAr** [comment]
I have reimplemented my older workaround for SADX style with better accuracy. Now the alpha on the underwater parts is working:
![w](https://cloud.githubusercontent.com/assets/23312549/22901799/3d455d60-f276-11e6-9349-d9e79fe6beb7.png)
Getting this to work with SA1 water textures is a different story though...

**Comment by PiKeyAr** [comment]
This is now working the way I wanted to implement it, so I'm marking this as resolved.
