### ISSUE TITLE
Better SADX 4.0 breaks the textures of your mod.

### ISSUE THREAD

**Issue by RenjinTenRyugaku** [PiKeyAr/sadx_dreamcast#44]
After clean installing steam SADX and Better SADX 4.0 in that order, I have experienced various bugs with textures similar to issue #37.

I've looked to see what the problem was. Some user pointed out may have to do with something about extra sub folder being created whilst some of your mod files were being renamed. These are his images.

http://images.akamai.steamusercontent.com/ugc/80339584927997243/CADFB808AEDB85F9BC80605A1778EAF208AF93EF/

http://images.akamai.steamusercontent.com/ugc/80339584928007925/16C34330A97FEAECCF806B3948A9AEB3BE520D97/

His post — http://steamcommunity.com/app/71250/discussions/0/133256080236730414/#c133256758579347908

Reverting back to 3.6.1 and manually downloading dreamcast conversion fixed it for me. This is what he's said about the changelog — it did not include the important update mod.manifest and mod.version. What were those files supposed to do anyway? Auto update? None of those files were included at 4.0

**Comment by PiKeyAr** [comment]
You need to report this to the author of BetterSADX. I don't have the Steam version so I can't install BetterSADX. As mentioned on the FAQ page, I also don't support mod compilations that include DC Conversion (and I don't quite see the point of including it in such compilations). It's up to their authors to ensure proper mod compatibility.

There are 3 possible causes of texture issues:
1. Outdated mod loader. An old version had a bug in the texture replacement system. As most people running into texture issues are BetterSADX users, I assume it comes with an old version of the Mod Loader.
2. Wrong mod order. A correct example of mod order is included in the issue 37 you linked to.
3. Incompatible mods overriding textures. Any mods that modify level/object textures are incompatible. You can sometimes resolve this by loading the DC mods after the incompatible texture mods.

The folders make no difference, the most important part is mod order in the Mod Manager.
mod.manifest and mod.version are included for compatibility with the Mod Loader's mod update feature, which isn't available in the latest public version of the Mod Loader at the moment. Those files are currently just placeholders to allow updates when the Mod Loader has an official release.

**Comment by cheatfreak47** [comment]
@RenjinTenRyugaku I'll look into fixing this for the first BetterSADX Hotpatch, thanks.
