### ISSUE TITLE
Small portion of water not moving inside Station Square sewers.

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#47]
I know this is not too ''Big'' of a deal but I thought it was worth mentioning Here's a little GIF.
http://oi68.tinypic.com/5dl9hg.jpg
The Water is basically not moving at all, I'm pretty sure this little portion of water is animated on the Dreamcast version.

**Comment by PiKeyAr** [comment]
Oh yes, I've been meaning to fix this for a while but then I forgot about it. Thanks for the report!

**Comment by PiKeyAr** [comment]
Fixed
