### ISSUE TITLE
SADXStyleWater Not working in latest mod loader?

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#48]
heres my setup 

Mod1=ADX Music & Voice
Mod2=Input-Mod
Mod3=Smooth-Cam
Mod4=Pause-Hide
Mod5=Super Sonic Mod
Mod6=DC_Bosses
Mod7=DC_Branding
Mod8=DC_Casinopolis
Mod9=DC_EggCarrier
Mod10=DC_EmeraldCoast
Mod11=DC_FinalEgg
Mod12=DC_HotShelter
Mod13=DC_IceCap
Mod14=DC_LostWorld
Mod15=DC_MysticRuins
Mod16=DC_Past
Mod17=DC_RedMountain
Mod18=DC_SkyDeck
Mod19=DC_SpeedHighway
Mod20=DC_StationSquare
Mod21=DC_SubGames
Mod22=DC_TornadoModels
Mod23=DC_TwinklePark
Mod24=DC_WindyValley
Mod25=DC_EnvMaps
Mod26=DC~ HD GUI+CharTextures+Voices 
Mod27=SADXStyleWater
Mod28=TrainDaytime
Mod29=DC_Lighting
Mod30=NoGloss

I tried loading it first and then loading it last but neither works. I get DC water in SS but in emerald coast i get sadx water.

**Comment by PiKeyAr** [comment]
Have you by any chance renamed any of the DLLs? The DC mods check the DLL handle of "SADXStyleWater.dll". If it's renamed, they won't see it.

Also, as of the yesterday's update, it is no longer required to load SADXStyleWater first. But you need to update Station Square, Mystic Ruins, Past, Bosses and Egg Carrier for that to work.

**Comment by Zetchzie** [comment]
I used your update from Mega that you posted on SonicRetro.

I went to check the ini file and it never had the dll file in it LOL i feel stupid

**Comment by PiKeyAr** [comment]
Oh holy crap I totally forgot to include it in mod.ini when I was testing DC textures. Thanks for catching it! Bot Dropbox and Mega mirrors have been updated.

**Comment by Zetchzie** [comment]
ok lol ^^
