### ISSUE TITLE
Suggestion: Split out the TitleScreen stuff from DC_Branding

### ISSUE THREAD

**Issue by cheatfreak47** [PiKeyAr/sadx_dreamcast#51]
The current mockup title screen is pretty ugly especially in Widescreen, for this I'm suggesting that function be removed from this, and separated out into it's own mod DC_TitleScreen, so it can be worked on independently- hopefully in the future improvements to menu scaling and aspect ratio handling will make this a bit more desirable, but until then... it's kind of bad, and there's little that can be done about it except make it optional.

Or better yet have the dreamcast title screen ported (but I'm not counting on that obviously)

Anyhow, you did something similar with DC_SubGames and DC_TornadoModels which is partially why I'm making this suggestion.

**Comment by PiKeyAr** [comment]
I'm not interested in splitting this mod in the main release. You could take out the DLL, as it only disables titlescreen scrolling, changes window title and alters the color of the Pause menu buttons. The following PVMs contain titlescreen-related stuff:
AVA_GTITLE0_E.PVM
AVA_TITLE_BACK_E.PVM
AVA_TITLE_CMN.PVM
AVA_TITLE_CMN_SMALL.PVM

For 16:9, you could also use a workaround with squeezed textures that are stretched to look normal at 16:9, though I'm not a fan of that approach. A modified PVM for 16:9 was posted on Steam forums in the DC models/textures topic some time ago (I think F-Man still has it).

Also, while I agree that it could look better at 16:9 with proper scaling, I don't think the SADX title screen looks any better. It's just as stretched, and the main menu background looks even worse, not to mention the recompressed textures.

Also, here is a side-by-side comparison of SA1 titlescreen (stretched in Demul to the same resolution) and the DC Branding titlescreen:
![demul_2017_02_21_15_21_26_703](https://cloud.githubusercontent.com/assets/23312549/23153052/9f20af0c-f849-11e6-870c-681df75885b1.png)
![sonic_2017_02_21_15_21_31_408](https://cloud.githubusercontent.com/assets/23312549/23153053/9f21b33e-f849-11e6-8012-8cfbf4a7b4e1.png)

**Comment by cheatfreak47** [comment]
@PiKeyAr I kind of figured that was the case, and that's fine, I'll probably make my own fork that removes the title screen stuff from the dll to use in my personal setup. (doesn't seem to complicated, looking at the code)
_In any case,_ I have two things else to say on the subject of the title screen.

The position of "Start" there is a little bit off. should be moved over to the right by 29 pixels- so it's perfectly centered.
This image here should fix that slight off centering.
![p_enter_us_00](https://cloud.githubusercontent.com/assets/7818664/23165474/3f4545dc-f80a-11e6-90e4-d54db426abf0.png)


Next I have a bug to report with the title screen.
Running the game in 640x480 causes half the title screen background to scroll.
![sonic_2017-02-21_07-56-24](https://cloud.githubusercontent.com/assets/7818664/23165826/fe5e8888-f80b-11e6-9099-83ff4ab3d41e.png)

**Comment by PiKeyAr** [comment]
I have enabled custom mod support in the same manner SADX Style Water works. I won't be including the "Disable SA1 title screen" mod in the main package, but feel free to use it in BetterSADX.

**Comment by cheatfreak47** [comment]
@PiKeyAr if you wanna publish the source for that, you could probably stick it in the "depreciated" folder since that isn't built for the main mod build anyway

**Comment by PiKeyAr** [comment]
It's the same source as SADXStyleWater, I only renamed the resulting DLL.

It's a DLL that does nothing on its own, it only contains some info for the ModLoader to tell that it's loaded. The DC mods pick it up from the filename of the loaded DLL.
