### ISSUE TITLE
Gamma's Final Cutscene Glitch

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#52]
I don't know if this is happening to anyone else but after beating the ''E 101 beta mk2'' boss battle Gamma's final cutscene Glitched after he gets shot by Beta...
Gamma simply starts walking Infinitely against some piece of geometry? at least that's what I think anyways the cutscene never ends unless you press enter.
Here's a picture of how it looks like: http://i.imgur.com/X28sakZ.png the poor Gamma simply keeps walking forever xD.
And here's an image of the mods I'm using: http://i.imgur.com/dS4NhxS.png
This never happened to me in vanilla DX.
also here's a save file with Gamma's story completed by 90% just before Beta's final battle so anyone can see if this glitch happens : http://www.mediafire.com/file/e5epvfb3e9ip91t/SonicDX03.snc

**Comment by PiKeyAr** [comment]
I've tried the save (thanks for uploading it btw), and I couldn't reproduce it. Also, here's a save that starts right at that cutscene: https://www.dropbox.com/s/3rvp5vtrsgochuf/SonicDX03.snc?dl=0

Maybe it's something that happens in SADX? It looks similar to [this](https://www.youtube.com/watch?v=1DLqsmYHFXY&feature=youtu.be&t=194), which seems to happen sometimes even without any mods.

As for the mods image you posted, I have a few suggestions:
1) You don't need DC Camera Angles - the DC mods already include them
2) You don't need the NoGloss mod if you use the Palette Lighting mod

Let me know if you can reproduce the problem consistently. If you can, try again without the DC Bosses mod. If it happens consistently and only with the DC Bosses mod, I will port collision from the SADX landtable just in case.

**Comment by PiKeyAr** [comment]
OK wait a second. It may have something to do with SA1 water stuff.

**Comment by PiKeyAr** [comment]
Please try [this DLL](https://www.dropbox.com/s/k73ss8frcwjvasn/DC_EggCarrier.dll?dl=0) and let me know if it fixes the problem.

**Comment by Thesch28** [comment]
I can't use my pc right but now that you mention this Gamma always acted weird on the outside of the eggcarrier with the dc eggcarrier mod acting like if he was close to water (you know when he tries to fly like a helicopter to get away from the water) but on many parts of the skydeck that aren't even close to the water and that didn't happen as often in vanilla DX maybe that affected the cutscene? I played the beta last boss like 6 times with my save file and the glitch happened all those 6 times.

**Comment by Thesch28** [comment]
I'll try the DLL later, if it works
I'll report it as soon as I could.

**Comment by PiKeyAr** [comment]
Yeah, those sound as if they may be related to what I just fixed. Feel free to reopen it if you run into any of those again.

**Comment by Thesch28** [comment]
I used the DLL and the save file you gave me and I think it's fixed now, Gamma also doesn't go into that anti water mode on the middle of the skydeck also using Eggman's (spining elevator) is a lot easier now.

**Comment by Thesch28** [comment]
Quick question is the DC branding mod suppoused to change the name of the game's window to Sonic Adventure?
I read something like that on the changelog and the window of my game still says SonicAdventureDXPC.

**Comment by PiKeyAr** [comment]
Thanks for testing! Yes, it's supposed to change the window title, but I've only tested it with [one specific sonic.exe](http://mm.reimuhakurei.net/misc/sonic-U-crack.7z). It's good that you brought it up, perhaps I should add a version check or something to prevent potentially dangerous memory changes with different EXEs.

**Comment by PiKeyAr** [comment]
Just a heads up regarding the window title thing, there appears to be an issue with the Mod Loader's "Windowed Fullscreen" option. Working on it. You can track #53 to see progress.
