### ISSUE TITLE
Start Mispositioned, 640x480 scrolling background, Window Title Bug

### ISSUE THREAD

**Issue by cheatfreak47** [PiKeyAr/sadx_dreamcast#53]
(1) The position of "Start" there is a little bit off. should be moved over to the right by 29 pixels- so it's perfectly centered.
This image here should fix that slight off centering.
![p_enter_us_00](https://cloud.githubusercontent.com/assets/7818664/23165474/3f4545dc-f80a-11e6-90e4-d54db426abf0.png)
[Here is what this looks like in-game.](https://u.teknik.io/zN9Er.png)

---

(2) Next I have a bug to report with the title screen.
Running the game in 640x480 causes half the title screen background to scroll.
![sonic_2017-02-21_07-56-24](https://cloud.githubusercontent.com/assets/7818664/23165826/fe5e8888-f80b-11e6-9099-83ff4ab3d41e.png)
According to you, this is probably due to your optimizations done to DC_branding recently.

---

(3) Lastly, the window title doesn't seem to change properly on my end- BetterSADX uses the same EXE you have, so we know it isn't an EXE issue, perhaps it's mod related to what mods are loaded and in what order?

**Comment by PiKeyAr** [comment]
I have fixed 1 and 2, as for 3 it appears related to the "Windowed fullscreen" option in the Mod Loader, and I haven't been able to change it for some reason. It only works when that option is disabled (which it should if you're playing in windowed mode anyway).

Will push another update soon.

**Comment by PiKeyAr** [comment]
So MainMemory updated the Mod Loader and helped me replace the window title in a better way, so expect all 3 issues to be fixed in the next release.

**Comment by PiKeyAr** [comment]
I have updated the DC Branding mod with the fixes for all of the above, as well as custom code support. It should be available through the Mod Loader when the update feature is ready, in the meantime it's available on my [Dropbox](https://www.dropbox.com/sh/gwvgh94qurgq244/AAC6pP52mCz5v6bGM2ageZYOa?dl=0) and [MEGA](https://mega.nz/#F!Ewl1lLjY!iP5g2e_k_l7NxdeL66U5zA).

Also, new title screen:
640x480: ![640](https://cloud.githubusercontent.com/assets/23312549/23175916/4f899d9a-f8a4-11e6-8134-9252b11fa999.png)
High res: 
![sa](https://cloud.githubusercontent.com/assets/23312549/23175926/5a6cdc68-f8a4-11e6-8d62-0c1d3f2237f8.png)
