### ISSUE TITLE
Eggmobile Texture Glitch in Super Sonic Story Cutscene. (also happens in vanilla DX)

### ISSUE THREAD

**Issue by Thesch28** [PiKeyAr/sadx_dreamcast#54]
I was playing Super Sonic's story and I saw a texturing glitch with the Eggmobile in one cutscene.
(The one were knuckles says that the master emerald is back, etc) and then finds Eggman and the Eggmobile thrown on the grass but the Eggmobile's textures are all messed up this also happens in vanilla DX I don't know if this happens to anyone else, Here's a 100% save file if anyone wants to see if this happens: http://www.mediafire.com/file/ra0dej06emyhl2q/SonicDX01.snc
and here are the screenshots I took.
Vanilla DX: http://i.imgur.com/0iPq8dW.png
With DC Mods: http://i.imgur.com/PelS9ja.png

**Comment by PiKeyAr** [comment]
Interesting, looks like it uses a wrong PVM altogether. What's weird is that it doesn't seem to happen in the Steam version, judging by the footage I've seen so far.

To fix this, I imagine I'd have to locate the model and see what's going on with it. Maybe change the texlist to reference a different PVM, or just change texture indices.

**Comment by PiKeyAr** [comment]
The cutscene that loads that model is at 665B20.
The model itself is probably the one at 0x02EEB524 (memory).
There may be a texlist error because it's the same model that loads fine in the cutscene right before this happens.

**Comment by PiKeyAr** [comment]
I have confirmed that it's a code-related error. This doesn't happen on the Steam version, but it happens in SADX 2004 even with the PVMs from the Steam version.

This is really awful and I don't really know how to fix it.

**Comment by KNNSpeed** [comment]
Wouldn't this be more an issue for SADX:FE?

**Comment by Zetchzie** [comment]
Well this is new I never experienced this issue on Vanilla DX with my super old computer

**Comment by KNNSpeed** [comment]
Ignore my earlier post; doesn't happen in vanilla for me.

**Comment by KNNSpeed** [comment]
But, uh, well, this happened with mods on:
![img_3905](https://cloud.githubusercontent.com/assets/9886112/23341451/ebb9c5cc-fc15-11e6-9a9b-bc35d26d6852.JPG)

Also, isn't the eggmobile supposed to be on the ground, not floating? Because that doesn't even show up anymore. It just shows up floating behind Knuckles during the cutscene, which it also does in vanilla SADX.

**Comment by Zetchzie** [comment]
@KNNSpeed I figured as much i was about to test without it aswell. If it did do it again id think its a graphic card error

**Comment by PiKeyAr** [comment]
I can reproduce the Eggmobile issue without the Mod Loader in the 2004 version.

**Comment by KNNSpeed** [comment]
Hmm. How are you able to trigger it on vanilla? I still can't, starting from the Red Mountain entrance.

**Comment by PiKeyAr** [comment]
For me, it happens in the 2004 version if you just start Super Sonic's story. It doesn't happen on the Steam version.

**Comment by PiKeyAr** [comment]
According to ItsEasyActually, the problem is that it's calling a null texlist in that cutscene. Potentially fixable.

**Comment by PiKeyAr** [comment]
Aww yea
![untitled](https://cloud.githubusercontent.com/assets/23312549/23515885/e81195a2-ffae-11e6-8c96-91e973d55b41.png)
Thanks to ItsEasyActually who located the problem and MainMemory who helped me with the correct syntax, I can now include this fix in the DC Bosses mod.
