### ISSUE TITLE
Green door barriers in Egg Carrier Interior

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx_dreamcast#55]
In SA1, when a certain door (e.g. Hot Shelter entrance) cannot be opened, it has a green barrier thing with environment mapping. This is gone in SADX, apparently.

I don't really know where to start with this, but I guess I need to find that shield in SA1 first.

**Comment by PiKeyAr** [comment]
I found the model in SADX, and I've been able to recreate it ingame. I now need to find out when the barriers are supposed to appear in the story.

**Comment by PiKeyAr** [comment]
Gamma's story
1) The Hot Shelter entrance barrier is there from the start until clearing Red Mountain.
2) The E-101 Beta room barrier appears after the cutscene where Gamma sees Beta being reassembled and never disappears.

**Comment by PiKeyAr** [comment]
It's kind of a pity that the barriers aren't used outside Gamma's story (at least I haven't seen them in other characters' stories). I also felt like the game could benefit from having more of those barriers to indicate the character can't go to a certain room. So, I have implemented them with the following behavior:

Gamma's story
The Hot Shelter barrier is there at start, but disappears if Red Mountain is cleared
The E-101 Beta room barrier doesn't show up at start, but appears when Gamma gets the Jet Booster
The barriers on the Ammunition Room, the Hedgehog Hammer room and Water Reservoir doors never show up when playing as Gamma

Amy's and Big's stories
The Hot Shelter and Hedgehog Hammer room barriers don't show up when playing as Amy
All other barriers are always there

Everybody elsse
All barriers are always on

**Comment by Thesch28** [comment]
I think I saw those barriers on the DC version a long time ago but only with gamma, I really like the idea of this New implementation because it isn't only a fix but rather an improvement over The Dreamcast and DX versions of game.

**Comment by cheatfreak47** [comment]
Agreed, that custom implementation is better.

**Comment by PiKeyAr** [comment]
Hey, anyone up for a [test](https://www.dropbox.com/s/cuh24f9kohem8aj/EggCarrier_DoorsTest.zip?dl=0)?
It should be working for all characters, but I need to test if the E-101 room barrier shows up properly in Gamma's story. Or if anyone has a save right at the start of Gamma's story, please share it. Thanks!

**Comment by PiKeyAr** [comment]
I have tested Gamma's story, and it looks like the barriers are working as intended. An update will be pushed to all mirrors soon.

Feel free to reopen this (or open another issue) if you run into any problems with those barriers.

**Comment by PiKeyAr** [comment]
So over a year later I was able to get to the bottom of the problem - the object's code is still there but SADX just doesn't render the barrier's model at all - and I'm about to restore the original game's behavior. It's unfortunate but the improvements for other characters will have to go. My original implementation of the barrier is pretty lame because it adds objects to the landtable and hides them dynamically, which is a rough and sub-optimal way to do it. The new implementation will render the barriers as they were meant to (they are SET objects that display or not depending on some story flags). While this will get rid of door barriers for other characters, it's more accurate to the original game and a better implementation technically.
