### ISSUE TITLE
2nd List of Issues with Screenshots

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#61]
Hi again, PkR.

[FIXED]
1. I found a few more layering problems, this time in Hot Shelter.
![you cannot see inside only beyond](https://cloud.githubusercontent.com/assets/26051785/23484138/56f8568c-fe9b-11e6-905c-a0e4975ff356.png)
Using debug mode and looking up through this thing shows transparency issues, and you cannot see inside the model. I know you probably wouldn't notice this much at all during normal gameplay, but I thought I'd report it anyway.

[FIXED]
2. Then the animated mechanisms in the background have a problem that looks similar to what I reported yesterday regarding Lost World Act 3.
![layering problem](https://cloud.githubusercontent.com/assets/26051785/23484178/8faa3b58-fe9b-11e6-858e-b491fcbbe028.png)
![layering problems 2](https://cloud.githubusercontent.com/assets/26051785/23484183/92735f5e-fe9b-11e6-8821-9da978557758.png)
The problem is with the bottom parts of the machines.

...If you're wondering why I'm flying around with debug mode, it's because I was looking around an empty layout. I understand what you meant when you mentioned the billboard in Casinopolis, the water objects in Hot Shelter 1, and the bathroom lights in Hot Shelter 2. I made the appropriate edits to my own layout files to compensate for the water object being implemented into the landtable itself. Interesting that you made the billboard and fountain lights Knuckles-specific. And you removed the light part of the model for the bathroom lights, and made the lights part of the landtable. Can you recall any other area that has things like this?

[FIXED]
3. Found another layering problem in Speed Highway Act 3. The lights on the lamp object go behind this building.
![no lights](https://cloud.githubusercontent.com/assets/26051785/23484441/92d2c006-fe9c-11e6-9a5d-fc420ff39aa1.png)
![no lights 2](https://cloud.githubusercontent.com/assets/26051785/23484474/c30f60f8-fe9c-11e6-850d-5d307e4bfa8b.png)
Oddly, the shield graphic, both normal and magnetic, don't go behind the building.

4. It's a bit difficult to see, but Knuckles is visible behind the entire model here, not just the light.
![behind the light](https://cloud.githubusercontent.com/assets/26051785/23484879/82824562-fe9e-11e6-8afd-e774dc98460f.png)

5. Something is going on with these lights here.
![light ropes issue](https://cloud.githubusercontent.com/assets/26051785/23485011/2dfa99f8-fe9f-11e6-98d7-fef1dd647d54.png)

6. Standing from way up here, above the "machine room", in the blue light closest to the center of the screenshot, the ropes have a problem. Approaching the area will cause the ropes to correct themselves, and appear behind the light, as they should.
![more light layering problems](https://cloud.githubusercontent.com/assets/26051785/23485202/09d040c2-fea0-11e6-9b7e-062caa74c3ec.png)

I'll continue to add more problems throughout today if I find any more, but any I find tomorrow will be in a separate issue list.

**Comment by PiKeyAr** [comment]
I don't quite remember where else I remade SET objects as landtable objects, but looking at the code might help.

1 - Fixed... sort of. Not much else I can do with it
2 - Fixed
3 - Fixed
4, 5, 6 - require order-independent transparency.

Thanks for the report!

**Comment by supercoolsonic** [comment]
Awesome. And that'll be all the problems I report in this issue. I'll just look through empty levels tomorrow to find out what was made part of the landtables.
