### ISSUE TITLE
Windy Valley bridge model

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#63]
Have a few more things, here.

1. There's a z-fighting problem with the top of the beams in Sky Deck 3, and also a texture looking quite warped. I believe this also happens in SADX.
![cross z-fighting and texture warp](https://cloud.githubusercontent.com/assets/26051785/23564730/bd1830b0-0010-11e7-9aa3-8686ec2be7b5.png)

2. Another handful of small z-fighting problems in Sky Deck Act 3.
![minor z-fighting](https://cloud.githubusercontent.com/assets/26051785/23564781/fc78c116-0010-11e7-8174-7ce973700788.png)
There's a problem at each of the corners of these things.

3. Some more z-fighting in the corner here in Speed Highway Act 3.
![z-fighting in corner](https://cloud.githubusercontent.com/assets/26051785/23564806/1d1a4a02-0011-11e7-8eeb-12f4706b547d.png)
On the opposite side of this area is yet another z-fighting issue.

4. The billboard objects in Speed Highway Act 3 also have layering issues.
![billboard layering](https://cloud.githubusercontent.com/assets/26051785/23564947/55cafd10-0011-11e7-93e9-a1b8346fb12f.png)
![billboard layering 2](https://cloud.githubusercontent.com/assets/26051785/23564951/587d0b0c-0011-11e7-9a0a-969c0342e649.png)

Additionally, the entire object appears to be ignoring lighting. Only the ad itself is meant to ignore it. In the Dreamcast version, the border does not ignore lighting.
![dreamcast billboards](https://cloud.githubusercontent.com/assets/26051785/23564984/7863eddc-0011-11e7-95cc-9ab2f290f224.png)

5. I noticed that the bridge model being used in Windy Valley isn't the same as the one in the Dreamcast version.
SADX:
![sadx bridge model](https://cloud.githubusercontent.com/assets/26051785/23565007/92f12bec-0011-11e7-9a5e-f3a06ad4c0c6.png)

Dreamcast:
![sa bridge model](https://cloud.githubusercontent.com/assets/26051785/23565016/98a4506e-0011-11e7-9b2e-738383dbb6a2.png)
It's possible to port the model over, right? Or is there something wrong with the model in SADX? Other levels use the same model as the Dreamcast version, with no ropes dangling below the bridge. Ex: Red Mountain uses the same model as the Dreamcast.

**Comment by PiKeyAr** [comment]
Sadly there's little I can do about these.
1, 2, 3 - these are issues with the original assets, and fixing them would require remodeling work. Simply changing their position against each other creates visible seams and/or Z fighting in other areas.
4. The materials on the object itself don't seem to ignore lighting, but the code for that object is seriously messed up in SADX, and I can't even look at it because IDA fails to decompile it. Since it's broken in unmodded SADX too, maybe the author of SADXFE will be interested.
5. The model(s) are likely the same as far as scale is concerned, however this bridge is set up from several small parts in code, and the ropes are just a tiny model that gets duplicated and stretched around to make the ropes. I tried poking around it to see if I can change it, but it didn't work out. The function to render the rope model is at 007A5B43. I'd say also SADXFE material if it's deemed an issue in the first place.

**Comment by supercoolsonic** [comment]
The author of SADXFE is Morph, right? Or SonicFreak94? I don't think it'd be relevant to post these in his Palette Lighting feedback, so I don't know of any way for myself to immediately contact him. As far as making the rope render the same way as the Dreamcast, would it be possible to examine the coding for other bridges, like Ice Cap's or Red Mountain's, locate the rope rendering code there, and compare it to Windy Valley's?

**Comment by SonicFreak94** [comment]
Although it's for the code-portion of the mod, I have a repo for fixed edition [here](https://github.com/SonicFreak94/sadx-fixed-edition) if you'd like to report issues.

**Comment by supercoolsonic** [comment]
Ah. Thanks. I will do so in the future.

**Comment by PiKeyAr** [comment]
I was able to fix (4) by changing the blending mode for that object. Thanks @SonicFreak94 for helping me decompile that function.

**Comment by PiKeyAr** [comment]
Since the Windy Valley bridge model issue is a code bug, I'm closing this because I'm unlikely to be able to do anything about it.

**Comment by PiKeyAr** [comment]
Reopening for posterity.

**Comment by PiKeyAr** [comment]
I managed to spawn a Red Mountain bridge in Windy Valley by forcing the Windy Valley bridge to load the same data as the Red Montain bridge but with a patched texlist address. The breaking behavior worked too, so I think the data contains some values for the bridge's setup.

The Red Mountain data is at 0x024C9208, texlist pointer at 0x024C9250.
Windy Valley bridge stuff is at 0x00C66F28, texlist pointer at 0x00C66F70.
![image](https://user-images.githubusercontent.com/23312549/33834737-4dd34f82-dec7-11e7-9f0d-81b4fd0f8d7e.png)

**Comment by PiKeyAr** [comment]
some more stuff from the disassembly defined 
![image](https://user-images.githubusercontent.com/23312549/33835127-d5489142-dec8-11e7-8102-4833764e84f2.png)
The last pointer is interesting, it's pointing to a bunch of floats.

**Comment by PiKeyAr** [comment]
Yeah, screw this. The second NJS_MODEL_SADX pointer after the texlist one is pointing to the vertical rope model. Apparently its shape is different in Windy Valley and it causes issues.

**Comment by PiKeyAr** [comment]
...yeah this is retarded. The rope's model was changed in SADX, for whatever reason it was made longer. Restoring the SA1 model fixed it.
