### ISSUE TITLE
5th List of Problems with Screenshots

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#64]
Here's the next one. One question about a feature, some are layering, others are possibly coding.

1. Are we going to be able to have a rippling title screen at some point?

2. In Speed Highway Act 3, shields do not display behind the glass of the clock, or the newspaper stands.
![no shield only bolts](https://cloud.githubusercontent.com/assets/26051785/23582044/32558392-00e7-11e7-8454-b528ec38eeb7.png)
![no shield only bolts 2](https://cloud.githubusercontent.com/assets/26051785/23582045/35236ba2-00e7-11e7-9ccc-2552f1babd05.png)
![no shield only bolts 3](https://cloud.githubusercontent.com/assets/26051785/23582046/38138180-00e7-11e7-8d6a-01250d604f88.png)
The electric bolts from the magnet shield still do, though. This displays correctly on the Dreamcast version.

On another note, I know this problem this problem also exists on the Dreamcast, but is there any way to make objects that don't stop moving while the game is paused, stop moving?

3. In Casinopolis, the words on the pinball transport machines have some transparency problems.
![transparency in words](https://cloud.githubusercontent.com/assets/26051785/23582055/6154e32c-00e7-11e7-83aa-2223193e4b82.png)
This also happens with the Card and Slot transport machine, but it's not as noticeable. This does not happen on the Dreamcast. 

Also, the top part of the Card and Slot transport machine is supposed to be animated, but does not animate on SADX.

4. And then this texture.
![lighting effect conflicts with texture](https://cloud.githubusercontent.com/assets/26051785/23582059/76ecc93e-00e7-11e7-97f6-682d6a1f4ae2.png)
The lighting effect that "moves around the room" has a weird effect...only on this texture right here. And I mean, literally, right here. This texture is also used by the fountain, but the lighting effect does not cause the issue seen in the screenshot. But it happens over here. I couldn't even begin to explain why this happens.

**Comment by PiKeyAr** [comment]
Thanks for the report.

1) Maybe, but not in this project per se. Someone skilled with shaders may be able to do it.
2) Fixing those is probably too much trouble than it's worth, and there's little guarantee that it will even work after the "fix". So I'd say not interested.
3) Fixed using the same workaround as for the Casino billboard (no SET changes necessary). The animation is done in code using some UV trickery so that'll have to wait, if I can even fix it in the first place.
4) Fixed.

**Comment by PiKeyAr** [comment]
I've moved transparency stuff to a separate issue, otherwise considering this fixed.
