### ISSUE TITLE
Emerald Coast Act 1 — that “Alpha Sorting” bug still appears only when moving camera the opposite direction

### ISSUE THREAD

**Issue by LighteningXL** [PiKeyAr/sadx_dreamcast#70]
Emerald Coast Act 1 – that “Alpha Sorting” bug after the whale chase still appears when only having camera positioned toward the opposite angle. Reminds me of the old texture bug on the pond in Emerald Coast Act 2. ˡᵒˡ
![untitled](https://cloud.githubusercontent.com/assets/26220489/23670299/437ea914-0335-11e7-873e-6001db969c45.png)
![untitled0](https://cloud.githubusercontent.com/assets/26220489/23670305/45c6a5b4-0335-11e7-9aa8-8b0602c73283.png)
![untitled1](https://cloud.githubusercontent.com/assets/26220489/23670306/484205ea-0335-11e7-9273-ffdf286780b8.png)
![untitled2](https://cloud.githubusercontent.com/assets/26220489/23670310/4a6638b4-0335-11e7-9df5-0975f1ebab1c.png)
![untitled3](https://cloud.githubusercontent.com/assets/26220489/23670312/4c683b08-0335-11e7-9f52-32e8a28fdc51.png)
![untitled4](https://cloud.githubusercontent.com/assets/26220489/23670318/4ffbc550-0335-11e7-9051-b5d8d0945921.png)
![untitled5](https://cloud.githubusercontent.com/assets/26220489/23670319/51c1b93a-0335-11e7-8256-28b91f19b23d.png)
![untitled6](https://cloud.githubusercontent.com/assets/26220489/23670321/535c4f76-0335-11e7-8157-e74abd9de713.png)

**Comment by PiKeyAr** [comment]
See if it works with this DLL: https://mega.nz/#!Z5MjgZBC!WSxFHzwdZM9hcP_GGGBLZoe_9defPcVNjm54RQ2dhaA
or
https://my.pcloud.com/publink/show?code=XZqVxqZGtT5KTY5KvJJyXyGIe5RPbehlLWV

**Comment by LighteningXL** [comment]
Yay! It works. TY,VM!
