### ISSUE TITLE
10th list of problems with screenshots

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#76]
Tenth list!

1. The transparent texture along the bowling mechanism that appears here in the Dreamcast screenshot...
![bowling dreamcast](https://cloud.githubusercontent.com/assets/26051785/23825203/0e76e31c-064b-11e7-9355-003b936407a5.png)
...isn't transparent in SADX. The crowns and transparent texture are actually part of the mechanism object itself.

2. I tried out the new merry-go-round, and it looks great. However, I noticed that standing on the edge of the carpet right next to the merry-go-round makes Sonic move with it, even though he isn't touching it. As it turns out, this happens on the Dreamcast too, but you have to be much closer to the edge for it to happen in that version.

3. This may require order-independent transparency, but...
![tube rings](https://cloud.githubusercontent.com/assets/26051785/23825185/bb64d77e-064a-11e7-83dc-5a8ef882ec89.png)
The rings around the blue tube don't look like they're going behind the tube at all. It looks like a layering problem to me. Also, the cool light effect things you restored on this little light objects also appear in front of the blue glass.

4. Perhaps another case of order-independent transparency, but I'll bring it up anyway.
![rocket steam](https://cloud.githubusercontent.com/assets/26051785/23825258/099324ae-064c-11e7-9b16-1977200ccff8.png)
The rocket steam conflicts with the transparent light in Final Egg 3. This is the secret ring-loaded room, by the way.

5. I've noticed that the common switch looks different between SADX and Dreamcast.
SADX:
![sadx switch example](https://cloud.githubusercontent.com/assets/26051785/23825422/3bf42f8a-064f-11e7-96da-1532870c6002.png)

Dreamcast:
![dreamcat switch example](https://cloud.githubusercontent.com/assets/26051785/23825423/4080248c-064f-11e7-8bec-a720acdbf5b7.png)
Is it lighting that makes it look different? A different model? Or is it something that can be restored in SADX by itself? ...Or can we conclude that the SADX switch just looks so much better?

...Also, as I'm noticing in the screenshot, the roof object has different texture mappings between both versions as well.

6. I noticed that these models in Sky Deck 3 are untextured on the bottom. I think this problem persists into SADX, as well.
![untextured](https://cloud.githubusercontent.com/assets/26051785/23835725/4c20aa64-073a-11e7-9295-1db4052d59ea.png)

7. I noticed the little red light machine is much shinier on Dreamcast. (Also, preview at a fix for the layout of Act 1, I guess)
SADX:
![sadx light](https://cloud.githubusercontent.com/assets/26051785/23842575/3ec02f18-0783-11e7-9e39-991401d33a0c.png)

Dreamcast:
![dreamcast light](https://cloud.githubusercontent.com/assets/26051785/23842584/454d5c8e-0783-11e7-90ae-4a96d9ec27b6.png)

8. The fog in the conveyor belt room in Act 1 is a little bit darker on Dreamcast.
Dreamcast:
![conveyor room fog dreamcast](https://cloud.githubusercontent.com/assets/26051785/23842639/b75113fc-0783-11e7-9f17-77688f707fe0.png)

SADX:
![conveyor room fog sadx](https://cloud.githubusercontent.com/assets/26051785/23842650/befa7094-0783-11e7-8d97-ad3f8f8ae061.png)

9. The model on top of the elevator is dark on Dreamcast, but a creamy color in SADX.
SADX:
![elevator top sadx](https://cloud.githubusercontent.com/assets/26051785/23842773/c4688aec-0784-11e7-867c-04a8bbd15b12.png)

Dreamcast:
![elevator top dreamcast](https://cloud.githubusercontent.com/assets/26051785/23842777/c785b7fe-0784-11e7-9a78-cb0063bba3fa.png)

10. Item boxes appear to ignore lighting on SADX, while they acknowledge it on Dreamcast:
Dreamcast:
![items and lighting on dreamcast](https://cloud.githubusercontent.com/assets/26051785/23842893/9e108696-0785-11e7-9d16-b317fd64f6b7.png)

SADX:
![items and lighting on sadx](https://cloud.githubusercontent.com/assets/26051785/23842895/a08ecdf6-0785-11e7-8083-2dceadbb9f5d.png)

11. Aha! How about this? Side-by-side comparison! The fog in Act 3 of Final Egg is much thicker than it currently is on SADX.
![act 3 fog comparison](https://cloud.githubusercontent.com/assets/26051785/23842958/59dfee7a-0786-11e7-92a3-296ae7b30262.png)

12. Not sure if this is because of the PL mod or if it's a difference between models, but the zipline machines and little lights have different lighting currently between versions.
![red mountain mechanisms](https://cloud.githubusercontent.com/assets/26051785/23843200/073bacde-0788-11e7-94bb-949e47ff90a7.png)

Also, I noticed the little yellow light objects use a different texture.

13. The little purple lights in Speed Highway differ in appearance between versions.
![purple pyramids](https://cloud.githubusercontent.com/assets/26051785/23843512/601349e6-078a-11e7-8b5d-e261166f47f2.png)

14. I also came to notice that there's a very faint pink tinge to certain things in the 2nd half of the Goin' Down sequence that is currently absent in SADX. I tried to get good comparisons, but the pink tinge is indeed visible.
![pink light](https://cloud.githubusercontent.com/assets/26051785/23843663/8705d9b4-078b-11e7-8d79-0fce86a092c0.png)

15. The fog in Act 3 is thicker on Dreamcast.
![act 3 in speed highway fog](https://cloud.githubusercontent.com/assets/26051785/23843787/40e64620-078c-11e7-80d6-875423d56600.png)

Almost done with essays, and then I'm on Spring Break. By the way, did you fix the looping of the grass noise in Mystic Ruins? The one I mentioned in my first post here? I remember it didn't loop at all when I first tried it, but now it is. I downloaded the Sound Overhaul 2 that you added onto the pCloud. Does that version contain any enhancements? ...Or am I going crazy?

**Comment by Zetchzie** [comment]
You really should use Demul its allot more accurate this could be an inaccuracy on nullDC's end

**Comment by supercoolsonic** [comment]
It's not an emulator issue. As far as I'm concerned, NullDC only has problems with collision (the tap-dance of doom), and transparency, along with rendering shields. *would* use Demul if I could figure out how to set it up.

**Comment by Zetchzie** [comment]
Yep Demul renders it the same way in Twinkle park though I wouldn't mess with it it looks like a error on the DC than something to tweak on PC. Demul is pretty easy to set up its just the bios setup thats tricky. Only trade off in Demul is the sound gets warped if the FPS ever drops and they are focusing on Accuracy so you can bump up the internal res atm

**Comment by Zetchzie** [comment]
ill send you a working demul link

**Comment by supercoolsonic** [comment]
"Unable to find 'mpr-21931.ic501' in romset 'dc'."

**Comment by Zetchzie** [comment]
you may have to delete the configuration files and set it up but everything is there

**Comment by Zetchzie** [comment]
same way you do with nulldc unless you been mounting the image files i may have deleted some plugins so you can get them back from demuls latest build.

**Comment by Zetchzie** [comment]
i may have deleted some plugins so you can get them back from demuls latest build.  Basicly you go to GD-ROM and select your cdi, gdi, or chd file and load it then start the emulator.

**Comment by Zetchzie** [comment]
no problem ^^ you can find most stuff through google lol

**Comment by Zetchzie** [comment]
heres some issues present in all versions but i think can be fixed.
Seems to ignore shadows
![capture](https://cloud.githubusercontent.com/assets/15071652/23826935/e10a5ad2-0675-11e7-9b6b-285fc1b13ed6.PNG)
 
![capture1](https://cloud.githubusercontent.com/assets/15071652/23826944/00c796aa-0676-11e7-8ef0-34ca6195ac2e.PNG)

![capture2](https://cloud.githubusercontent.com/assets/15071652/23826946/0a39c6e0-0676-11e7-8831-06e416ce043a.PNG)

**Comment by supercoolsonic** [comment]
Finally finished! Ha ha! ...Anyway, thanks for your effort to contribute towards fixing the game. However, I must remind you of a few things. And I'm by no means angry or trying to be mean, but...

-This is the issue thread for reporting problems with PkR's DC conversion mods. Please refrain from posting problems from vanilla SADX.

-Only report problems that happen due to the DC mods being active, or report things that have yet to be "Dreamcast-ified".

-Please create your own issue report on the main page when you wish to report problems. Do not post reports in someone else's report.

Okay? Great. Now then, I have actually looked at the pool room problem before. That indeed does happen on Dreamcast too. Unfortunately, those circle models are part of the level model itself. The only way to completely fix it would be to make it solid, as it currently relies on flat collision cylinder objects to appear solid. There is no collision object in the game that Sonic can run on and is slanted. Therefore, the only solution is the one I mentioned previously.

As for the other two, those are very minor. I'm not sure if those happen on Dreamcast or not. Even if they do, don't expect them to get fixed anytime soon.

Again, not trying to sound mean. Not trying to be mean, either. If you submit reports within the guidelines above, you could do PkR a tremendous favor and help point out things he may have missed!


I will soon begin to dissect the Emerald Coast layout files after I eat some supper. I guess my only remaining question to completely clarify, PkR, is how should I go about giving you the fixes? Upload the files on their own, and make a post in the report you made a few days ago, describing each individual change, perhaps along with a screenshot? Or should I just upload a folder with pictures and a text files with all the fixes I made?

**Comment by Zetchzie** [comment]
Not mean at all ^^ I understand. they do happen in DC version aswell. since no one is currently ironing out that stuff idk where i should go i'm not sure if these would qualify for SADXFE or not

**Comment by supercoolsonic** [comment]
Actually, I think they would technically qualify for SADXFE. That mod's goal is to touch up the original game, so it's best post there. SonicFreak94 is the author of that mod.

**Comment by PiKeyAr** [comment]
1 - if it isn't a bug with NullDC, I'll try to restore that
2 - not fixable
3 - yes, this is going to #42 until transparency is sorted out (hopefully soon)
4 - same as above
5 - see here https://github.com/SonicFreak94/sadx-dc-lighting/issues/22
The roof can be restored, though
6 - those parts don't have proper UVs, so simply enabling the "use texture" flag wouldn't work. I guess not really fixable via normal means
7 - might be a different object model. Will look into it
8 - very low priority, but I may look into it
9 - that's a palette selection issue, will be fixable when this is implemented https://github.com/SonicFreak94/sadx-dc-lighting/issues/43
10 - item capsules are a known "broken" object in SADX, this manifests in many ways. #42 for now
11 - will look into it, though if it changes dynamically I probably won't restore it for this level
12 - most likely palette selection
13 - also palette selection, possibly alpha issues too
14 - might be related to landtable specular, see here https://github.com/SonicFreak94/sadx-dc-lighting/issues/20
15 - the fog adjusts dynamically in this level, which is doable but I thought it wasn't necessary for this level. It was most likely done for performance reasons in the original game and to obscure draw distance pop-in, which isn't a problem in SADX

**Comment by PiKeyAr** [comment]
1, 5 (roof), 7, 12 (lights), 13 - fixed.

10 will be fixed in a SADXFE update.

Fog can't be fixed (at least at the moment) because SADX uses fixed fog distances, which means making fog thicker in one area will introduce inaccuracies in other areas. In addition, there's a certain limit to how much fog distance can be adjusted, as going over it disables fog completely. In both cases in Final Egg it's impossible to mimic the SA1 fog within the SADX limits.

**Comment by PiKeyAr** [comment]
1, 5 (roof), 7, 12 (lights), 13 - fixed.

10 will be fixed in a SADXFE update.

Fog can't be fixed (at least not at the moment) because SADX uses fixed fog distances, which means making fog thicker in one area will introduce inaccuracies in other areas. In addition, there's a certain limit to how much fog distance can be adjusted, as going over it disables fog completely. In both cases in Final Egg it's impossible to mimic the SA1 fog within the SADX limits.

**Comment by PiKeyAr** [comment]
The majority of this has been fixed except fog (which is a separate issue) and untextured areas, which I'm not interested in. An alpha rejection problem in Final Egg Act 2 still remains.
