### ISSUE TITLE
Twinkle Park Entrance Door Errors

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#77]
Clipping through textures
![capture](https://cloud.githubusercontent.com/assets/15071652/23835033/832647f2-0736-11e7-82b1-2f161cd1523d.PNG)

![captures](https://cloud.githubusercontent.com/assets/15071652/23835037/93a87fd2-0736-11e7-82aa-e8836b795ed4.PNG)

**Comment by supercoolsonic** [comment]
Before PkR gets to this, I guess I can comment, as well. The first one seems fixable by moving the door back a little bit, while the second involves just moving the door so that the doors aren't more on the inside of the room. However, I'm not sure if it'll still look good if that's done...

**Comment by PiKeyAr** [comment]
supercoolsonic: feel free to pick it up in your SET fixes if you're interested

**Comment by PiKeyAr** [comment]
supercoolsonic: feel free to pick it up in your SET fixes if you're interested. Would make my life easier as well lol.

**Comment by supercoolsonic** [comment]
Uhh....yessir! Right away, sir! I'll post the results as soon as I can.

**Comment by PiKeyAr** [comment]
Cool, thanks! I guess this can be closed then.
