### ISSUE TITLE
Other Issues in Transparency?

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#78]
The light leaves a bit of lining in the bulb not present in DC
![capturegg](https://cloud.githubusercontent.com/assets/15071652/23836295/6019aea0-074c-11e7-8046-7d4a02a0b28b.PNG)

The ballons are not transparent as in DC

PC
![captured](https://cloud.githubusercontent.com/assets/15071652/23836338/fb9e714e-074c-11e7-86e5-e8db2c1b49ef.PNG)

DC
![captureg](https://cloud.githubusercontent.com/assets/15071652/23836350/1c4c72e2-074d-11e7-9a0c-e095b6bbe22a.PNG)

**Comment by PiKeyAr** [comment]
Unfortunately these will have to go to #42 until proper transparency sorting is implemented...
