### ISSUE TITLE
Final Egg Inaccuracies 

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#80]
Playing through Final Egg I noticed a difference 

The Lids are shiney in DC
![capture](https://cloud.githubusercontent.com/assets/15071652/23840609/06569974-077d-11e7-9e8e-2f45102bf3f1.PNG)
Not shiney in PC Also the Robots look a little different in color?
![ssss](https://cloud.githubusercontent.com/assets/15071652/23840618/1894baee-077d-11e7-959a-a73e5bbe87e6.PNG)

More pinkish in DC but Brownish in PC
![captureg](https://cloud.githubusercontent.com/assets/15071652/23840642/3c2affc2-077d-11e7-8ff7-8eea9ac8853c.PNG)

**Comment by PiKeyAr** [comment]
Nice catch! Looks like the hatch model uses a different texture in SADX.

As for lighting on the badniks, I will be able to fix that when the PL mod has an API for me to manipulate materials directly.

**Comment by Zetchzie** [comment]
you sure you restored the model? im still getting sadx Hatch doors and the shininess of the hatches isn't there

**Comment by PiKeyAr** [comment]
It was working a while ago but now it doesn't seem to be working for some reason. I'll look into it.

**Comment by PiKeyAr** [comment]
Huh ok, so the replacement is working, but there are some material colors in the SA1 model that shouldn't be displayed. Try the version I just uploaded.

**Comment by Zetchzie** [comment]
will do brb

**Comment by supercoolsonic** [comment]
The very front of the lid appears more like silver on Dreamcast. Is that the Lantern Engine, or material color? Or something else?

**Comment by PiKeyAr** [comment]
The environment maps look different because SADX flips them horizontally. There's a "DC Environment Maps" mod in the main package. Anyway I'm gonna consider this fixed.

**Comment by Zetchzie** [comment]
Im using the DC ENV mod I wonder why its not working?

**Comment by PiKeyAr** [comment]
It is working, but, like I said, there may be differences in how textures are transformed for environment maps in that particular level in SA1.

**Comment by Zetchzie** [comment]
oh alright.

**Comment by PiKeyAr** [comment]
The environment maps on the gachapon throwers should be restored as of today's update. The lighting should also be correct because that's now implemented in the API.
