### ISSUE TITLE
Egg Carrier Inaccuracies 

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#81]
This rooms lighting is way off its supposed to have a dim lighting with some shades of blue and the table might be different
PC
![ssss](https://cloud.githubusercontent.com/assets/15071652/23844816/e50503fa-079a-11e7-9042-0d27553f4f42.PNG)

DC
![capture s](https://cloud.githubusercontent.com/assets/15071652/23844832/ffbdf3a0-079a-11e7-8bb3-22935d9b0781.PNG)

Idk about you but the lighting for the objects in the room looks different from the DC
PC
![capture](https://cloud.githubusercontent.com/assets/15071652/23844864/37f17738-079b-11e7-8800-0e5d88d5aad8.PNG)

DC has more shine and its darker
![capturez](https://cloud.githubusercontent.com/assets/15071652/23844879/4e35d958-079b-11e7-8c45-5f4a6c724803.PNG)

**Comment by PiKeyAr** [comment]
The table object (alpha issues) will be fixed next time I push an update; as for the lighting inaccuracies, that seems to be related to incorrect PL file selection for Egg Carrier landtables. I just made an issue here: https://github.com/SonicFreak94/sadx-dc-lighting/issues/46
