### ISSUE TITLE
11th List of Problems with screenshots

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#82]
Alrighty, here we go.

1. The low-detail model of the wing that breaks off in Sky Deck has its textures screwed up in SADX.
![sky deck wing low](https://cloud.githubusercontent.com/assets/26051785/23876099/e4c4f4e4-0809-11e7-94a1-00afd76c5fa5.png)

2. At the *very end* of Sky Deck Act 2, the textures here are different.
![sky deck wrong texture](https://cloud.githubusercontent.com/assets/26051785/23876145/0d7a1342-080a-11e7-869b-3c5b2ee9719f.png)

3. There's some minor z-fighting going on with these things in Act 2, as well. Happens in Dreamcast, too. Should be fixable by scooting one model 0.01 in a specific direction.
![sky deck z-fighting](https://cloud.githubusercontent.com/assets/26051785/23876180/26cba248-080a-11e7-89f5-82a033f85fdc.png)

4. Okay, this doesn't look normal. It's at the start of Final Egg Act 3.
![possible z-fighting](https://cloud.githubusercontent.com/assets/26051785/23878449/75ecafba-0815-11e7-8c3c-650a249f8df9.png)
As it turns out, this happens on the Dreamcast as well. Upon further inspection, it looks like....well, I don't actually know! I think the texture might be horribly warped, which probably means that it won't be easy to fix. However, in vanilla SADX, they...took the lazy way out and changed the model of the room to use a different texture there, thus hiding the light effect completely. I believe the texture may still be warped in vanilla SADX, so the question would then become would it be possible to look at other model data in the level and copy it over to fix this issue?

5. This object in Final Egg ignores lighting on the Dreamcast.
![ignoring lighting](https://cloud.githubusercontent.com/assets/26051785/23878945/390cc4ce-0818-11e7-8b5f-1382bbaa1bb5.png)

About the lighting being broken on item capsules, I'm now aware that when you break the item capsule, the bottom part of it will correctly acknowledge lighting. So, there has to be some coding in there that works right. Only the glass surrounding the item on the model is meant to ignore lighting. Also, the floating item boxes perfectly acknowledge lighting.

6. The screen on this object in Hot Shelter is meant to ignore lighting.
![dim screen](https://cloud.githubusercontent.com/assets/26051785/23879277/073347f0-081a-11e7-8608-2c14d0cd7a11.png)

7. The trapdoors on the Dreamcast version blend in more with the surrounding floor.
![false floors](https://cloud.githubusercontent.com/assets/26051785/23879748/270f1088-081d-11e7-9bcb-26c23dfc5d40.png)
On vanilla SADX, the trapdoors match the other floor tiles, but now they need to be either ported from the Dreamcast version or have their textures looked at.

8. There's a problem with a Buyon in Amy's Fakery Way (Twinkle Park Act 3). 
![buyon in the floor](https://cloud.githubusercontent.com/assets/26051785/23880552/63c1d344-0822-11e7-9584-1f11d41b7c1b.png)
It walks through the floor, as opposed to all other buyons in the level, and even ones in this act, that properly walk on the floor. I tried moving it up by at least 5 units, but it still continued to clip through the floor. Might be a bounds problem. I'm not sure. This also happens in vanilla SADX.

By the way, regarding that Red Mountain issue I reported in my previous list, I noticed something else. The little yellow lights, their cube base uses a different texture. I noted this in my previous list, as well.

I will get to working on the SET layouts for Twinkle Park tomorrow.
Edit: I would start working on them now, but it appears the pCloud server is experiencing a lot of traffic, and I don't have PkR's versions of the Twinkle Park layout files on my computer, so I can't really start until that's sorted out.

**Comment by Zetchzie** [comment]
4 is being looked at in the PL mod afaik

**Comment by supercoolsonic** [comment]
Oh. Okay. Thanks for letting me know.

**Comment by PiKeyAr** [comment]
1, 2, 6, 7 - Fixed

3) Uhh not really interested. If it's SET stuff, feel free to experiment with those.
4) The UVs are set up like that, maybe it was intentional, but I dunno. I don't see any similarly shaped lantable pieces so I guess it isn't really fixable. And in general I don't fix design flaws with the original assets.
5) That's a landtable piece. It doesn't have the ignore light flag in the SA1 landtable, but maybe the game has a global material override for it. Fixed.
8) That's likely a coding issue (it wouldn't spawn at all if bounds were involved), so I don't really know what to do with it. I'd say SADXFE material.
