### ISSUE TITLE
TODO: Integrate SA1 textures for non-level PVMs

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#83]
So here it is, All textures besides those in your mods have been replaced with the Cleaner DC Counterparts Directly from Sonic Adventure International. 

This is to make sure all is correct.

[DC2PC Texture Pack](https://drive.google.com/file/d/0B1ZzvlogSUERREYwdUxhT1lWV3M/view?usp=sharing)

**Comment by Zetchzie** [comment]
May need to repack them back into PVMs Seems to lag the game a tad bit

**Comment by PiKeyAr** [comment]
Since this is now integrated into the main mod, any texture issues can be reported as general project issues.
