### ISSUE TITLE
Different Go–Kart Undertexture

### ISSUE THREAD

**Issue by LighteningXL** [PiKeyAr/sadx_dreamcast#85]
Grey and Black
![untitled](https://cloud.githubusercontent.com/assets/26220489/23895974/0c1ab3c0-087e-11e7-8ff2-eee350b174d2.png)

Just Black
![untitled1](https://cloud.githubusercontent.com/assets/26220489/23895976/0d303000-087e-11e7-85c2-288eac065812.png)

**Comment by Sonikko** [comment]
It looks almost the same to me, it's still checkered, gray and black. Unless you're talking about the shadow?

**Comment by Zetchzie** [comment]
check your Contrast and brightness

**Comment by PiKeyAr** [comment]
It was a material color issue. From my experience the Dreamcast version ignores material colors pretty much all the time, while SADX uses them, but some of them look odd. I've adjusted the material color to make it look more like SA1.
