### ISSUE TITLE
Hot Shelter Inaccuracies 

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#88]
Texture is used twice on here when it should only be once
![capture](https://cloud.githubusercontent.com/assets/15071652/23937080/fd1f63c6-092b-11e7-88c6-b3e4c9e30141.PNG)
DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23937103/25f9db64-092c-11e7-97bc-6ff7b698787a.PNG)

**Comment by Zetchzie** [comment]
Fish in the tank are different there using two of the same
![capture](https://cloud.githubusercontent.com/assets/15071652/23937210/bb66e322-092c-11e7-960e-1ccb6cd30158.PNG)

DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23937219/c9571cc2-092c-11e7-91de-a0ffff1d5a50.PNG)

**Comment by Zetchzie** [comment]
lighting is a LITTLE different in DC
![capture](https://cloud.githubusercontent.com/assets/15071652/23937453/0b8a4b40-092e-11e7-9f53-c0c1b6730c69.PNG)

DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23937473/1b1f1784-092e-11e7-85c6-f1f03b0820fa.PNG)

**Comment by Zetchzie** [comment]
Machine is lit differently 
![capture](https://cloud.githubusercontent.com/assets/15071652/23937595/b866d400-092e-11e7-9b57-47e073fc1ae1.PNG)

DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23937607/c63d497e-092e-11e7-929b-3e9685b4bc95.PNG)

**Comment by Zetchzie** [comment]
different lighting on the roller
![capture](https://cloud.githubusercontent.com/assets/15071652/23937685/1d257e0a-092f-11e7-8bcf-abe5ff8a5be4.PNG)

DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23937686/283cf336-092f-11e7-9b33-b5445a4dadaf.PNG)

**Comment by Zetchzie** [comment]
Wall texture comparison
![capture](https://cloud.githubusercontent.com/assets/15071652/23937830/e6d9d19c-092f-11e7-8cf4-6ac0e0617f1e.PNG)
 
DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23937848/f74990ee-092f-11e7-93d4-d8cf9ff48f5d.PNG)

**Comment by Zetchzie** [comment]
Lighting on the lamp is different and the dc version has fencing on the hatch 
![capture](https://cloud.githubusercontent.com/assets/15071652/23938002/aa368acc-0930-11e7-8dbc-3d56877f17d6.PNG)
DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23938012/b99647aa-0930-11e7-9c1b-55c9b9a764d3.PNG)

**Comment by Zetchzie** [comment]
The gears have different lighting
![capture](https://cloud.githubusercontent.com/assets/15071652/23938179/95f35bb6-0931-11e7-9458-f7c02d153383.PNG)
DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23938180/95ff8a6c-0931-11e7-991f-1926ac106703.PNG)

**Comment by Zetchzie** [comment]
an enemy is meant to spawn here but dosnt in PC
![capture](https://cloud.githubusercontent.com/assets/15071652/23938422/a44b726a-0932-11e7-9d42-32b51eb338cd.PNG)
DC
![capture2](https://cloud.githubusercontent.com/assets/15071652/23938423/a452bc96-0932-11e7-8e41-aacf849969da.PNG)

**Comment by PiKeyAr** [comment]
Thanks for the report!

>Texture is used twice on here when it should only be once
>lighting is a LITTLE different in DC
>and the wall texture repetes in DC
>Machine is lit differently
>Bathroom doors are different aswell
>an enemy is meant to spawn here but dosnt in PC

Fixed.

>different lighting on the roller 
>The gears have different lighting

This is palette selection, which I can't fix on my end.

>Fish in the tank are different there using two of the same

If you mean they use different models, they are spawned randomly every time you load the level in both SA1 and SADX.

>Lighting on the lamp is different 

I think I fixed it, sort of.


>the dc version has fencing on the hatch 

I would fix this, but it wouldn't make much sense because Amy is supposed to go through it. The hatch is sealed in Gamma's level.

**Comment by Zetchzie** [comment]
the lamp seems to ignore lighting the lights coming out of it are brighter in DC and the lamp itself is brighter in color.

**Comment by PiKeyAr** [comment]
Ah I guess I forgot that one. Will update soon.

**Comment by Zetchzie** [comment]
the shine on the machines is a palette selection issue right? I think I saw it posted before by someone on here

**Comment by PiKeyAr** [comment]
If you mean those computer-like things, try with the latest update on MEGA, should be fixed now. If you mean the gears, yeah it's a palette selection issue.

I'm having trouble with uploading to MEGA right now, so it will be up in a few hours.

**Comment by Zetchzie** [comment]
the screens on the machines are corrects but the machine around the machine ignores its lighting

**Comment by PiKeyAr** [comment]
Looks more like a specular thing rather than ignoring lighting. They're using their DC model anyway, so it's a palette issue most likely.
