### ISSUE TITLE
Massive slowdowns in DC_ChaoGardens

### ISSUE THREAD

**Issue by LighteningXL** [PiKeyAr/sadx_dreamcast#92]
According to a tweet who said he had stutter, I am also experience heavy impact in performance whenever I enter any of the chao gardens. 

__________Specs__________
GPU: NVIDIA GTX 1080
CPU: Intel(R) Core(TM) i7-4790K CPU OC @4.40GHz
Memory: 16.00 GB RAM @1860Mhz
PSU: 700w
OS: Windows 10
__________________________

DC gardens will slowdown even having set to a 480p resolution with without AA applied. Setting Frame rate to potato–low seemed to fix it, but Normal is slow, and High makes the gardens even more sluggish. Clip level and Fog emulation didn't change anything in performance. Turning off the PL mod didn't help either. DX gardens don't lag for me though.

**Comment by PiKeyAr** [comment]
Is it still slow with this DLL? https://mega.nz/#!F402mT7R!mEC_vh7T_GSpMkD49Xga7n2DTcoTjMJGKL2CgxaWGH8 it has object loading disabled.

**Comment by Zetchzie** [comment]
Strange im not exp any slowdowns in chao gardens

**Comment by PiKeyAr** [comment]
I found a potential issue with my code and corrected it. Try the latest update from MEGA. If you can't download from MEGA, use this temporary link: https://www.dropbox.com/s/lyhwufuu3hr458y/DC_ChaoGardens.zip?dl=0

**Comment by PiKeyAr** [comment]
According to at least one report and my own testing on a computer where I could reproduce the issue originally, it's fixed now. Feel free to reopen this if you're still experiencing slowdown.
