### ISSUE TITLE
12th list of problems with some screenshots

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#93]
I'm a bit pressed for time today, with some personal stuff going on, so Red Mountain might have to wait until tomorrow, unfortunately. But I'll submit another list to make up for it.

1. The coding in Twinkle Park that made the transparent texture appear for Sonic's bowling mechanisms no longer makes the texture show up. (Oops?)

2. There's transparency problems with the little logo on the front side of the roller coaster.
![rollercoaster alpha](https://cloud.githubusercontent.com/assets/26051785/24058115/def0d856-0b17-11e7-9036-9a72170c6385.png)

3. The train announcer immediately announces that the "train will be departing soon" in the Mystic Ruins as soon as you step into the area, but on Dreamcast, it only announces it once you approach the train. Does this have to do with the train loading in?

4. Either the skybox at the end of Red Mountain Act 2 is lower on the Dreamcast, or the clouds are higher on Dreamcast.
![skybox](https://cloud.githubusercontent.com/assets/26051785/24060589/f661c8b0-0b21-11e7-956f-a29e96aba709.png)

**Comment by PiKeyAr** [comment]
1) The texture was always there, it was a sorting issue with the child model causing the bottom part of the mechanism to become invisible. I had to hide it in the model and readd it as a landtable piece. Anyway I can't reproduce it. Make sure you have updated the entire mod folder, not just the DLL.
2) Fixed
3) I don't know, probably won't bother with this
4) Fixed
