### ISSUE TITLE
GOMA's Limbs messed up

### ISSUE THREAD

**Issue by Zetchzie** [PiKeyAr/sadx_dreamcast#94]
The seal shows up normaly in its bubble but after you enter the chao garden its apendeges are mixxed 
**_This is after applying DC_General Mod_**
![capture](https://cloud.githubusercontent.com/assets/15071652/24081434/ac6c7214-0c89-11e7-95ad-c99a706be5a8.PNG)

**Comment by PiKeyAr** [comment]
Looks like there's another animation involved with animals in the Chao gardens, which I can't find in SA1. Reverted for now.
