### ISSUE TITLE
Hero and Child Chao Texture error with DC_ChaoGardens

### ISSUE THREAD

**Issue by LimitCrown** [PiKeyAr/sadx_dreamcast#95]
The textures that the Hero Chao and Child Chao have use look-up tables to determine their colors. Because the mod affects those textures, Hero Chao and Child Chao consequently have the wrong appearance.

**Comment by PiKeyAr** [comment]
This is because the mod adds textures to AL_BODY.PVM, which has textures that use external palettes. I thought it extracted correctly with those palettes applied, but apparently it's still messed up. I guess there's little I can do unless SADXModLoader or SA tools add support for textures with external palettes.

**Comment by PiKeyAr** [comment]
I found another solution. Try the latest update on MEGA (make sure you delete the textures/AL_BODY folder if you're updating).

**Comment by LimitCrown** [comment]
I downloaded the latest update to DC_ChaoGardens, but the problem still persists.

**Comment by PiKeyAr** [comment]
Did you delete the texture pack for AL_BODY? Try deleting the entire mod folder before updating.

**Comment by LimitCrown** [comment]
Oh. I deleted the the DC_ChaoGardens folder before updating, but I neglected to delete the AL_BODY folder afterwards. The problem with the Hero and Child textures is resolved! However, the texture used for the Two-Tone Grey and Two-Tone Black Eggs looks weird.

**Comment by PiKeyAr** [comment]
Make sure there's AL_BODY.PVM in the mod's system folder. It's part of the update.

**Comment by LimitCrown** [comment]
AL_BODY.PVM isn't in the system folder. After looking at the folder in MEGA, the file doesn't appear to be there yet.

**Comment by PiKeyAr** [comment]
Should be up now, but in case it doesn't show up, use this temporary link: https://www.dropbox.com/s/2g7aaamvuw1mqz3/DC_ChaoGardens.zip?dl=0

**Comment by LimitCrown** [comment]
I downloaded it again. Both issues are now resolved.

**Comment by PiKeyAr** [comment]
Alright, cool. Thanks for the report!
