### ISSUE TITLE
Cowgirl texture error

### ISSUE THREAD

**Issue by Stachekip** [PiKeyAr/sadx_dreamcast#97]
The Cowgirl optional mod appears to have a texture error towards the bottom. I have the mod below DC Casinopolis on my modloader list. The animation also appears to be playing faster than on the original Japanese Dreamcast version.

![sonic_2017-03-21_03-21-48](https://cloud.githubusercontent.com/assets/26565561/24136594/ec05dafc-0de5-11e7-8ca5-c0d0a4da0ad8.jpg)
![chrome_2017-03-21_03-22-02](https://cloud.githubusercontent.com/assets/26565561/24136606/f931f242-0de5-11e7-8bb0-9ee53c002657.png)

**Comment by PiKeyAr** [comment]
I fixed the texture, but found a serious accuracy issue with the restored cowgirl model. Looks like there's additional code involved with animation based UV shifts, which I won't be able to restore. I'll take this mod down until there's a solution for that.

**Comment by PiKeyAr** [comment]
I fixed the texture, but found a serious accuracy issue with the restored cowgirl model. Looks like there's additional code involved with animation based on UV shifts, which I won't be able to restore. I'll take this mod down until there's a solution for that.
