### ISSUE TITLE
Was animation water speed that slow in Station Square?

### ISSUE THREAD

**Issue by LighteningXL** [PiKeyAr/sadx_dreamcast#99]
I thought the previous speed of the water animation in Station Square were accurate to SA.

**Comment by PiKeyAr** [comment]
I never really tried to match it with SA1 since SA1 runs at 30 FPS and even then some water animations look a bit too fast to me. I may revert it at some point, but I don't see this as an issue.

**Comment by PiKeyAr** [comment]
As of today's update water animation speed in Station Square and Mystic Ruins should be the same with SA1.
